### ISSUE TITLE
submit refused by nicehash

### ISSUE THREAD

**Issue by huiyiqun** [ethereum-mining/ethminer#151] opened 2017-07-14 02:04 UTC
With the latest(master branch) build on my desktop, I see following error repeatedly:

```
  ℹ  09:50:21|stratum  Invalid nonce size.
  ✘  09:50:21|stratum  :-( Not accepted.
```

I use the pool of nicehash, following is my command:

```
ethminer -SP 2 -U -S daggerhashimoto.jp.nicehash.com:3353 -O xxxxxxxxxxxx
```

What's the problem?

**Comment by piotr-dobrogost** [comment] 2017-07-14 15:40
I witness the same problem.
Everything is OK when using version `0.11.0.dev0` but when using version `0.12.0.dev0` I get `Invalid nonce size` as well. Both versions are built using `gcc5 (GCC) 5.3.1 20160406 (Red Hat 5.3.1-6)` from https://copr.fedorainfracloud.org/coprs/leebc/compat-gcc-5/ I'm using GPUs with Nvidia 1070 chipset.
Observations:

- new version was working OK for about a couple of hours today and errors started to appear just recently (about an hour ago)
- error seems to go away when lowering the degree to which the cards are overclocked

**Comment by AndyLavr** [comment] 2017-07-16 06:41
I witness the same problem. :(

**Comment by cnilsecure** [comment] 2017-07-16 07:58
where i can d/l this 0.12.0.dev0 ?

**Comment by jimmykl** [comment] 2017-07-16 08:02
@cnilsecure if you're after a windows build: https://ci.appveyor.com/project/ethereum-mining/ethminer/build/175/job/a6l30ujhr10qg0kr/artifacts

**Comment by cnilsecure** [comment] 2017-07-16 08:05
@jimmykl  thanks, but actually more interested in the source code i just cant find it anywhere in the
release section

**Comment by jimmykl** [comment] 2017-07-16 08:13
@cnilsecure You can either clone it with git or download the zip from https://github.com/ethereum-mining/ethminer/archive/master.zip. Add any pending pull requests from https://github.com/ethereum-mining/ethminer/pulls

**Comment by AndyLavr** [comment] 2017-07-16 10:02
I used this fix, it works fine.

$ ./ethminer -V
ethminer version 0.12.0.dev0
Build: Linux/g++/Release



------------------------------------------------------------------------------------------------------------------
--- MinerAux.h.orig	2017-07-15 09:51:55.000000000 +0300
+++ MinerAux.h	2017-07-16 12:13:54.000000000 +0300
@@ -712,7 +712,8 @@
 				this_thread::sleep_for(chrono::milliseconds(1000));
 				time++;
 			}
-			cnote << "Difficulty:" << difficulty << "  Nonce:" << solution.nonce;
+			string nonceHex = toHex(solution.nonce);
+			cnote << "Difficulty:" << difficulty << "  Nonce:" << nonceHex;
 			if (EthashAux::eval(current.seedHash, current.headerHash, solution.nonce).value < current.boundary)
 			{
 				cnote << "SUCCESS: GPU gave correct result!";
@@ -815,13 +816,14 @@
 					}
 					this_thread::sleep_for(chrono::milliseconds(_recheckPeriod));
 				}
+				string nonceHex = toHex(solution.nonce);
 				cnote << "Solution found; Submitting to" << _remote << "...";
-				cnote << "  Nonce:" << solution.nonce;
+				cnote << "  Nonce:" << nonceHex;
 				cnote << "  headerHash:" << solution.headerHash.hex();
 				cnote << "  mixHash:" << solution.mixHash.hex();
 				if (EthashAux::eval(solution.seedHash, solution.headerHash, solution.nonce).value < solution.boundary)
 				{
-					bool ok = prpc->eth_submitWork("0x" + toHex(solution.nonce), "0x" + toString(solution.headerHash), "0x" + toString(solution.mixHash));
+					bool ok = prpc->eth_submitWork("0x" + toString(solution.nonce), "0x" + toString(solution.headerHash), "0x" + toString(solution.mixHash));
 					if (ok) {
 						cnote << "B-) Submitted and accepted.";
 						f.acceptedSolution(false);

----------------------------------------------------------------------------------------------------

**Comment by chfast** [comment] 2017-07-18 14:29
@AndyLavr why don't you submit this as a pull request?

**Comment by AndyLavr** [comment] 2017-07-18 16:45
@chfast  I'm not yet sure what I did right ... What do you say?

**Comment by EoD** [comment] 2017-07-18 19:02
@AndyLavr it's common to discuss code changes in a pull request, even if they are not being merged in the end. It's easier both for you and for the reviewer.

About your change. It seems you are basically reverting 8e6a7015a425b20fb9f59c03345e501232041b2d and partially 2895cb48bbaefc1daf786e57e0dee3285a5bf512 .

**Comment by chfast** [comment] 2017-07-18 20:45
@AndyLavr it looks like the right fix.

**Comment by evilny0** [comment] 2017-07-18 21:20
It's fixing the issue in my case :).

**Comment by AndyLavr** [comment] 2017-07-18 22:00
Yes, the problem still exists, but on a smaller scale.

**Comment by AndyLavr** [comment] 2017-07-18 22:32
@chfast I added a pull request - #165

**Comment by piotr-dobrogost** [comment] 2017-07-19 12:06
Out of curiosity why nicehash is the only pool not accepting new nonces?

**Comment by chfast** [comment] 2017-07-19 15:43
In general I probably have broken this in 2895cb48bbaefc1daf786e57e0dee3285a5bf512, but the fix is not so easy as I thought.

**Comment by AndyLavr** [comment] 2017-07-19 17:56
It works, but it is not stable, the first 15 minutes is normal, after they begin to refuse ...

**Comment by oleng** [comment] 2017-07-19 18:34
how is this related to #167?
There's no authorized connection to begin with, unlike this issue.

**Comment by chfast** [comment] 2017-07-19 19:43
I have to read their spec first. This is suspicious line: https://github.com/ethereum-mining/ethminer/blob/master/libstratum/EthStratumClient.cpp#L520. I have no idea what this is about.

At the moment we can and a log dumping whole JSON submit message, maybe we will find something interesting there. Is anyone interested in doing this? I'm not sure when I will be able to test nicehash mining.

BTW, the reason nicehash is special is they have different stratum protocol.

**Comment by oleng** [comment] 2017-07-19 19:48
@chfast one detail that might help, I tested dev version of ethminer 0.11.0 with `--cuda-parallel-hash` on nicehash to compared it with claymore, so the extra nonce requirement was not a problem to establish connection to their pool. I have no idea if there's any changes happened in between.

**Closed** 2017-07-20 13:35 UTC
Labels: bug

**Comment by EoD** [comment] 2017-07-21 19:21
I can confirm that the current build works again :+1:
