### ISSUE TITLE
Error CUDA mining: CUDA error in func set_constants at line 142 invalid device symbol

### ISSUE THREAD

**Issue by jyouyj** [ethereum-mining/ethminer#1659] opened 2018-10-25 23:24 UTC
OS - Ubuntu 18.04 latest updates
Cuda compilation tools, release 10.0, V10.0.130
Cuda driver 4.10
Device: GeForce GTX 1070
There are enough GPU memory for DAG. 

Code build fine, but run time gives fatal error:
cu 16:15:16 cuda-0   Using device: GeForce GTX 1070 (Compute 6.1)
cu 16:15:16 cuda-1   Using device: GeForce GTX 1070 (Compute 6.1)
cu 16:15:16 cuda-2   Using device: GeForce GTX 1070 (Compute 6.1)
cu 16:15:16 cuda-3   Using device: GeForce GTX 1070 (Compute 6.1)
cu 16:15:16 cuda-4   Using device: GeForce GTX 1070 (Compute 6.1)
cu 16:15:17 cuda-0   Set Device to current
cu 16:15:17 cuda-0   Resetting device
cu 16:15:17 cuda-2   Set Device to current
cu 16:15:17 cuda-2   Resetting device
cu 16:15:17 cuda-4   Set Device to current
cu 16:15:17 cuda-4   Resetting device
cu 16:15:17 cuda-3   Set Device to current
cu 16:15:17 cuda-3   Resetting device
cu 16:15:17 cuda-1   Set Device to current
cu 16:15:17 cuda-1   Resetting device
cu 16:15:20 cuda-3   Allocating light with size: 16.000 MB
 X 16:15:20 cuda-3   Error CUDA mining: CUDA error in func set_constants at line 142 invalid device symbol
cu 16:15:20 cuda-4   Allocating light with size: 16.000 MB
cu 16:15:20 cuda-0   Allocating light with size: 16.000 MB
cu 16:15:20 cuda-2   Allocating light with size: 16.000 MB
cu 16:15:20 cuda-1   Allocating light with size: 16.000 MB
 X 16:15:20 cuda-0   Error CUDA mining: CUDA error in func set_constants at line 142 invalid device symbol
 X 16:15:20 cuda-2   Error CUDA mining: CUDA error in func set_constants at line 142 invalid device symbol
 X 16:15:20 cuda-4   Error CUDA mining: CUDA error in func set_constants at line 142 invalid device symbol
 X 16:15:20 cuda-1   Error CUDA mining: CUDA error in func set_constants at line 142 invalid device symbol
Trial 1... 
0
Trial 2... 
0
Trial 3... 
0
Trial 4... 
0
Trial 5... 
0
min/mean/max: 0/0/0 H/s
inner mean: 0 H/s

**Comment by AndreaLanfranchi** [comment] 2018-10-26 08:20
Duplicate of #1658

**Comment by AndreaLanfranchi** [comment] 2018-10-26 18:03
Closing. See #1658

**Closed by AndreaLanfranchi** 2018-10-26 18:03 UTC
Labels: committed, duplicate
