### ISSUE TITLE
What's the difference between this fork and Genoil's?

### ISSUE THREAD

**Issue by Immortalin** [ethereum-mining/ethminer#157] opened 2017-07-15 06:38 UTC

**Comment by JHGitty** [comment] 2017-07-15 08:44
Duplicate question, see #154

**Comment by EoD** [comment] 2017-07-17 18:16
There are a lot of commits by chfast in Genoil's repository: https://github.com/Genoil/cpp-ethereum/commits?author=chfast

And there are a few commits by Genoil in chfast's repository: https://github.com/ethereum-mining/ethminer/commits?author=Genoil

**Comment by chfast** [comment] 2017-07-18 13:24
Duplicate of #154.

**Closed by chfast** 2017-07-18 13:24 UTC
