### ISSUE TITLE
Ethminer unusable with Celeron CPU

### ISSUE THREAD

**Issue by n4ru** [ethereum-mining/ethminer#74] opened 2017-06-27 22:59 UTC
So, I have 7 GPUs running on a measly Celeron with 8GB of RAM. When it's just one, I can run it just fine. When I bump it up, the text output becomes so slow that it ends up freezing and won't mine properly. CPU usage spikes up to 100%.

This issue doesn't happen with any other miner. I'm assuming it is related to the way text is output to the console and I'm wondering if there's either a flag I'm missing or if there is another fix available.

My pagefile is larger than the sum of all GPU's RAM.

**Comment by ajthemacboy** [comment] 2017-06-27 23:11
Same issue for me. Claymore's miner and other coin miners don't have high CPU usage like this for me. I have an Athlon II x2 CPU, definitely low end, but since other miners work I think it's related to ethminer.

**Comment by jimmykl** [comment] 2017-06-27 23:20
Try the --farm-recheck flag to reduce the speed of the text output. From the help:
```--farm-recheck <n>  Leave n ms between checks for changed work (default: 500). When using stratum, use a high value (i.e. 2000) to get more stable hashrate output```

**Comment by jimmykl** [comment] 2017-06-27 23:23
Also if the miner is hanging when it's starting up and loading the DAGs onto the GPUs you could try changing the --dag-load-mode flag to sequential or single:
```--dag-load-mode <mode> DAG generation mode."
			parallel    - load DAG on all GPUs at the same time (default)
			sequential  - load DAG on GPUs one after another. Use this when the miner crashes during DAG generation
			single <n>  - generate DAG on device n, then copy to other devices```

**Comment by n4ru** [comment] 2017-06-27 23:28
No dice to any of those. As soon as "cudaminer0" text shows up, it shits the bed regardless of settings.

**Comment by ajthemacboy** [comment] 2017-06-27 23:30
`--dag-load-mode single 0` helped me a lot. Startup time is a lot slower but the 100% CPU usage is gone. Thank you!

**Comment by ajthemacboy** [comment] 2017-06-27 23:31
edit: I lied, I still get 100% CPU usage, but it goes away after about 20 seconds.

**Comment by jimmykl** [comment] 2017-06-27 23:33
@n4ru Sorry to hear that. I don't have any other suggestions at the moment sorry.

@ajthemacboy Yeah even my pentium 4560 gets pegged for a while during the setup. Hopefully someone can work on an actual fix.

**Comment by ajthemacboy** [comment] 2017-06-27 23:37
Ok, clearly I should have tested a bit more before responding the first two times. 

With `--dag-load-mode single 0`, my _startup_ time is a lot lower. However, once I get up and running, it randomly and frequently goes up to 100% CPU and the screen only prints one character at a time. 

Additionally, my hashrate is only 92 MH/s max with 4 GTX 1060s, using `--cuda-parallel-hash 2`. My hashrate mining with Claymore's miner is 94 MH/s constantly. I'm not sure why these optimizations aren't working for my cards.

**Comment by jimmykl** [comment] 2017-06-27 23:39
--cuda-parallel-hash 4 should be optimum for 1060s. I was about to reply to you in the other thread – davilizh said: 

> This code is optimized for GP106 with 1GPC GDDR5 case, and may be helpful for other chips. You can scale the “#define PARALLEL_HASH 4” in dagger_shuffled.cuh from 1 to 8 to check whether can improve performance for your GPU.

on https://github.com/ethereum-mining/ethminer/pull/18  

I'm not sure what 1GPC means though, maybe 3GB card?

**Comment by omento** [comment] 2017-06-28 02:11
What operating systems are you guys running? I'm using CentOS without any of these issues. Is this potentially Windows specific?

**Comment by n4ru** [comment] 2017-06-28 02:24
I suppose it could be. I am on Windows 10.

**Comment by ajthemacboy** [comment] 2017-06-28 02:28
I am on Windows Server 2016.

**Comment by justinwyer** [comment] 2017-06-28 05:26
This only happens on windows, ethminer works okay on Linux with a Celeron. I have rigs running both.

**Comment by gigi1231** [comment] 2017-06-28 08:33
ethminer.exe -U -v 2 -L sequential --dag-load-mode single 0 -S eu2.ethermine.org:4444 -SP 1 -O 

wallet.name --farm-recheck 2000 --cuda-parallel-hash 4

tried this, no luck. still takes forever to load ...

**Comment by JHGitty** [comment] 2017-06-28 12:45
Same issue here, Windows 10 x64 with 7x GPU (1060s)

**Comment by JHGitty** [comment] 2017-06-28 12:49
Running multiple instances with 2 GPU per instance seems to be a valid workaround for this issue.

ethminer.exe --farm-recheck 200 -U --cuda-devices 0 1
ethminer.exe --farm-recheck 200 -U --cuda-devices 2 3
ethminer.exe --farm-recheck 200 -U --cuda-devices 4 5

**Comment by ET-Bent** [comment] 2017-06-28 13:01
100% CPU usage regardless of number of GPUs. Ubuntu Linux 16.04.2.

**Comment by omento** [comment] 2017-06-28 14:52
To be clear, are you all running the release candidate?

**Comment by ET-Bent** [comment] 2017-06-28 14:55
In my case running `ethminer 0.9.41-genoil-1.1.7`

**Comment by ajthemacboy** [comment] 2017-06-28 15:12
@omento This occurs for me on the RC and 0.10.0, as well as on Genoil's miner.

**Comment by omento** [comment] 2017-06-28 15:24
Just trying to consolidate as much info for @chfast as possible, could you guys provide the following info so it's globbed together? Apologies if this feels redundant.

1. Operating System (Include Version)
2. Graphics Driver Version
3. Graphics Cards in Use
4. Version of Ethminer used (all version)
5. Built from source or pre-built binaries?
6. If source were there any errors/warning in the build process? What are they? Any issues retrieving libraries? What GCC/CMAKE version was used?

**Comment by omento** [comment] 2017-06-28 15:42
@ET-Bent Could you try this binary? Just built it from the latest dev source (with CUDA 8 support).

[ethminer.tar.gz](https://github.com/ethereum-mining/ethminer/files/1109288/ethminer.tar.gz)

**Comment by JHGitty** [comment] 2017-06-28 17:09
@omento 

1. Windows 10 x64 (newest release, including Creators Update)
2. latest nvidia stable driver
3. 7x GTX 1060 (6GB)
4. the latest RC release
5. pre-built binary (RC release)

The issue behind this is that the text output becomes really really slow because of a full load of the CPU (100% CPU usage). I think the text output and mining is not seperated from each other?

Shouldn't the CUDA-feature prevent from 100% CPU usage, even on a very slow G4400 CPU?

**Comment by n4ru** [comment] 2017-06-28 19:42
I have identical settings as JHGitty except I use 3GB cards.

**Comment by ajthemacboy** [comment] 2017-06-28 19:48
Operating System: Windows Server 2016 Standard, build 1607
Graphics Driver Version: 382.33
Graphics Cards in Use: GTX 1060 6GB
Version of Ethminer used: 0.10.0 and the pre-release with optimizations 
Built from source or pre-built binaries: Pre-built binaries tested only

**Comment by ET-Bent** [comment] 2017-06-28 20:51
@omento I appreciate all your efforts to help me.

I just rebuilt all my nodes today so they use the latest `ethminer` version built from source (`0.11.0.dev0`). Now everything is fine and we are soaring around 1-2% CPU usage :+1: 

Cheers!

For future time travellers reading this: **Build the latest version from source >= `0.11.0.dev0` will fix the abnormal CPU usage. Also make sure you are not using cpp anymore ;)

**Comment by ajthemacboy** [comment] 2017-06-28 23:30
@ET-Bent I'm glad to know it's fixable. However, I'm having trouble compiling it on Windows. 
- Do I need VS 14 2015 to compile?
- How do I install Hunter?!?!? I can't find any binaries anywhere.

I really have no clue what I'm doing, any help is appreciated.

**Comment by thghdbs** [comment] 2017-06-29 06:04
Win 10 Pro
Celeron G3900
6x1070 

Confirming that rc1 will not load. After the first few lines of loading the system crashes.

**Comment by thghdbs** [comment] 2017-06-29 12:29
@ET-Bent could you link a zip with the executor and dlls (and everything else) compiled for Windows 10 that you mentioned does not have the Celeron 100% CPU bog down issue?

**Comment by guillermo82** [comment] 2017-06-29 13:00
If you are using the latest binary, try using the --cuda-schedule option
sync should put cpu to about 3% but is the slowest
yield cpu is at 100% but responsive system (sort of)
spin screws up the system if you have more GPU cores than CPU cores (it might be an even/uneven issue, but no way I can test that here)

**Comment by guillermo82** [comment] 2017-06-29 13:05
And don't worry about the slow startup, after it does the DAG calculation everything runs smooth.. Running on Windows 10 Creator update with newest nvidia drivers and 6x GTX 1070 Evga FTW at +100/+650 clock mem OC

**Comment by ajthemacboy** [comment] 2017-06-29 13:39
@guillermo82 --cuda-schedule sync seemed to help me for a bit, but I'm still getting 100% CPU usage for 20-30 seconds pretty frequently.

**Comment by guillermo82** [comment] 2017-06-29 13:41
@ajthemacboy you can also try the auto one... I've set that now and even though I have 100% cpu usage the miner seems to be performing as advertised...

**Comment by yalokin** [comment] 2017-06-29 16:18
I also have such a problem. Windows 10, 6 X gtx 1060, and CPU Celeron 3990

**Comment by thghdbs** [comment] 2017-06-29 16:41
I replaced the Celeron G3990 with a Pentium G4560 and the fail to load / typewriter slow load problem is solved. It still bogs a little for a few seconds, but it works brilliantly after load.

Windows 10 Pro Creators
1070 x 6
SSD
2x4gb RAM

The G4560 has 50% more cache, a higher clock, hyperthreading, and a faster memory interface. 

The G3900 just can't cut it. Even with nothing running it is laggy. Maybe with Linux it is fine, but with Windows 10, forget it. 

Hope this helps.

**Comment by ET-Bent** [comment] 2017-06-29 19:52
@everyone asking me about a compiled binary -> Sorry I am running my miners on Linux (which is also highly recommended).

You can build `ethminer` as stated in the README. cmake will fetch Hunter.

**Comment by twist2k** [comment] 2017-07-01 03:21
On Windows try executing from PowerShell instead of CMD. Between that and changing the Farm Recheck speed, it seems to have totally fixed my slow downs I was experiencing.

Specs;
G4500 CPU
2 x 4GB RAM
120GB SSD
7 x GTX 1070

**Comment by guillermo82** [comment] 2017-07-01 03:54
@twist2k so what command are you running now?

**Comment by ajthemacboy** [comment] 2017-07-01 14:53
`-farm-recheck` set higher helped me alot, but Ethermine tells me to use a value of 200. Is it OK for me to use a higher value? Will I make less?

I now get about 100 MH/s on 4 1060 6GBs.

**Comment by omento** [comment] 2017-07-01 15:00
200ms is much to low to get a stable hashrates result. I believe it's a typo considering the `--help` results say to use 2000ms for stratum. I personally use 60000ms for once a minute.

**Comment by ajthemacboy** [comment] 2017-07-01 15:03
I think every of the ethereum pools I've looked at has 200 ms in their ethminer example commands, so I'm not sure what's up with that. Thank you, I will stick to 2000.

**Comment by michael-pesce** [comment] 2017-07-01 15:15
Are we sure farm-recheck has no bearing on actual mining? Read this elsewhere: 

> --farm-recheck is the frequency in milliseconds that ethminer will poll geth (or eth-proxy) for new work

Shouldn't we want to check for new work very frequently? Otherwise we'd be wasting cycles on old problems. Right?

**Comment by omento** [comment] 2017-07-01 15:27
I'm pretty sure. I have 2x 1070's running (OC'd) with a reported hashrate in the terminal of ~60MH/s, averaged ~61MH/s on Ethermine, and had between 45-65 shares per hour (usually mid to high 50's). Those were pretty much identical results to Claymore. All with a 1 minute check.

**Comment by michael-pesce** [comment] 2017-07-01 15:35
I am not familiar with the code, but below is the relevant bit in MinerAux.h.

Looks to me like farm-recheck does define how often the miner polls for new work, and theoretically that might not impact hash rate, but definitely would impact shares. A longer wait period might lead to more stale shares? What % of your solutions are stale? 

					if (hh != current.headerHash)
					{
						x_current.lock();
						previous.headerHash = current.headerHash;
						previous.seedHash = current.seedHash;
						previous.boundary = current.boundary;
						current.headerHash = hh;
						current.seedHash = newSeedHash;
						current.boundary = h256(fromHex(v[2].asString()), h256::AlignRight);
						minelog << "Got work package: #" + current.headerHash.hex().substr(0,8);
						f.setWork(current);
						x_current.unlock();
					}
					this_thread::sleep_for(chrono::milliseconds(_recheckPeriod));

**Comment by omento** [comment] 2017-07-01 15:42
About 1-2% at most, some hours none. I could be totally wrong on this, but for my personal use I didn't see much of an impact. Had similar results with Claymore if I'm remembering correctly. I'm not currently mining, but if you wanted you could always give it a go. Try 2000, as it's recommended by the help forba few hours then try 200.

**Comment by michael-pesce** [comment] 2017-07-01 15:46
I am at 200ms (on a Celeron btw, with no issues, though on Ubuntu) with same stale rate. There's probably some staleness threshold, perhaps it's just beyond 2 seconds (and certainly 200ms). 

On a more general level, I do agree the verbose output could be cut down. I use monit to poll ethminer output (piped to log files) to make sure everything is running (due to occasionally freezes via OCing) and the log files get big fast. Need to add rotation or something.

**Comment by twist2k** [comment] 2017-07-01 23:05
@guillermo82 ethminer.exe --farm-recheck 1000 -U --cuda-schedule sync -S server:port -FS backup-server:port -O 0xWALLET.PC is what I am using at the moment. I may tweak with it a bit, but this is working pretty good right now!

**Comment by chfast** [comment] 2017-07-03 15:37
Can you try this PR: <https://github.com/ethereum-mining/ethminer/pull/110>?

**Comment by n4ru** [comment] 2017-07-04 05:18
Unable to build currently. Any 64-bit linux binaries available?

**Comment by marcovillar** [comment] 2017-07-05 04:37
I solved this problem. thanks god 4 days of intense coding working perfectly on celeron cpu.

**Comment by cnilsecure** [comment] 2017-07-05 05:33
Please please share, I been looking everywhere,All my rigs are Celeron based and I cant use this optimization.

**Comment by jimmykl** [comment] 2017-07-05 06:21
@marcovillar If you've tested it sucessfully you should make a PR for review and wider testing

**Comment by ChronoXNL** [comment] 2017-07-05 07:12
@chfast : Latest build seemed to have solved the issues for me on 2 machines. Tested with latest build #112.

Setup: 7 x 1070, celeron 3930, 8gb mem, z270a chipset.

**Comment by ajthemacboy** [comment] 2017-07-05 12:47
The new release works great for me! Mining at about 98 MH/s, tyvm @chfast <3

**Comment by gigi1231** [comment] 2017-07-05 14:40
works great, thank you! used https://github.com/ethereum-mining/ethminer/releases/tag/v0.11.0

**Comment by JHGitty** [comment] 2017-07-05 20:26
I can confirm - latest v0.11.0 release is fixing the issue - somebody can close this ticket. Thank you very much for fixing this @chfast  !!!

**Closed** 2017-07-05 20:54 UTC

**Comment by ebbbang** [comment] 2017-08-05 03:15
It still doesn't work for me ...

**Comment by derubm** [comment] 2017-08-05 03:48
if it is still a text issue to you, try    >>    -v 1     <<
disables allmost everything excpet information and error output.

**Comment by ebbbang** [comment] 2017-08-05 19:48
Still no luck ...
CPU stayed at 100% and system restarted after a crash ...

**Comment by derubm** [comment] 2017-08-05 20:32
ebbang could you provide a bit more information about your rig?
CPU Model, Ram, GPU model , OS, Miner Version, driver version etc ..

**Comment by ortakpayda** [comment] 2017-08-06 19:54
I also have this problem although I have Pentium.
My rig:
Intel Pentium G4400
5x 8GB Asus GeForce GTX 1070 Strix OC
1x 8GB Asus GeForce GTX 1070 Strix 
geforce 382.53
Windows 10 with the necessary updates done
miner version 0.11 and 0.12dev

I really want to stop using claymore but with ethminer I can't mine properly 😞

**Comment by derubm** [comment] 2017-08-07 15:17
@ortakpayda 
check if you can generate the DAG sequential or single, that might take load from the system.

> ` -L, --dag-load-mode <mode> DAG generation mode.
        parallel    - load DAG on all GPUs at the same time (default)
        sequential  - load DAG on GPUs one after another. Use this when the miner crashes during DAG generation
        single <n>  - generate DAG on device n, then copy to other devices
`

**Comment by ebbbang** [comment] 2017-08-08 09:39
@derubm My Rig:
Intel Pentium G4400
6x 8GB Gigabyte GTX 1070 G1 Gaming
GeForce 384.94
Windows 10
miner version 0.11 and 0.12dev

I tried with -v 1 & also with single/sequential DAG generation mode. Still it does not work ...

**Comment by jimmykl** [comment] 2017-08-08 09:53
@ebbbang Have you updated to the latest mobo BIOS and upped Windows' virtual memory? (See Increase virtual memory on [url]http://1stminingrig.com/best-windows-setup-configuration-tweaks-for-mining/[/url])

**Comment by ebbbang** [comment] 2017-08-08 10:37
@jimmykl I'll check for the mobo BIOS today ...
And I have done all windows tweaks ...

**Comment by xixou2** [comment] 2017-08-23 15:55
Remove the -G option and only keep -U

    -G,--opencl  When mining use the GPU via OpenCL.
    -U,--cuda  When mining use the GPU via CUDA.

When both -G and -U are specified, the miner works but uses one CPU core.

**Comment by ajthemacboy** [comment] 2017-08-26 20:10
@xixou2 No one here was using both.

**Comment by xixou2** [comment] 2017-08-26 20:46
Maybe they were by mistake.

**Comment by dest4** [comment] 2017-11-06 09:18
Using a 1070 on linux / Cuda 8, ethminer 0.13.0.dev0, i5 Quad core, I had 100% CPU usage on a single core whatever the logging options, using the OpenCL kernel (-G).
I recompiled ethminer with the following flags 
`cmake .. -DETHASHCUDA=ON -DETHASHCL=OFF`
Now I'm using the Cuda kernel (-U) and I get minimal CPU usage.

**Comment by dougbacelar** [comment] 2017-12-13 23:03
Tried to mine eth for the first time using this miner with the following code in a .bat script:

```setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
ethminer.exe --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -v 1 -O <Ethereum_Address>.<RigName>
```

CPU overloaded and restarted my Rig twice, reached temperatures of over 100C.

I am back to zCash mining for the time being. My CPU stays at a stable 40C while mining zCash.

ethminer 0.12.0
**4x** GTX 1070
i7 4790k
win10

**Comment by derubm** [comment] 2017-12-14 19:16
@dougbacelar  replace -G with -U

**Comment by dougbacelar** [comment] 2017-12-14 22:59
@derubm thanks! I dont understand why, but it worked.

**Comment by Logic-Net** [comment] 2018-02-04 19:42
I had the same problem, mining with claymore and CPU stay in 50 percent..
the problem resolved by disabling windows search and superfetch:
1) Press the Windows logo key + R at the same time, and type in services.msc
2) Locate Windows Search option, double click it to enter its Properties window.
3) Change the Startup type to Disabled. Then click Apply and OK to save your change.

and the same for superfetch (Properties - Stop - and Startup type Disable)

I hope these settings help other people
I struggled for ten days until I solved the CPU issue 50%

If you think I was useful to you, you can donate me a beer by paypal :))

**Comment by dhanaraj1** [comment] 2018-02-21 05:21
@derubm Thanks man !!

**Comment by Logic-Net** [comment] 2018-02-21 10:31
and if the problem persists, you have too much overclocking on one GPU
usually the GPU which has fan on zero.
reduce overclocking to that board and everything becomes stable.

**Comment by AndreaLanfranchi** [comment] 2018-02-21 10:41
If I may add just one more hint.
Please note that when power-limiting the GPU below their "natural" consumption, the CPU load increases a lot. (direct experience on Linux !)
