### ISSUE TITLE
Speed is always 0 Mh / s (OpenCL old version?)

### ISSUE THREAD

**Issue by aashidham** [ethereum-mining/ethminer#1294] opened 2018-06-23 00:05 UTC
Hello, I have `Ubuntu 16.04.4 LTS` (`xenial`) with a Radeon RX 550 Series graphics card. I'm trying to use OpenCL 1.1 to mine with it. However, `ethminer` just gives back 0.00 Mh / s when I'm trying to mine with it.

Here is the output for `ethminer`:
```
test@test:~$ ethminer -G --pool stratum+tcp://0xdeadbeef@us1.ethpool.org:3333
 m 19:38:25 ethminer ethminer 0.15.0rc2
 m 19:38:25 ethminer Build: linux/release
 i 19:38:25 ethminer Found suitable OpenCL device [Radeon 550 Series (AMD POLARIS12 / DRM 3.25.0 / 4.13.0-45-generic, LLVM 5.0.0)] with 15398063308 bytes of GPU memory
 i 19:38:25 main     Selected pool us1.ethpool.org:3333
 i 19:38:25 stratum  Trying 35.185.92.48:3333 ...
 i 19:38:25 stratum  Connected to us1.ethpool.org [35.185.92.48:3333]
 i 19:38:25 stratum  Spinning up miners...
cl 19:38:25 cl-0     No work. Pause for 3 s.
 i 19:38:25 stratum  Subscribed to stratum server
 i 19:38:25 stratum  Authorized worker 0xdeadbeef
 i 19:38:25 stratum  Job: #fcfeef68… us1.ethpool.org [35.185.92.48:3333]
 i 19:38:25 stratum  Pool difficulty: 4.00K megahash
 i 19:38:25 stratum  New epoch 194
cl 19:38:28 cl-0     Platform: Clover
cl 19:38:28 cl-0     Device:   Radeon 550 Series (AMD POLARIS12 / DRM 3.25.0 / 4.13.0-45-generic, LLVM 5.0.0) / OpenCL 1.1 Mesa 17.2.8
cl 19:38:28 cl-0     OpenCL 1.1 not supported, but platform Clover might work nevertheless. USE AT OWN RISK!
cl 19:38:30 cl-0     OpenCL kernel: Stable kernel
 X 19:38:30 cl-0     Build info:<unknown>:0:0: in function ethash_calculate_dag_item void (i32, %union.compute_hash_share addrspace(1)*, %union.compute_hash_share addrspace(1)*, i32): unsupported initializer for address space

 X 19:38:30 cl-0     OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_MEM_OBJECT (-38)
 m 19:38:30 ethminer Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
```

Here is the output of `glmark2`:
```
=======================================================
    glmark2 2014.03+git20150611.fa71af2d
=======================================================
    OpenGL Information
    GL_VENDOR:     Advanced Micro Devices, Inc.
    GL_RENDERER:   Radeon 550 Series
    GL_VERSION:    OpenGL ES 3.1.13529 Release
=======================================================
```

Here is the output of `clinfo`:
```
Number of platforms                               1
  Platform Name                                   Clover
  Platform Vendor                                 Mesa
  Platform Version                                OpenCL 1.1 Mesa 17.2.8
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd
  Platform Extensions function suffix             MESA

  Platform Name                                   Clover
Number of devices                                 1
  Device Name                                     Radeon 550 Series (AMD POLARIS12 / DRM 3.25.0 / 4.13.0-45-generic, LLVM 5.0.0)
  Device Vendor                                   AMD
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.1 Mesa 17.2.8
  Driver Version                                  17.2.8
  Device OpenCL C Version                         OpenCL C 1.1
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Max compute units                               8
  Max clock frequency                             1183MHz
  Max work item dimensions                        3
  Max work item sizes                             256x256x256
  Max work group size                             256
  Preferred work group size multiple              64
  Preferred / native vector sizes
    char                                                16 / 16
    short                                                8 / 8
    int                                                  4 / 4
    long                                                 2 / 2
    half                                                 0 / 0        (n/a)
    float                                                4 / 4
    double                                               2 / 2        (cl_khr_fp64)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (cl_khr_fp64)
    Denormals                                     Yes
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 Yes
    Round to infinity                             Yes
    IEEE754-2008 fused multiply-add               Yes
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Address bits                                    64, Little-Endian
  Global memory size                              15429913804 (14.37GiB)
  Error Correction support                        No
  Max memory allocation                           3857478451 (3.593GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max constant buffer size                        2147483647 (2GiB)
  Max number of constant args                     16
  Max size of kernel argument                     1024
  Queue properties
    Out-of-order execution                        No
    Profiling                                     Yes
  Profiling timer resolution                      0ns
  Execution capabilities
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  Device Available                                Yes
  Compiler Available                              Yes
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_fp64

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  Clover
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [MESA]
  clCreateContext(NULL, ...) [default]            Success [MESA]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 Clover
    Device Name                                   Radeon 550 Series (AMD POLARIS12 / DRM 3.25.0 / 4.13.0-45-generic, LLVM 5.0.0)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 Clover
    Device Name                                   Radeon 550 Series (AMD POLARIS12 / DRM 3.25.0 / 4.13.0-45-generic, LLVM 5.0.0)

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.8
  ICD loader Profile                              OpenCL 1.2
	NOTE:	your OpenCL library declares to support OpenCL 1.2,
		but it seems to support up to OpenCL 2.1 too.
```

I had do `apt install mesa-opencl-icd` to get this to work. I have the drivers from `amdgpu-pro-18.20-606296` installed. 

I tried installing a newer OpenCL ICD loader (`sudo gdebi opencl-amdgpu-pro-icd_18.20-606296_amd64.deb`) installed but this stopped `clinfo` and `ethminer` from recognizing the graphics card.

I also tried installing newer OpenCL libraries from the AMD drivers (`libopencl1-amdgpu-pro_18.20-606296_amd64.deb` and `opencl-amdgpu-pro_18.20-606296_amd64.deb`) but this had no effect.

Here are all the packages that are available from the AMD driver tarball:
```
test@test:~/projects/graphics_mining/amdgpu-pro-18.20-606296$ ls
amdgpu_18.20-606296_amd64.deb                        libgles2-amdgpu-mesa_18.0.0-606296_amd64.deb
amdgpu_18.20-606296_i386.deb                         libgles2-amdgpu-mesa_18.0.0-606296_i386.deb
amdgpu-core_18.20-606296_all.deb                     libgles2-amdgpu-mesa-dev_18.0.0-606296_amd64.deb
amdgpu-dkms_18.20-606296_all.deb                     libgles2-amdgpu-mesa-dev_18.0.0-606296_i386.deb
amdgpu-install                                       libgles2-amdgpu-pro_18.20-606296_amd64.deb
amdgpu-lib32_18.20-606296_amd64.deb                  libgles2-amdgpu-pro_18.20-606296_i386.deb
amdgpu-pro_18.20-606296_amd64.deb                    libllvm6.0-amdgpu_6.0-606296_amd64.deb
amdgpu-pro_18.20-606296_i386.deb                     libllvm6.0-amdgpu_6.0-606296_i386.deb
amdgpu-pro-core_18.20-606296_all.deb                 libopencl1-amdgpu-pro_18.20-606296_amd64.deb
amdgpu-pro-install                                   libopencl1-amdgpu-pro_18.20-606296_i386.deb
amdgpu-pro-lib32_18.20-606296_amd64.deb              libosmesa6-amdgpu_18.0.0-606296_amd64.deb
clinfo-amdgpu-pro_18.20-606296_amd64.deb             libosmesa6-amdgpu_18.0.0-606296_i386.deb
clinfo-amdgpu-pro_18.20-606296_i386.deb              libosmesa6-amdgpu-dev_18.0.0-606296_amd64.deb
glamor-amdgpu_1.19.0-606296_amd64.deb                libosmesa6-amdgpu-dev_18.0.0-606296_i386.deb
glamor-amdgpu_1.19.0-606296_i386.deb                 libwayland-amdgpu-client0_1.14.0-606296_amd64.deb
glamor-amdgpu-dev_1.19.0-606296_amd64.deb            libwayland-amdgpu-client0_1.14.0-606296_i386.deb
glamor-amdgpu-dev_1.19.0-606296_i386.deb             libwayland-amdgpu-cursor0_1.14.0-606296_amd64.deb
gst-omx-amdgpu_1.0.0.1-606296_amd64.deb              libwayland-amdgpu-cursor0_1.14.0-606296_i386.deb
gst-omx-amdgpu_1.0.0.1-606296_i386.deb               libwayland-amdgpu-dev_1.14.0-606296_amd64.deb
ids-amdgpu_1.0.0-606296_all.deb                      libwayland-amdgpu-dev_1.14.0-606296_i386.deb
libdrm2-amdgpu_2.4.91-606296_amd64.deb               libwayland-amdgpu-doc_1.14.0-606296_all.deb
libdrm2-amdgpu_2.4.91-606296_i386.deb                libwayland-amdgpu-egl1-mesa_18.0.0-606296_amd64.deb
libdrm-amdgpu-amdgpu1_2.4.91-606296_amd64.deb        libwayland-amdgpu-egl1-mesa_18.0.0-606296_i386.deb
libdrm-amdgpu-amdgpu1_2.4.91-606296_i386.deb         libwayland-amdgpu-server0_1.14.0-606296_amd64.deb
libdrm-amdgpu-dev_2.4.91-606296_amd64.deb            libwayland-amdgpu-server0_1.14.0-606296_i386.deb
libdrm-amdgpu-dev_2.4.91-606296_i386.deb             libxatracker2-amdgpu_18.0.0-606296_amd64.deb
libdrm-amdgpu-radeon1_2.4.91-606296_amd64.deb        libxatracker2-amdgpu_18.0.0-606296_i386.deb
libdrm-amdgpu-radeon1_2.4.91-606296_i386.deb         libxatracker-amdgpu-dev_18.0.0-606296_amd64.deb
libdrm-amdgpu-utils_2.4.91-606296_amd64.deb          libxatracker-amdgpu-dev_18.0.0-606296_i386.deb
libdrm-amdgpu-utils_2.4.91-606296_i386.deb           llvm-amdgpu-6.0_6.0-606296_amd64.deb
libegl1-amdgpu-mesa_18.0.0-606296_amd64.deb          llvm-amdgpu-6.0_6.0-606296_i386.deb
libegl1-amdgpu-mesa_18.0.0-606296_i386.deb           llvm-amdgpu_6.0-606296_amd64.deb
libegl1-amdgpu-mesa-dev_18.0.0-606296_amd64.deb      llvm-amdgpu_6.0-606296_i386.deb
libegl1-amdgpu-mesa-dev_18.0.0-606296_i386.deb       llvm-amdgpu-6.0-dev_6.0-606296_amd64.deb
libegl1-amdgpu-mesa-drivers_18.0.0-606296_amd64.deb  llvm-amdgpu-6.0-dev_6.0-606296_i386.deb
libegl1-amdgpu-mesa-drivers_18.0.0-606296_i386.deb   llvm-amdgpu-6.0-doc_6.0-606296_all.deb
libegl1-amdgpu-pro_18.20-606296_amd64.deb            llvm-amdgpu-6.0-runtime_6.0-606296_amd64.deb
libegl1-amdgpu-pro_18.20-606296_i386.deb             llvm-amdgpu-6.0-runtime_6.0-606296_i386.deb
libgbm1-amdgpu_18.0.0-606296_amd64.deb               llvm-amdgpu-dev_6.0-606296_amd64.deb
libgbm1-amdgpu_18.0.0-606296_i386.deb                llvm-amdgpu-dev_6.0-606296_i386.deb
libgbm1-amdgpu-pro_18.20-606296_amd64.deb            llvm-amdgpu-runtime_6.0-606296_amd64.deb
libgbm1-amdgpu-pro_18.20-606296_i386.deb             llvm-amdgpu-runtime_6.0-606296_i386.deb
libgbm1-amdgpu-pro-base_18.20-606296_all.deb         mesa-amdgpu-common-dev_18.0.0-606296_amd64.deb
libgbm1-amdgpu-pro-dev_18.20-606296_amd64.deb        mesa-amdgpu-common-dev_18.0.0-606296_i386.deb
libgbm1-amdgpu-pro-dev_18.20-606296_i386.deb         mesa-amdgpu-omx-drivers_18.0.0-606296_amd64.deb
libgbm-amdgpu-dev_18.0.0-606296_amd64.deb            mesa-amdgpu-omx-drivers_18.0.0-606296_i386.deb
libgbm-amdgpu-dev_18.0.0-606296_i386.deb             mesa-amdgpu-va-drivers_18.0.0-606296_amd64.deb
libgl1-amdgpu-mesa-dev_18.0.0-606296_amd64.deb       mesa-amdgpu-va-drivers_18.0.0-606296_i386.deb
libgl1-amdgpu-mesa-dev_18.0.0-606296_i386.deb        mesa-amdgpu-vdpau-drivers_18.0.0-606296_amd64.deb
libgl1-amdgpu-mesa-dri_18.0.0-606296_amd64.deb       mesa-amdgpu-vdpau-drivers_18.0.0-606296_i386.deb
libgl1-amdgpu-mesa-dri_18.0.0-606296_i386.deb        opencl-amdgpu-pro_18.20-606296_amd64.deb
libgl1-amdgpu-mesa-glx_18.0.0-606296_amd64.deb       opencl-amdgpu-pro-dev_18.20-606296_amd64.deb
libgl1-amdgpu-mesa-glx_18.0.0-606296_i386.deb        opencl-amdgpu-pro-icd_18.20-606296_amd64.deb
libgl1-amdgpu-pro-appprofiles_18.20-606296_all.deb   opencl-orca-amdgpu-pro-icd_18.20-606296_amd64.deb
libgl1-amdgpu-pro-dri_18.20-606296_amd64.deb         opencl-orca-amdgpu-pro-icd_18.20-606296_i386.deb
libgl1-amdgpu-pro-dri_18.20-606296_i386.deb          Packages
libgl1-amdgpu-pro-ext_18.20-606296_amd64.deb         Release
libgl1-amdgpu-pro-ext_18.20-606296_i386.deb          roct-amdgpu-pro_1.0.8-606296_amd64.deb
libgl1-amdgpu-pro-glx_18.20-606296_amd64.deb         roct-amdgpu-pro-dev_1.0.8-606296_amd64.deb
libgl1-amdgpu-pro-glx_18.20-606296_i386.deb          vulkan-amdgpu_18.20-606296_amd64.deb
libglapi-amdgpu-mesa_18.0.0-606296_amd64.deb         vulkan-amdgpu_18.20-606296_i386.deb
libglapi-amdgpu-mesa_18.0.0-606296_i386.deb          vulkan-amdgpu-pro_18.20-606296_amd64.deb
libgles1-amdgpu-mesa_18.0.0-606296_amd64.deb         vulkan-amdgpu-pro_18.20-606296_i386.deb
libgles1-amdgpu-mesa_18.0.0-606296_i386.deb          wayland-protocols-amdgpu_1.13-606296_all.deb
libgles1-amdgpu-mesa-dev_18.0.0-606296_amd64.deb     xserver-xorg-amdgpu-video-amdgpu_1.4.0-606296_amd64.deb
libgles1-amdgpu-mesa-dev_18.0.0-606296_i386.deb      xserver-xorg-amdgpu-video-amdgpu_1.4.0-606296_i386.deb
```

How do I either correctly install newer OpenCL libraries on Ubuntu or make `OpenCL 1.1` work with `ethminer`?

**Comment by aashidham** [comment] 2018-06-23 06:56
@jean-m-cyr @AndreaLanfranchi any insights about this?

**Comment by aashidham** [comment] 2018-06-24 04:43
^ ping on this?

**Comment by jean-m-cyr** [comment] 2018-06-24 14:12
I'm not ignoring this issue. I am just not able to reproduce it on my single 480 GPU. I generally focus on Nvidia stuff.

@ddobreff Do you see any problem with this configuration?

**Comment by ddobreff** [comment] 2018-06-24 17:28
Install opencl dependencies from 18.10 amdgpu-pro package. AMD added support for Vega and Lexa since this package.

**Comment by jean-m-cyr** [comment] 2018-06-24 20:13
I don't think there's a apt package for that version. I think you have to download and follow instructions here:
https://support.amd.com/en-us/kb-articles/Pages/AMDGPU-PRO-Install.aspx

**Comment by ddobreff** [comment] 2018-06-24 21:40
All packages have dependencies, just track dependencies of libopencl/opencl/amdgpu-core, you can use dpkg-deb -R to unpack amdgpu-core and remove amdgpu-pro-dkms package requirement.

**Comment by ddobreff** [comment] 2018-06-26 23:53
Do you still have the issue?

**Comment by aashidham** [comment] 2018-06-27 01:22
Yes. I don't get which of the packages to install. I have trouble
understanding your prior comment.

**Comment by ddobreff** [comment] 2018-06-27 16:04
Just install the hybrid driver amdgpu-pro-18.20 and it should work.

**Comment by aashidham** [comment] 2018-06-27 19:44
Like I mentioned in the original post, those drivers are the first thing I
installed.

**Comment by aashidham** [comment] 2018-07-02 23:28
This is what I get:

```
test@test:~$ ethminer -G --list-devices

Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] Radeon 550 Series (AMD POLARIS12 / DRM 3.25.0 / 4.13.0-45-generic, LLVM 5.0.0)
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 15430149732
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 3857537433
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] [0] gfx804
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 3967397888
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 3725058048
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
```

**Comment by AndreaLanfranchi** [comment] 2018-07-03 05:06
Would you please try to relaunch with this parameters ?

```
ethminer -G --opencl-platform 0 --cl-global-work -1 
--pool stratum+tcp://0xdeadbeef@us1.ethpool.org:3333
```

Then report back

**Comment by chfast** [comment] 2018-07-03 08:58
@aashidham your OpenCL driver is not able to compile the OpenCL kernel. The Clover OpenCL implementations you are using is production ready and does not give good performance. You should install amdgpu-pro driver.

**Comment by aashidham** [comment] 2018-07-03 17:51
Apologies for my ignorance, but how do I remove Mesa / clover and do a clean install on Ubuntu 16.04? What specific packages should I delete?

**Comment by yotys** [comment] 2018-09-01 22:16
Same problem here, but on Windows.

 m 23:57:52 main     ethminer 0.15.0
 m 23:57:52 main     Build: windows/release
 i 23:57:52 main     Found suitable OpenCL device [Intel(R) HD Graphics 520] with 3380779418 bytes of GPU memory
 i 23:57:52 main     Selected pool europe.ethash-hub.miningpoolhub.com:20535
 i 23:57:52 stratum  Trying 35.156.160.57:20535 ...
 i 23:57:52 stratum  Connected to europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
 i 23:57:52 stratum  Spinning up miners...
cl 23:57:52 cl-0     No work. Pause for 3 s.
 i 23:57:52 stratum  Subscribed to stratum server
 i 23:57:52 stratum  Extranonce set to 2bb0 (nicehash)
 i 23:57:52 stratum  Difficulty set to 1.00117 (nicehash)
 i 23:57:52 stratum  Job: #6b01e0ee... europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
 i 23:57:52 stratum  Pool difficulty: 4.30K megahash
 i 23:57:52 stratum  New epoch 208
 i 23:57:52 stratum  Authorized worker test.test
 i 23:57:52 stratum  Job: #bd148c98... europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
cl 23:57:55 cl-0     Platform: Intel(R) OpenCL
cl 23:57:55 cl-0     Device:   Intel(R) HD Graphics 520 / OpenCL 2.0
 m 23:57:57 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cl 23:57:57 cl-0     OpenCL kernel: Stable kernel
cl 23:57:58 cl-0     Build info: fcl build 1 succeeded.
bcl build succeeded.

cl 23:57:58 cl-0     Creating light cache buffer, size: 44039104
cl 23:57:58 cl-0     Creating DAG buffer, size: 2818571648
 X 23:57:58 cl-0     Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)
 X 23:57:59 cl-0     OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_MEM_OBJECT (-38)
 i 23:57:59 stratum  Job: #6ef718f8... europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
 m 23:58:02 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 23:58:06 stratum  Job: #45f71106... europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
 m 23:58:07 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 23:58:09 stratum  Job: #19241eff... europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
 m 23:58:12 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 23:58:15 stratum  Job: #e23fe665... europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
 m 23:58:17 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00

**Comment by lesjokolat** [comment] 2018-09-01 23:46
is it possible this gpu is not large enough in terms of ram size for dag file?

**Comment by AndreaLanfranchi** [comment] 2018-09-19 15:50
No feed back.
Closing

**Closed by AndreaLanfranchi** 2018-09-19 15:50 UTC
Labels: question
