### ISSUE TITLE
ethminer 0.18 fails with Parity but 0.12 succeeds

### ISSUE THREAD

**Issue by stone212** [ethereum-mining/ethminer#1911] opened 2019-06-26 08:55 UTC
**Describe the bug**
Using ethminer 0.18 to mine on a local Parity node fails

**To Reproduce**
1. Start a local Parity node wtih stratum enabled
2. Start ethminer 0.18 with:
`/opt/ethminer/bin/ethminer -G -P stratum+tcp://127.0.0.1:8008`
(See https://github.com/ethereum-mining/ethminer/issues/1895)

3. See 0.00h:

```
i 01:46:31 ethminer Configured pool 127.0.0.1:8008
 i 01:46:31 ethminer Selected pool 127.0.0.1:8008
 i 01:46:31 ethminer Established connection to 127.0.0.1:8008
 i 01:46:31 ethminer Spinning up miners...
 i 01:46:31 ethminer Stratum mode : STRATUM
 i 01:46:31 ethminer Subscribed!
cl 01:46:31 cl-0     Using PciId : 01:00.0 Ellesmere OpenCL 1.2 AMD-APP (2671.3) Memory : 7.05 GB
 i 01:46:31 ethminer Authorized worker
cl 01:46:31 cl-1     Using PciId : 03:00.0 Ellesmere OpenCL 1.2 AMD-APP (2671.3) Memory : 7.96 GB
 m 01:46:36 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:46:41 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:46:46 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:46:51 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:46:56 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:01 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:06 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:11 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:16 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:21 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:26 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:31 ethminer 0:01 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:36 ethminer 0:01 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:41 ethminer 0:01 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:46 ethminer 0:01 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:51 ethminer 0:01 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:47:56 ethminer 0:01 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:48:01 ethminer 0:01 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:48:06 ethminer 0:01 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 01:48:11 ethminer 0:01 A0 0.00 h { cl0 0.00 | cl1 0.00 }

```

This continues even after 20 minutes.

**Expected behavior**
I expect ethminer to generate the DAG and start mining.  Please see example of ethminer 0.12 below

**Environment (please complete the following information):**
- Operating System: `Ubuntu 18.04`
- Hardware 
```
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] (rev e7)
03:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] (rev e7)
```
- Ethminer Version `0.18`
- Ethminer options used `/opt/ethminer/bin/ethminer -G -P stratum+tcp://127.0.0.1:8008`

**Additional context**
ethminer 0.12 succeeds with no changes to Parity.  Interesting that one time I accidentally used incorrect port for ethminer 0.12 and it worked.  Tested and any port seems to work, ex 127.0.0.1:8003.  Maybe that is useful maybe not.

```
/opt/ethminer-0.12/bin/ethminer -G -SP 127.0.0.1:8008
  ℹ  01:51:44|ethminer  Found suitable OpenCL device [ Ellesmere ] with 7568220160  bytes of GPU memory
 cl  01:51:44|cl-0      No work. Pause for 3 s.
 cl  01:51:44|cl-1      No work. Pause for 3 s.
  m  01:51:44|ethminer  Waiting for work package...
  m  01:51:44|ethminer  Got work package: #2b3fc68c
  m  01:51:44|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:45|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:45|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:46|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:46|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:47|cl-0      New work: header #2b3fc68c… target 0000000725f3d795607b91864c60504925cc1532dc108e02bf720f1528fd5a61
 cl  01:51:47|cl-1      New work: header #2b3fc68c… target 0000000725f3d795607b91864c60504925cc1532dc108e02bf720f1528fd5a61
 cl  01:51:47|cl-0      New seed #013d5197…
 cl  01:51:47|cl-1      New seed #013d5197…
  m  01:51:47|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:47|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:48|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:48|cl-0      Platform: AMD Accelerated Parallel Processing
 cl  01:51:48|cl-1      Platform: AMD Accelerated Parallel Processing
 cl  01:51:48|cl-0      Device:   Ellesmere  / OpenCL 1.2 AMD-APP (2671.3)
 cl  01:51:48|cl-1      Device:   Ellesmere  / OpenCL 1.2 AMD-APP (2671.3)
  m  01:51:48|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:49|cl-1      Build info: 
 cl  01:51:49|cl-1      Creating light cache buffer, size 22675264
 cl  01:51:49|cl-1      Creating DAG buffer, size 1451229056
 cl  01:51:49|cl-1      Loading kernels
 cl  01:51:49|cl-1      Writing light cache buffer
 cl  01:51:49|cl-1      Creating buffer for header.
 cl  01:51:49|cl-1      Creating mining buffer
 cl  01:51:49|cl-1      Generating DAG
  m  01:51:49|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:49|cl-1      DAG 0 %
 cl  01:51:49|cl-0      Build info: 
 cl  01:51:49|cl-0      Creating light cache buffer, size 22675264
 cl  01:51:49|cl-0      Creating DAG buffer, size 1451229056
 cl  01:51:49|cl-0      Loading kernels
 cl  01:51:49|cl-0      Writing light cache buffer
 cl  01:51:49|cl-0      Creating buffer for header.
 cl  01:51:49|cl-0      Creating mining buffer
 cl  01:51:49|cl-0      Generating DAG
 cl  01:51:49|cl-1      DAG 4 %
  m  01:51:49|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:49|cl-0      DAG 0 %
 cl  01:51:49|cl-1      DAG 9 %
 cl  01:51:49|cl-0      DAG 4 %
 cl  01:51:49|cl-1      DAG 13 %
 cl  01:51:50|cl-0      DAG 9 %
 cl  01:51:50|cl-1      DAG 18 %
  m  01:51:50|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:50|cl-0      DAG 13 %
 cl  01:51:50|cl-1      DAG 22 %
 cl  01:51:50|cl-0      DAG 18 %
 cl  01:51:50|cl-1      DAG 27 %
 cl  01:51:50|cl-0      DAG 22 %
 cl  01:51:50|cl-1      DAG 31 %
  m  01:51:50|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:50|cl-0      DAG 27 %
 cl  01:51:50|cl-1      DAG 36 %
 cl  01:51:50|cl-0      DAG 31 %
 cl  01:51:50|cl-1      DAG 40 %
 cl  01:51:51|cl-0      DAG 36 %
 cl  01:51:51|cl-1      DAG 45 %
  m  01:51:51|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:51|cl-0      DAG 40 %
 cl  01:51:51|cl-1      DAG 50 %
 cl  01:51:51|cl-0      DAG 45 %
 cl  01:51:51|cl-1      DAG 54 %
 cl  01:51:51|cl-0      DAG 50 %
 cl  01:51:51|cl-1      DAG 59 %
  m  01:51:51|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:51|cl-0      DAG 54 %
 cl  01:51:51|cl-1      DAG 63 %
 cl  01:51:51|cl-0      DAG 59 %
 cl  01:51:51|cl-1      DAG 68 %
 cl  01:51:52|cl-0      DAG 63 %
 cl  01:51:52|cl-1      DAG 72 %
  m  01:51:52|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:52|cl-0      DAG 68 %
 cl  01:51:52|cl-1      DAG 77 %
 cl  01:51:52|cl-0      DAG 72 %
 cl  01:51:52|cl-1      DAG 81 %
 cl  01:51:52|cl-1      DAG 86 %
 cl  01:51:52|cl-0      DAG 77 %
  m  01:51:52|ethminer  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  01:51:52|cl-1      DAG 90 %
 cl  01:51:52|cl-0      DAG 81 %
 cl  01:51:52|cl-1      DAG 95 %
 cl  01:51:52|cl-1      Switch time 8637 ms / 5638249 us
 cl  01:51:52|cl-0      DAG 86 %
 cl  01:51:53|cl-0      DAG 90 %
 cl  01:51:53|cl-0      DAG 95 %
 cl  01:51:53|cl-0      Switch time 8974 ms / 5975666 us
  m  01:51:53|ethminer  Speed   9.45 Mh/s    gpu/0  1.05  gpu/1  8.40  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:53|ethminer  Speed   9.45 Mh/s    gpu/0  1.05  gpu/1  8.40  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:54|ethminer  Speed  26.77 Mh/s    gpu/0 11.55  gpu/1 15.22  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:54|ethminer  Speed  26.77 Mh/s    gpu/0 11.55  gpu/1 15.22  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:55|ethminer  Speed  32.54 Mh/s    gpu/0 15.04  gpu/1 17.49  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:55|ethminer  Speed  32.54 Mh/s    gpu/0 15.04  gpu/1 17.49  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:56|ethminer  Speed  35.15 Mh/s    gpu/0 16.53  gpu/1 18.63  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:56|ethminer  Speed  35.15 Mh/s    gpu/0 16.53  gpu/1 18.63  [A0+0:R0+0:F0] Time: 00:00
  m  01:51:57|ethminer  Speed  36.94 Mh/s    gpu/0 17.63  gpu/1 19.31  [A0+0:R0+0:F0] Time: 00:00
```

**Comment by smurfy** [comment] 2019-06-26 09:00
Could you try different stratum variants instead using auto-detect?:

``/opt/ethminer/bin/ethminer -G -P stratum1+tcp://127.0.0.1:8008``
``/opt/ethminer/bin/ethminer -G -P stratum2+tcp://127.0.0.1:8008``
``/opt/ethminer/bin/ethminer -G -P stratum3+tcp://127.0.0.1:8008``

**Comment by stone212** [comment] 2019-06-26 09:10
@smurfy

```
/opt/ethminer/bin/ethminer -G -P stratum1+tcp://127.0.0.1:8008


ethminer 0.18.0-alpha.3
Build: linux/release/gnu

 i 02:07:22 ethminer Configured pool 127.0.0.1:8008
 i 02:07:22 ethminer Selected pool 127.0.0.1:8008
 i 02:07:22 ethminer Could not login: code:-32601 message:Method not found 
 i 02:07:22 ethminer Disconnected from 127.0.0.1:8008
 i 02:07:22 ethminer No connection. Suspend mining ...
 i 02:07:22 ethminer No more connections to try. Exiting...
 i 02:07:22 main     Got interrupt ...
 i 02:07:22 ethminer Terminated!
```

```
/opt/ethminer/bin/ethminer -G -P stratum2+tcp://127.0.0.1:8008


ethminer 0.18.0-alpha.3
Build: linux/release/gnu

 i 02:07:31 ethminer Configured pool 127.0.0.1:8008
 i 02:07:31 ethminer Selected pool 127.0.0.1:8008
 i 02:07:31 ethminer Established connection to 127.0.0.1:8008
 i 02:07:31 ethminer Spinning up miners...
cl 02:07:31 cl-0     Using PciId : 01:00.0 Ellesmere OpenCL 1.2 AMD-APP (2671.3) Memory : 7.69 GB
cl 02:07:31 cl-1     Using PciId : 03:00.0 Ellesmere OpenCL 1.2 AMD-APP (2671.3) Memory : 7.96 GB
 i 02:07:31 ethminer Stratum mode : ETHEREUMSTRATUM (NiceHash)
 i 02:07:31 ethminer Subscribed to stratum server
 i 02:07:31 ethminer Extranonce set to 0x53cc9af1dbcd5270d7d20df93a6002de835f9ef88b576af062564e671d7ec932 (nicehash)
 i 02:07:31 ethminer Authorized worker 
 m 02:07:36 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 02:07:41 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 02:07:46 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 02:07:51 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 02:07:56 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 02:08:01 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 02:08:06 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 02:08:11 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
```

```
/opt/ethminer/bin/ethminer -G -P stratum3+tcp://127.0.0.1:8008


ethminer 0.18.0-alpha.3
Build: linux/release/gnu

Error: Bad URI : Invalid scheme
```

I will let 2 run a little longer and reply if it begins to hash.

**Comment by stone212** [comment] 2019-06-26 09:14
@smurfy Still no change.  Reverting to 0.12 (this is a production server).

**Comment by AndreaLanfranchi** [comment] 2019-06-26 09:20
Is it a parity node in sync with eth main net or is it a custom/private chain ?
If the latter which is the epoch height ?

**Comment by stone212** [comment] 2019-06-26 09:23
@AndreaLanfranchi 

It is a private chain, in sync with that chain.

By "epoch height" do you mean "block height"? That is 1351060

I think Parity does not support getWork so I can not test that.

But please see that ethminer 0.12 does work with stratum.  You probably saw that already, I just want to be certain.

**Comment by AndreaLanfranchi** [comment] 2019-06-26 09:27
Parity DOES support getWork as primary connection method.

>> Parity supports standard Ethereum JSON-RPC interface for mining (eth_getWork, eth_submitWork methods) and thus compatible with any miner which implements Ethereum Proof-of-Work.

In addition to that Parity clearly states that stratum support is in **beta** and (quote from their site)
"Parity currently implements stratum without any authentication, **nor does it match the proxy modes used by mining pools** and certain mining software. Attempting to use these features with Parity will result in it rejecting your connections."

ethminer is all about compatibilty with mining pools.

**Comment by AndreaLanfranchi** [comment] 2019-06-26 09:29
Use

`ethminer -G -P http://127.0.0.1:8545`

**Comment by stone212** [comment] 2019-06-26 09:34
@AndreaLanfranchi Ah!  I see what you mean.  I was thinking of "support" getwork using http which Parity does not do but you are suggesting I use it over RPC.   Okay good idea.  I will enable RPC and test.

Yes, the stratum is in beta but again *it works great with ethminer 0.12* so the problem is some change made with ethminer between 0.12 and 0.18.  It's not like beta means it does not work.  ethminer is in pre-beta not even a whole 1.0 release yet and it (0.12 at least) works very well by many many people.

**Comment by stone212** [comment] 2019-06-26 09:35
@AndreaLanfranchi Okay no that does not work.  

```
/opt/ethminer/bin/ethminer -G -P http://127.0.0.1:8545


ethminer 0.18.0-alpha.3
Build: linux/release/gnu

 i 02:34:44 ethminer Configured pool 127.0.0.1:8545
 i 02:34:44 ethminer Selected pool 127.0.0.1:8545
 X 02:34:44 ethminer Error connecting to 127.0.0.1:8545 : Connection refused
 X 02:34:44 ethminer No more IP addresses to try for host: 127.0.0.1
 i 02:34:44 ethminer Disconnected from 127.0.0.1:8545
 i 02:34:44 ethminer No connection. Suspend mining ...
 i 02:34:44 ethminer Selected pool 127.0.0.1:8545
 X 02:34:44 ethminer Error connecting to 127.0.0.1:8545 : Connection refused
 X 02:34:44 ethminer No more IP addresses to try for host: 127.0.0.1
 i 02:34:44 ethminer Disconnected from 127.0.0.1:8545
 i 02:34:44 ethminer No connection. Suspend mining ...
 i 02:34:44 ethminer Selected pool 127.0.0.1:8545
 X 02:34:44 ethminer Error connecting to 127.0.0.1:8545 : Connection refused
 X 02:34:44 ethminer No more IP addresses to try for host: 127.0.0.1
 i 02:34:44 ethminer Disconnected from 127.0.0.1:8545
 i 02:34:44 ethminer No connection. Suspend mining ...
 i 02:34:44 ethminer No more connections to try. Exiting...
 i 02:34:44 main     Got interrupt ...
 i 02:34:44 ethminer Terminated!
```

RPC is enabled on the Parity node:

```
netstat -tulpn | grep '8545'
tcp        0      0 127.0.0.1:8545          0.0.0.0:*               LISTEN      3392/parity        
```

**Comment by AndreaLanfranchi** [comment] 2019-06-26 09:36
Firewall ?

**Comment by AndreaLanfranchi** [comment] 2019-06-26 09:38
> Yes, the stratum is in beta but again it works great with ethminer 0.12 

This does not mean anything. 
A lot of refactoring over stratum glue has been carried out during last year and a half to get ethminer compliant with major pools: adding more strict checks over stratum flavors may have broken compatibility with **BETA** parity's stratum support.

**Comment by stone212** [comment] 2019-06-26 09:40
@AndreaLanfranchi No not a firewall.  I can run a curl command as the same user I run ethminer as:

```
# curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":67}' 127.0.0.1:8545
{"jsonrpc":"2.0","result":"Parity-Ethereum//v2.3.9-stable-0b42826-20190401/x86_64-linux-gnu/rustc1.33.0","id":67}
```

Also if we point ethminer to port 8545 it has to be using the JSON RPC commands, right?  The eth_getwork function in Parity is RPC, not a typical HTTP service (https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getwork)

So unless ethminer is smart and can switch to RPC I think getWork and ethminer and Parity are not made to work together.  getWork I think is only for API's and other RPC services?

**Comment by stone212** [comment] 2019-06-26 09:42
@AndreaLanfranchi 

> more strict checks over stratum flavors may have broken compatibility 

Yes this is exactly what I think probably happened.  This means that ethminer 0.18 has the potential to do this but is being blocked.  It is like if you have to take off your seatbelt to reach your cheeseburger.  It's not always a good idea but you don't want to be dis-allowed from doing it when you upgrade to a new car.

Maybe an ethminer flag like -I-Feel-Lucky to disable the checks?

**Comment by AndreaLanfranchi** [comment] 2019-06-26 09:43
You're mixing JSON-RPC protocol (which is a payload definition) with transport (TCP or HTTP).
JSON-RPC is only a syntax definition of json formatted strings. Eventually they can be transmitted via HTTP POST or direct TCP connections.

**Comment by AndreaLanfranchi** [comment] 2019-06-26 09:44
> Maybe an ethminer flag like -I-Feel-Lucky to disable the checks?

Maybe ... if someone wants to self assign the task.

**Comment by stone212** [comment] 2019-06-26 09:44
@AndreaLanfranchi 

> JSON-RPC is only a syntax definition of json formatted strings. 

Yes exactly.  I guess I am wondering if ethminer knows to format the strings in this way when pointed to an RPC port?  If not then there is no way to test ethminer and Parity with getWork.

**Comment by stone212** [comment] 2019-06-26 09:46
@AndreaLanfranchi 

I think we have two likely possibilities:

1. There is some bug in ethminer that we have not found a way to test (unless ethminer can talk RPC formatting for getWork?)

2. There is some bug in Parity stratum protocol which ethminer 0.12 did not check against, but ethminer 0.18 does.

Did you develop this code?  If you can highlight it, maybe I can re-compile without the checks.

**Comment by AndreaLanfranchi** [comment] 2019-06-26 09:49
It already does it.
JSON messages are formatted correctly. We hadn't any issue with both parity and geth (two major ethereum nodes) on HTTP as well as no issues on pools.

The message "Connection refused" is a message from TCP stack ... way before the data gets transmitted. So I'd investigate more on that.

>Did you develop this code? If you can highlight it, maybe I can re-compile without the checks.

I've been developing this code for more than a year.
No longer on the matter though.

You can lurk at https://github.com/ethereum-mining/ethminer/tree/master/libpoolprotocols
All communication functions are in there.

**Comment by stone212** [comment] 2019-06-26 09:52
@AndreaLanfranchi 

> We hadn't any issue with both parity and geth 

Was that using port 8545?  Or an HTTP service on port 8000 for example?

**Comment by Spudz76** [comment] 2019-06-26 17:27
JSON-RPC 2.0 operates over HTTP

RPC is not a "port";  HTTP is the "port" and transport, for the JSON-RPC formatted messages.

JSON-RPC is the language, HTTP is the communications protocol.  While you could send JSON-RPC over SMS, or old pager network, or emails, or smoke signals, most everything uses HTTP to transport it since it is the simplest request-reponse protocol.  There exists no "RPC port" and there is no "RPC protocol".  It is and has always been HTTP, but not HTML-over-HTTP which is what web browsers use (and GET requests are not supported, it all works via POST requests).  So you might say it's a subset of HTTP however it's still HTTP.

So I think you mean, Parity does not talk to web browsers... But it must support HTTP but can be only POST method, as that is what all JSON-RPC for mining (getwork) is.  It should return method not allowed for GET, PUT, HEAD, and I think all other HTTP request types, which is not "doesn't support HTTP" but actually "supports only the subset of HTTP required for JSON-RPC transport, and not web browsers and HTML".

It seems you assume HTTP (transport) always means HTML (payload) and web browsers, where it does not.  Many other services operate over HTTP other than web browsing.

Any "JSON RPC 2.0" port is also an http port, to which you send only POST messages with the properly formatted JSON message as the payload.  Then it should respond with properly formatted JSON to continue the conversation.  HTTP response codes and headers are unused.

**Comment by Spudz76** [comment] 2019-06-26 17:30
See also: https://wiki.parity.io/JSONRPC

**Comment by AndreaLanfranchi** [comment] 2019-06-26 18:48
Hope not to add confusion but :

- TCP is the transport protocol which, merged with UDP, makes almost 99.9% of all traffic worldwide; It transports anything representable in the form of bytes. So basically anything in the digital world.
- TCP makes possible the comunication to an "endpoint" addressing data to its ip address plus a "port";
- A port does not define anything of the **application protocol** required to successfully comunicate. It only defines "the intercom button" of a specific address.
- On a "port" listens an application/service which **implements** one of the many possible **application-protocols** like HTTP, SMTP, IMAP, POP, SSH etc.

Worldwide agreements bind well known ports to specific application protocols. For example is generally accepted to expect HTTP responses on port 80 or email exchanges on port 25. **But nothing prevents from having a web server to listen on port 25 and an SMTP server to listen on port 80** Ports are agnostic of the application layer.

RPC (Remote Procedure Call) is not a protocol. Is the technique for a computer to invoke the execution on a remote computer of a program a routine a process (eventually passing some parameter) and expect back a result. Technically HTTP navigation **is** RPC: my computer queries a remote computer for a content which is produced by a combination of procedures (load data from a database or from static storage).

JSON-RPC is a an attempt to standardize **light-weight** RPC in the form of JSON formatted messages which can be transmitted by any application protocol (HTTP, SMTP, SSH, Telnet ... whatever) on any port.

When it happens that JSON-RPC messages are sent over plain TCP Sockets and the requirement of separating each message by a LF char is met ... then JSON-RPC it also becomes an application-protocol.

**Comment by stone212** [comment] 2019-06-27 05:26
@AndreaLanfranchi Thank you for taking the time to write this although it was not necessary in this case (I've been doing this for as long as you have I think) and we only have a mis-communication that makes you think I did not understand this.  Or more specifically I was not thinking clearly because I forgot that Parity port 8545 does accept http requests (proof in the `curl` example above).

Can you provide a command line example for ethminer 0.12 to work using getWork on a local Parity node?  ethminer 0.18 fails with `ethminer -G -P http://127.0.0.1:8545` where `curl` succeeds.  Now I want to test with ethminer 0.12, which succeeds with stratum on the same node but ethminer 0.18 does not.  I am trying to eliminate possibilities.

`ethminer-0.12 -h` provides some switches but it does not mention getWork, and no command line switch produces:

```
/opt/ethminer-0.12/bin/ethminer -G http://127.0.0.1:8545
Invalid argument: http://127.0.0.1:8545
```
Because `-G` is not mentioned in the `-h` results I try without and get the same:

```
/opt/ethminer-0.12/bin/ethminer  http://127.0.0.1:8545
Invalid argument: http://127.0.0.1:8545
```

Also if I do not use `http`:

```
/opt/ethminer-0.12/bin/ethminer  127.0.0.1:8545
Invalid argument: 127.0.0.1:8545
```

And of course with `-P` we get `Invalid argument: -P` because -P did not exist for 0.12 I think?

The examples page (https://github.com/ethereum-mining/ethminer/blob/master/docs/POOL_EXAMPLES_ETH.md) shows for 0.18, not 0.12.  So if you remember how to start ethminer 0.12 with http/getWork I will test that next.  What this will do is tell me if the problem with 0.18 and Parity with getWork is a problem with Parity accepting getWork.

I have Parity .toml file with these RPC API's:

```
[rpc]
apis = ["web3", "eth", "pubsub", "net", "parity", "private", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub", "personal", "parity_accounts"]
hosts = [""]
cors = [""]
```

And the `[mining]` section has an `author` value (which is why stratum mining works with 0.12)

**Comment by AndreaLanfranchi** [comment] 2019-06-27 09:34
0.12 is so old I can hardly recall to have ever used it.
From ancient (and maybe wrong) memories with release 0.12 `-SP` was the CLI argument for **S**tratum **P**ool while `-F` was meant for **F**arm or, in other words, direct HTTP connection with a local node.

Nevertheless `/opt/ethminer-0.12/bin/ethminer --help` may provide additional information.

What I do know for sure (tested) is that with current 0.18 `-P http://127.0.0.1:8545` works for `geth` node as well as for `parity`. I reiterate it should work **and it should not report "connection refused"**

**Comment by stone212** [comment] 2019-06-29 07:42
@AndreaLanfranchi Yes you are correct.  Good memory!  I must have missed that option because I was not looking for something like "farm".  Okay:

1. I confirm that this Parity works in HTTP mode with 0.12 `/opt/ethminer-0.12/bin/ethminer -G -F 127.0.0.1:8545`  

2. This Parity node works in stratum mode with 0.12 (see above)

Because of 1 & 2 I think we can say it was not correct (but a good guess!) that "it appears to me this whole issue is more related to running params of the node".

3. Failure 0.18 HTTP mode `/opt/ethminer-0.18/bin/ethminer -GP http://127.0.0.1:8545`

```
ethminer 0.18.0-alpha.3
Build: linux/release/gnu

 i 00:32:29 ethminer Configured pool 127.0.0.1:8545
 i 00:32:29 ethminer Selected pool 127.0.0.1:8545
 i 00:32:29 ethminer Established connection to 127.0.0.1:8545
 i 00:32:29 ethminer Spinning up miners...
cl 00:32:29 cl-0     Using PciId : 01:00.0 Ellesmere OpenCL 1.2 AMD-APP (2671.3) Memory : 7.48 GB
cl 00:32:29 cl-1     Using PciId : 03:00.0 Ellesmere OpenCL 1.2 AMD-APP (2671.3) Memory : 7.96 GB
 X 00:32:29 ethminer 127.0.0.1:8545 reported status 403 Forbidden
 i 00:32:29 ethminer Disconnected from 127.0.0.1:8545
 i 00:32:29 ethminer No connection. Suspend mining ...
 i 00:32:29 ethminer Selected pool 127.0.0.1:8545
 i 00:32:29 ethminer Established connection to 127.0.0.1:8545
 i 00:32:29 ethminer Resume mining ...
 X 00:32:29 ethminer 127.0.0.1:8545 reported status 403 Forbidden
 i 00:32:29 ethminer Disconnected from 127.0.0.1:8545
 i 00:32:29 ethminer No connection. Suspend mining ...
 i 00:32:29 ethminer Selected pool 127.0.0.1:8545
 i 00:32:29 ethminer Established connection to 127.0.0.1:8545
 i 00:32:29 ethminer Resume mining ...
 X 00:32:29 ethminer 127.0.0.1:8545 reported status 403 Forbidden
 i 00:32:29 ethminer Disconnected from 127.0.0.1:8545
 i 00:32:29 ethminer No connection. Suspend mining ...
 i 00:32:29 ethminer No more connections to try. Exiting...
 i 00:32:29 ethminer Shutting down miners...
 i 00:32:29 main     Got interrupt ...
 i 00:32:29 ethminer Terminated!
```

Without `-G` I get `CUDA Error : No CUDA driver found` and that is reasonable.

4. Failure  0.18 stratum mode (See above)

Is it possible that 0.18 requires CUDA for local connections?  Just an idea.  I will look into installing CUDA to test this (but then the bug would be that mining does not work without CUDA).

**Comment by AndreaLanfranchi** [comment] 2019-06-29 08:52
CUDA is only needed for NVIDIA cards and is not relevant to work-provider(s) connection(s).

If you omit `-G` (as well as `-U`) miner tries to start in mixed mode (i.e. using mixed AMD and NVIDIA cards) thus trying to instantiate CUDA.

Yet the relevant part of that log is this one:

```
 X 00:32:29 ethminer 127.0.0.1:8545 reported status 403 Forbidden
```
which is the reply of parity node to ethminer request for mining jobs.

**Comment by AndreaLanfranchi** [comment] 2019-06-29 09:05
What is the output of 

```
curl -H 'Connection: close' --http1.0 "Content-Type: application/json" -X POST --data '{"id":1,"jsonrpc":"2.0","method":"eth_getWork","params":[]}' 127.0.0.1:8545/
```
(this exactly reproduces the call issued by ethminer 0.18.x

**Comment by AndreaLanfranchi** [comment] 2020-11-23 18:34
No feed back.
Closing

**Closed by AndreaLanfranchi** 2020-11-23 18:34 UTC

**Comment by mcarilli** [comment] 2021-07-30 06:27
After monkeying with curl and netcat to compare the raw http that gets sent by [openethereum's curl getwork example](https://openethereum.github.io/JSONRPC-eth-module#eth_getwork) (which works) to the raw http sent by ethminer (which doesn't), and inspect the raw http returned by the openethereum client in both cases, I realized the openethereum curl getwork example sends http with Host header line
```
Host: localhost:8545
```
while ethminer (v0.18.0) sends http with Host header line
```
Host: 127.0.0.1
```
The latter yields the response (from the openethereum client)
```
HTTP/1.0 403 Forbidden
content-type: text/plain; charset=utf-8
content-length: 41
date: Fri, 30 Jul 2021 06:20:23 GMT

Provided Host header is not whitelisted.
```


There's a simple fix: add
```
--jsonrpc-hosts=127.0.0.1
```
to your openethereum CLI options, which apparently whitelists the `Host: 127.0.0.1` header field sent by ethminer. When I run openethereum with `--jsonrpc-hosts=127.0.0.1`, `./ethminer --cuda -P getwork://127.0.0.1:8000` connects to openethereum without complaining.

Disclaimer: I do not know the security implications of `--jsonrpc-hosts=127.0.0.1`.
