### ISSUE TITLE
can not reconnect stratum server

### ISSUE THREAD

**Issue by billytk06** [ethereum-mining/ethminer#988] opened 2018-04-09 06:52 UTC
For release 0.14rc3
After any disconnect from internet or  worker timeout, system can not reconnect to startum server

There is no internet issue, just reconnect issue

if we restart  the app, then it works.

**Comment by beinadvance** [comment] 2018-04-09 09:40
I also have

**Comment by whotheff** [comment] 2018-04-09 13:29
+1

**Comment by alptolga** [comment] 2018-04-09 19:01
Ethminer has a serious problem about connection. I use open ethereum pool for solo mining in my lan. Random disconnects... after loosing connection I must close and start ethminer. It occurs in both  platforms (nvidia, amd)

**Comment by whotheff** [comment] 2018-04-09 20:31
I have two rigs mining and they both disconnect at the same time. While a CPU mining continues with no interrupt. How is it possible that they both drop at the same time?

**Comment by papampi** [comment] 2018-04-10 13:11
+1
Updated 5 Rigs to 0.14rc4, all 5 lose connection at same time while rest are mining with no problem.

**Comment by invidtiv** [comment] 2018-04-11 00:34
same here, have a old switch , if it fails to connect proper on first round of connection, then ethminer will drop the stratum connection, and will not reconnect.
This is causing stability issues. I also have PPPoE wan connection, and I know that it resets itself from time to time, on that occurrence all ethminers will stop working,
This can be easily reproduced by removing the ethernet cable from the rig, reconnecting the ethernet does not make ethminer reestablish the connection, it just stays in a loop trying to reconnect unsuccessfully.

**Comment by Xeroeth** [comment] 2018-04-12 06:54
+1

**Comment by aleqx** [comment] 2018-04-15 03:43
I just posted https://github.com/ethereum-mining/ethminer/issues/1007 as I didn't find this issue at first

Is RC2 fine?

I wish the devs did a little bit more testing before releasing RC stuff. The development during the past couple of months felt quite rushed. Please don't release RC stuff without testing - we all understand it's open source and the community should test, and we're all grateful, but keep the DEV label until actual tests are done and more community members confirm it's working.

**Comment by aleqx** [comment] 2018-04-15 04:06
I can confirm that RC2 has the same problem ... all of them up to 0.15dev1. Haven't yet tried RC1

**Comment by aleqx** [comment] 2018-04-15 04:14
Also, killing the process via CTRL-C doesn't work either. `kill` must be used, sometimes `kill -9` ...

testing, testing, testing ...

**Comment by chfast** [comment] 2018-04-15 11:58
These 2 mins issues are still there. Nobody had time to fix it yet.

**Comment by ThetaProtocol** [comment] 2018-04-18 00:00
Have also had this issue with every build since 13 stable release. Ethminer will work until a disconnect and keep running doing nothing in addition to continual power consumption. Running 0.15.0dev2 tonight to confirm its existence there as well.

**Comment by chfast** [comment] 2018-04-24 20:55
What is the latest working version?

**Comment by AndreaLanfranchi** [comment] 2018-04-25 05:55
@jean-m-cyr 
you're right. I'm working over EthStratumClient.cpp and it has numerous points of failure plus a couple of nonsenses.

**Comment by chfast** [comment] 2018-04-25 08:40
From my tests, it looks at least DNS lookup will not be retried so the connection stops there.

**Comment by whotheff** [comment] 2018-04-25 09:33
I've set my router to permanent DHCP address for the rigs, added google DNS, no difference. Connection still drops randomly and fails to reconnect to both  primary and secondary addresses. Any luck with 0.15?

**Comment by chfast** [comment] 2018-04-25 09:40
@whotheff But you still fail to answer simple questions as "What is the latest working version?"

**Comment by Olegatorius** [comment] 2018-04-25 10:00
12.x ?

**Comment by aleqx** [comment] 2018-04-25 10:27
> @whotheff But you still fail to answer simple questions as "What is the latest working version?"

12.0 works fine as long as reconnection is concerned. But isn't this your project?

**Comment by chfast** [comment] 2018-04-25 10:39
> But isn't this your project?

It's not.

**Comment by aleqx** [comment] 2018-04-25 10:40
I thought all releases were made by you.

**Comment by whotheff** [comment] 2018-04-25 15:17
@alexq Yes, the last non disconnecting was 12.x. 13 and 14 have more stabile hashrate, but screwed the connection part.

**Comment by whotheff** [comment] 2018-04-25 18:17
The worst part is that sometimes it keeps the cards spinning (using electricity and producing heat)

**Comment by chfast** [comment] 2018-04-26 10:44
> I thought all releases were made by you.

They are. Do you want to do the next release?
I'm not using this software, so if an issue is not properly reported it cannot be fixed.

**Comment by AndreaLanfranchi** [comment] 2018-04-29 10:07
Resolved in 0.14.rc6

**Closed by AndreaLanfranchi** 2018-04-29 10:07 UTC
Labels: bug
