### ISSUE TITLE
Yesterday my 1060 with 3 gig worked mining Ethereum Classic, Today it doesn't?

### ISSUE THREAD

**Issue by RUminingTwo** [ethereum-mining/ethminer#713] opened 2018-02-07 18:47 UTC
I have successfully been using the console, but as of today it seems like it cant successfully run. Seems the it gets to the point that there doesn't seem to be enough GPU memory ( 1060 GPU with 3 Gig) . Yesterday Windows Updates installed. so I dont know if that has something to do with the system files, that were updated and the console not being able to mine Ethereum Classic today.

I have other Win Servers running the older ver 13 still working fine with the same 1060 3 Gig cards.

Everything was working yesterday mining Ethereum Classic today it wont fully run?

Any thoughts would be appreciated to get the console to run again.

**Comment by piotr-dobrogost** [comment] 2018-02-07 19:03
Duplicate of issue #711

**Comment by RUminingTwo** [comment] 2018-02-07 19:42
Thank you for the follow up.

 

The strange thing is I have another system with the same 1060 3 gig card that is still working. But its running on Windows sever 2012

**Comment by DeadManWalkingTO** [comment] 2018-02-18 21:42
I think this issue can be closed.

**Comment by RUminingTwo** [comment] 2018-02-18 22:52
I agree, 

 

Just food for thought, mining ETC with 3 Gig 1060 GPU still works for my Win 2012 servers, Its only still an issue on Win 10 x64

**Closed** 2018-02-19 13:18 UTC
