### ISSUE TITLE
Low hash rate

### ISSUE THREAD

**Issue by davidwillis** [ethereum-mining/ethminer#415] opened 2017-12-02 17:04 UTC
Hi,
I opened this earlier and it was closed saying I sould use -U for cuda.  But if you read, I am using rx 580 cards, which are AMD.  etherminer worsk fine with my nvida cards using cuda, but I am having problems getting it to work with AMD cards.

With my six rx580 cards, I get over 180mh/s using claymore (174 with the nofee option). However with ethminer I am only getting 130-135mh/s. I am sure I have something wrong to be this low. Both are using the same overclock (using msi afterburner), and the same modded bios.

Here is my start file.
ethminer --farm-recheck 200 -G --opencl-platform 1 -S us1.ethermine.org:4444 -O ee8866a0f1e6fae19cb5ddfbcdfc6ca076c1d73b.rig1

Also I am running windows 10.

**Comment by smurfy** [comment] 2017-12-02 17:05
dupe of #414

**Closed by smurfy** 2017-12-02 17:05 UTC
