### ISSUE TITLE
ethminer 0.15.0.dev1 - all shares rejected

### ISSUE THREAD

**Issue by Teressss** [ethereum-mining/ethminer#1003] opened 2018-04-12 23:09 UTC
I wanted to try ethminer 0.15.0.dev1 today. After a while I notice, that all my shares to nanopool was rejected. What is going on??

**Comment by chfast** [comment] 2018-04-13 11:05
What protocol do you use?

**Comment by Teressss** [comment] 2018-04-13 11:06
the same protocol I used on all version of ethminer before on this pool

**Comment by chfast** [comment] 2018-04-13 11:13
> the same protocol I used

And which one it is? Can you send you command line options if you don't understand what I'm asking about?

**Comment by chfast** [comment] 2018-04-13 11:25
Because I'm modifying the ethash library. I tested only CUDA and single stratum protocol.

**Comment by Starkot** [comment] 2018-04-13 22:02
It seems to me the same. 0.15.0.dev1
✘  00:45:46|cl-0    |  FAILURE: GPU gave incorrect result!
In 0.14 its Ok.
Stratum+ssl

**Comment by Psyire** [comment] 2018-04-13 22:24
I'm having the exact same issue with 0.15

"Failure: GPU gave incorrect result!"

No issues with 0.14.

NVidia 1060 3GB, mining on miningpoolhub (stratum)

**Comment by claymore008** [comment] 2018-04-14 08:36
and me the same issue, many of "GPU gave incorrect result" on Nvidia 1070 8GB.

**Comment by megapearl** [comment] 2018-04-14 10:15
I'm not having this issue with nanopool, shares got accepted, no difference for me between 0.15 and 0.14
 m  12:11:56|ethminer|  Speed 258.41 Mh/s    gpu/0 32.40 47C 100% 109W  gpu/1 31.89 47C 100% 111W  gpu/2 32.10 40C 100% 109W  gpu/3 33.43 42C 100% 110W  gpu/4 31.89 46C 100% 110W  gpu/5 31.79 42C 100% 110W  gpu/6 31.79 52C 100% 107W  gpu/7 33.12 50C 100% 110W  [A102+1:R0+0:F0] Time: 01:10
  ℹ  12:11:57|cuda-7  |  Nonce 0xb77xxxxxx02e06a5 submitted to eth-eu1.nanopool.org
  ℹ  12:11:58|stratum |  **Accepted  in 44 ms.

**Comment by SergiumX** [comment] 2018-04-14 15:49
me too the same issue with 0.15dev1   - "GPU gave incorrect result" on Nvidia 1060 (6Gb), 1050Ti etc. 
No issues with 0.14.

**Comment by th0ma7** [comment] 2018-04-14 16:10
Same here!
Using Legacy OpenCL from amdgpu-pro with Radeon RX 560

**Comment by mixa6688** [comment] 2018-04-14 20:59
Same here on Hive OS! Update 0.5-44 2018-04-13, ethminer 0.15-dev1.
In settings miner, "stratum2+tcp://daggerhashimoto.eu.nicehash.com", report from miner "GPU gave incorrect result!"

**Comment by H05ted** [comment] 2018-04-16 14:27
the same i get on 0.14rc4 too, 0.14rc3 works fine.

**Comment by Zohaib2018** [comment] 2018-04-16 17:14
I have Gtx 1050ti  4GB
2 CARD AND BORD ASUIS Z270P

PLZZ SUGESHION ME KON SA COIN MINE KARO MA JISS MA PROFIT MILY :(

**Comment by Zohaib2018** [comment] 2018-04-16 17:15
PLZ HELP ME :(

**Comment by chfast** [comment] 2018-04-17 14:07
I will be testing this today or tomorrow. Can you send me the full list of command line arguments to ethminer what does not work for you?

**Comment by H05ted** [comment] 2018-04-17 14:17
Hi! This settings working with 0.14rc3.


ethminer -U --farm-recheck 500 -RH  -HWMON -P stratum+ssl://
0xb4983146f0047d87c63b5fdb3ef9e2bee4557ea3.M1@eu1.ethermine.org:5555 -P
stratum+ssl://
0xb4983146f0047d87c63b5fdb3ef9e2bee4557ea3.M1@us1.ethermine.org:5555
--api-port -7777


With newer versions on all my rigs 21 gpu incorrect.

вт, 17 апр. 2018 г., 17:07 Paweł Bylica <notifications@github.com>:

**Comment by chfast** [comment] 2018-04-17 17:44
@H05ted what OS do you use?

**Comment by H05ted** [comment] 2018-04-17 17:51
Ubuntu 16.04 lts xfce nvidia only, different driver versions on some rigs
but results the same, last time i updated all rigs at once and dont
understand what heppend at first but then see errors and get back to stable
version and all good for now. 5.2 ghs note a joke ))

вт, 17 апр. 2018 г., 20:44 Paweł Bylica <notifications@github.com>:

**Comment by chfast** [comment] 2018-04-17 17:59
I don't understand. Is this still an issue?

I'm just mining with your config for your address. You should see "chfast" worker.

**Comment by H05ted** [comment] 2018-04-17 18:04
Yes i see it in list, the version of ethminer 0.15dev1 ? Becouse with this
and 0.14rc4 i have errors. Now im using 0.14rc3.

вт, 17 апр. 2018 г., 20:59 Paweł Bylica <notifications@github.com>:

**Comment by H05ted** [comment] 2018-04-17 18:15
Pawel where i can send you some eth for you work? Im a good system
administrator but for now i dont have anough time to find out how to
powerline pci-e, i think it must be. Some times gpu just hangs and ethminer
will still show hashrate but it not true.

вт, 17 апр. 2018 г., 21:04 Vov4ik _ <vhosted@gmail.com>:

**Comment by chfast** [comment] 2018-04-17 18:30
Funny. I can confirm the issue in the ethminer binary downloaded from GitHub, but not in one I built myself. Does anyone have problem with 0.15.0.dev1 on operating system other than Linux?

**Comment by chfast** [comment] 2018-04-17 19:11
@H05ted you can find my tip address in my GitHub profile, but I rather need way of testing changes and access to hardware. Find me on https://gitter.im/ethereum-mining/ethminer.

**Comment by chfast** [comment] 2018-04-17 19:48
I fixed the bug, give me some time to release new version.

**Comment by AndreaLanfranchi** [comment] 2018-04-17 19:51
Using 0.15.0.dev1 on roughly 30 rigs with overall 3.5 Gh/s.
Not a single invalid share.

Using Ubuntu 16.04
Cuda 9.1
Driver Nvidia 390.12
Cards 1050 ti / 1060 / 1070

Must be noted that on every machine ethminer is compiled from source.

**Comment by chfast** [comment] 2018-04-17 19:56
Thanks @AndreaLanfranchi.
The issues is in builds with GCC 4.8.

**Comment by chfast** [comment] 2018-04-17 20:40
Fixed in https://github.com/ethereum-mining/ethminer/releases/tag/v0.15.0.dev2.

**Closed by chfast** 2018-04-17 20:40 UTC
Labels: bug
