### ISSUE TITLE
Cuda error in func 'set_constants'

### ISSUE THREAD

**Issue by 007fred50** [ethereum-mining/ethminer#1885] opened 2019-05-02 09:31 UTC
Hello,

i got error:
  11:14:32|ethminer  Connecting to stratum server eth.pool.minergate.com:45791
  11:14:32|stratum  Connected to stratum server eth.pool.minergate.com : 45791
  11:14:32|stratum  Starting farm
  11:14:32|stratum  Subscribed to stratum server
  11:14:33|stratum  Authorized worker xxxxx@xxxxx
  11:14:33|stratum  Received new job #e9cd9560
  11:14:33|cudaminer0  set work; seed: #a6fcfcc1, target:  #000010c6f7a0
  11:14:33|cudaminer0  Initialising miner...
  m  11:14:34|ethminer  Mining on PoWhash #e9cd9560 : 0.00MH/s [A0+0:R0+0:F0]
  11:14:35|stratum  Received new job #d434f2f1
Using device: GeForce RTX 2080 (Compute 7.5)
Cuda error in func 'set_constants' at line 143 : invalid device symbol.

somthng i do wrong ?

i try on cuda 9 and 10 still does not work !

**Comment by AndreaLanfranchi** [comment] 2019-05-13 10:06
Closing as it's duplicate of #1886

**Closed by AndreaLanfranchi** 2019-05-13 10:06 UTC
Labels: duplicate
