### ISSUE TITLE
ethminer 0.16.0.dev1 can't start miner - Error: "terminate called without an active exception" (smOS)

### ISSUE THREAD

**Issue by luteknarozniak** [ethereum-mining/ethminer#1378] opened 2018-07-24 17:32 UTC
Getting error message:

============Starting Miner ===============
m 18:54:05 ethminer ethminer 0.16.0.dev1
m 18:54:05 ethminer Build: linux/release
terminate called without an active exception
/root/xminer.sh: line 102: 4666 Segmentation fault $MINER_PATH $MINER_OPTIONS
Miner ended/crashed. Restarting miner in 10 seconds --------------

Tried with nanopool, dwarfpool, sparkpool and nicehash - makes no difference.
Tried with overclock applied and stock values as well - again, no difference.

No problems with ethminer 0.14 (there's no 0.15 available on smOS to try).

Developer of smOS claims they have tested it on nanopool and it worked. Suggested to ask around on ethminer forum.

Any ideas?

Lutek.

**Comment by AndreaLanfranchi** [comment] 2018-07-24 18:05
Is it the first start or are you re-starting after an error ?

Could you please do a cold restart and start the miner ? (report results)

**Comment by luteknarozniak** [comment] 2018-07-24 18:36
Cold restart done. Same error:

terminate called without an active exception
/root/xminer.sh: line 102: 4030 Aborted $MINER_PATH $MINER_OPTIONS
Miner ended/crashed. Restarting miner in 10 seconds --------------
============ Starting Miner ===============
m 20:35:44 ethminer ethminer 0.16.0.dev1
m 20:35:44 ethminer Build: linux/release
terminate called without an active exception
/root/xminer.sh: line 102: 4822 Aborted $MINER_PATH $MINER_OPTIONS
Miner ended/crashed. Restarting miner in 10 seconds --------------
============ Starting Miner ===============
m 20:35:54 ethminer ethminer 0.16.0.dev1
m 20:35:54 ethminer Build: linux/release
terminate called without an active exception
/root/xminer.sh: line 102: 5508 Aborted $MINER_PATH $MINER_OPTIONS
Miner ended/crashed. Restarting miner in 10 seconds --------------

**Comment by smurfy** [comment] 2018-07-24 18:45
what exactly is the commandline?

**Comment by luteknarozniak** [comment] 2018-07-24 18:49
-U -P stratum1+tcp://ETH_address.Worker_name@eth-us-west1.nanopool.org:9999

**Comment by ddobreff** [comment] 2018-07-25 08:55
We have switched to autostratum configuration.

**Comment by luteknarozniak** [comment] 2018-07-25 15:48
> 50181

Is my command line wrong then?

**Comment by xdemocle** [comment] 2018-07-25 21:01
I don't think is command line misconfiguration.
I got same issue with my rig nvidia 1060:
`terminate called without an active exception`

**Comment by StefanOberhumer** [comment] 2018-07-25 21:13
@xdemocle : Are you also using SMOS (Simple Mining OS) ?

**Comment by xdemocle** [comment] 2018-07-25 21:21
@StefanOberhumer no sorry, forgot to mention. I do not use SMOS.

**Comment by StefanOberhumer** [comment] 2018-07-25 21:38
OK - I can reproduce it if I use the official 0.16.0.dev1 release (normally I use self compiled actual dev snapshots).
Seems to be a build problem of the official release !

**Comment by luteknarozniak** [comment] 2018-07-25 22:02
Perhaps Tytanick (smOS developer) had tested the miner compiled from the same source as you @StefanOberhumer and it worked for him, but then he has added the official release to smOS and that one, unfortunately, comes with some build issues.

**Comment by XhmikosR** [comment] 2018-07-26 05:42
@StefanOberhumer It's built on Travis for nix and AppVeyor for Windows.

**Comment by ddobreff** [comment] 2018-07-26 09:40
This was already discussed. CUDA 9.2 works on 396+ but not on 390, while 9.1/9.0 work on both. There is no known/found benefit of using 9.2 over 9.1/9.0.

**Comment by StefanOberhumer** [comment] 2018-07-26 10:33
@ddobreff : I think it's not an issue/discussion which CUDA driver version we're using/require. 
Currently ethminer segfaults without displaying a proper message if the driver mismatches - That should be fixed.

**Comment by luteknarozniak** [comment] 2018-07-27 17:39
> @luteknarozniak : Just as I know/remember:
smOS does not upgrade the drivers/kernel within their online updates!
To get new drivers/kernel you have to download their latest image and write it to the HDD/USB!

@StefanOberhumer I flushed new image (kernel 4.7.1) about couple of weeks ago. I don't think there is a newer version. 
Just run `nvidia-smi` command and yes, we're still running on `Driver Version: 390.67`.
Will ask Tytanick if he can install 396 driver for us.

**Comment by ddobreff** [comment] 2018-07-27 17:48
396 are not stable enough to use in production environment.

**Comment by StefanOberhumer** [comment] 2018-07-27 20:52
@luteknarozniak 
1.) Do you get also `error: Insufficient CUDA driver` when running `./ethminer -U --list-devices`
==> we can close this issue
2.) You can add some comments to issue #1390 where a downgrade to CUDA 9.0 is requested

**Comment by luteknarozniak** [comment] 2018-07-27 22:45
@StefanOberhumer 
> 1.) Do you get also error: Insufficient CUDA driver when running ./ethminer -U --list-devices
==> we can close this issue
Can't run that command as there is no ./ethminer folder in smOS (at least I can't find it). However, I'm getting `Insufficient CUDA driver: 9010` error while trying to mine with ethminer 0.15.0, Tytanick has just added.

> 2.) You can add some comments to issue #1390 where a downgrade to CUDA 9.0 is requested
Yea, it'd be great if the ethminer could remain compatible with older Nvidia drivers (especially since new driver is still not quite ready to be used in production environment).

**Comment by StefanOberhumer** [comment] 2018-07-31 08:00
> Can't run that command as there is no ./ethminer folder in smOS (at least I can't find it). 

As I remember the miners are at /root/miner/ethminer.... or at /root/miner_org/ethminer....


You also can adapt you commandline (in the SMOS interface) to `-U --list-devices`

**Closed by StefanOberhumer** 2018-07-31 08:00 UTC
