### ISSUE TITLE
LLVM ERROR

### ISSUE THREAD

**Issue by sandisufiandi** [ethereum-mining/ethminer#804] opened 2018-02-25 19:29 UTC
I found following error during run ethminer
I use ubuntu linux 16.04

LLVM ERROR: Cannot select: 0x7f2e980c0ca8: i32,ch = AtomicLoadAdd<Volatile LDST4[%g_output(addrspace=1)]> 0x7f2e9837aba8, 0x7f2e980b5b70, Constant:i32<1>
  0x7f2e980b5b70: i32,ch = CopyFromReg 0x7f2e9837aba8, Register:i32 %vreg170
    0x7f2e980b1478: i32 = Register %vreg170
  0x7f2e98078fd0: i32 = Constant<1>
In function: ethash_search

I am a newbie, and learning by doing...

**Comment by DeadManWalkingTO** [comment] 2018-02-27 14:16
Please give more info.

1. Ethminer version : 
2. OS : Ubuntu 16.04
3. GPU
4. Drivers version
5. Full run command

Thank you!

**Comment by renyuneyun** [comment] 2018-03-09 15:15
I'm having the same error (with different memory addresses).

1. Ethminer version: 0.13.0
2. OS: archlinux x86_64, kernel 4.15.5
3. GPU: Radeon HD 7600M
4. Drivers: mesa (and opencl-mesa)
5. Command: `ethminer -G --opencl-platform 0 --benchmark`

**Comment by chfast** [comment] 2018-06-04 15:35
This is the OpenCL driver issue. We can try help, but the problem is not on ethminer side.

Closing because not active for a month.

**Closed by chfast** 2018-06-04 15:35 UTC
Labels: discussion
