### ISSUE TITLE
0.15 binaries no longer run on Ubuntu 16.04 (wrong libgcc)

### ISSUE THREAD

**Issue by aleqx** [ethereum-mining/ethminer#1216] opened 2018-06-04 21:49 UTC
It would be really nice if you guys compiled the binaries using a more widespread (slightly older) libstdc++ so that it runs on more systems. My 16.04 can't run the 0.15dev11 linux binaries you pushed.

```
# /node/ethminer-0.15dev11 --help
/node/ethminer-0.15dev11: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /node/ethminer-0.15dev11)
```

I know how to install new gcclibs etc - i'm advocating for greater compatibility. Could you please compile 0.15 using the same toolchain that you used to compile 0.14? Those ones work fine.

**Comment by XhmikosR** [comment] 2018-06-05 06:50
Duplicate of #1140

**Closed by XhmikosR** 2018-06-05 06:50 UTC
