### ISSUE TITLE
Limiting GPU Usage

### ISSUE THREAD

**Issue by oguzhankrcby** [ethereum-mining/ethminer#739] opened 2018-02-14 04:11 UTC
Hi, i build the source newly and i am looking for limiting gpu usage but i couldn't reach any solution for that, i really need that gpu limitation, i am open for any ideas...

**Comment by AndreaLanfranchi** [comment] 2018-02-14 14:56
Duplicate of #576

**Comment by DeadManWalkingTO** [comment] 2018-02-18 21:34
I think this issue can be closed.

**Comment by smurfy** [comment] 2018-02-19 13:16
As mentioned before, this is a duplicate and there is no plan adding support for this at this time.
Patches welcome.

**Closed by smurfy** 2018-02-19 13:16 UTC

**Comment by NukeManDan** [comment] 2021-04-08 02:04
Cross posting: #2222 may help those looking to solve this. Thanks @TroyNeubauer 🙇🏼 !
