### ISSUE TITLE
Mixed AMD/Nvidia cards can't work

### ISSUE THREAD

**Issue by peterwillcn** [ethereum-mining/ethminer#243] opened 2017-08-18 04:16 UTC
Centos 7
Ethminer are generated by source compilation (master:a537ed9bb5bd)
NVIDIA-SMI 375.26 Driver Version: 375.26
amdgpu-pro-driver Driver Version: 17.30-465504 for centos7

```
./ethminer --list-devices

Listing OpenCL devices.
FORMAT: [deviceID] deviceName
[0] Ellesmere
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8566140928
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] GeForce GTX 1070
	CL_DEVICE_TYPE: GPU
	CL_DEVICE_GLOBAL_MEM_SIZE: 8507555840
	CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2126888960
	CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
[CUDA]:
Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1070
	Compute version: 6.1
	cudaDeviceProp::totalGlobalMem: 8507555840
```

Only -G or -U work very well.
```
./ethminer -G --opencl-device 0 --farm-recheck 200 -F http://127.0.0.1:8080/eth01
./ethminer -U --cuda-devices 1  --farm-recheck 200 -F http://127.0.0.1:8080/eth01
```
But -G and -U can't work.
```
./ethminer -G --opencl-device 0 -U --cuda-devices 1  --farm-recheck 200 -F http://127.0.0.1:8080/eth01
```

use -X also don't work.
```
./ethminer -X  --farm-recheck 200 -F http://127.0.0.1:9090/eth03
  ℹ  01:26:42|ethminer  Found suitable OpenCL device [ Ellesmere ] with 8566140928  bytes of GPU memory
  m  01:26:42|ethminer  Getting work package...
  m  01:26:42|ethminer  Got work package: #e46e2de1
  m  01:26:43|ethminer  Mining on #e46e2de1… [A0+0:R0+0:F0]
  m  01:26:43|ethminer  Total: 0.00MH/s ( )
  m  01:26:43|ethminer  Mining on #e46e2de1… [A0+0:R0+0:F0]
  m  01:26:43|ethminer  Total: 0.00MH/s ( )
  m  01:26:43|ethminer  Mining on #e46e2de1… [A0+0:R0+0:F0]
  m  01:26:43|ethminer  Total: 0.00MH/s ( )
  m  01:26:43|ethminer  Mining on #e46e2de1… [A0+0:R0+0:F0]
  m  01:26:43|ethminer  Total: 0.00MH/s ( )

./ethminer -X --opencl-platform 0 --farm-recheck 200 -F http://127.0.0.1:9090/eth03
  ℹ  20:12:18|ethminer  Found suitable OpenCL device [ Ellesmere ] with 8566140928  bytes of GPU memory
  m  20:12:18|ethminer  Getting work package...
  m  20:12:18|ethminer  Got work package: #3032f35b
  m  20:12:19|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:19|ethminer  Total: 0.00MH/s ( )
  m  20:12:19|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:19|ethminer  Total: 0.00MH/s ( )
  m  20:12:19|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:19|ethminer  Total: 0.00MH/s ( )
  m  20:12:19|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]

./ethminer -X --opencl-platform 1 --farm-recheck 200 -F http://127.0.0.1:9090/eth03
  ℹ  01:23:45|ethminer  Found suitable OpenCL device [ GeForce GTX 1070 ] with 8507555840  bytes of GPU memory
  m  01:23:45|ethminer  Getting work package...
  m  01:23:45|ethminer  Got work package: #476a6ddb
  m  01:23:45|ethminer  Mining on #476a6ddb… [A0+0:R0+0:F0]
  m  01:23:45|ethminer  Total: 0.00MH/s ( )
  m  01:23:45|ethminer  Mining on #476a6ddb… [A0+0:R0+0:F0]
  m  01:23:45|ethminer  Total: 0.00MH/s ( )
  m  01:23:45|ethminer  Mining on #476a6ddb… [A0+0:R0+0:F0]
  m  01:23:45|ethminer  Total: 0.00MH/s ( )
  m  01:23:45|ethminer  Mining on #476a6ddb… [A0+0:R0+0:F0]
  m  01:23:45|ethminer  Total: 0.00MH/s ( )
```

**Comment by smurfy** [comment] 2017-08-19 10:29
Works for me as your old title suggested use the -X flag (instead of the -G and -U)
I also needed "--opencl-platform" , because otherwise it always tried and failed to use my OnBoard graphics.

    [0] Intel(R) HD Graphics 4000
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 662700032
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 165675008
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 512
    [1] GeForce GTX 1080
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
    [2] Ellesmere
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 4244635648
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256


So i use ``ethminer -X --opencl-platform 2 ....``
If i use 1 as platform it uses the geforce only in cl mode, otherwise it works and it runs opencl on my RX 580 and Cuda on my 1080. 

Also it only worked for me using cuda+opencl, it did not work for both opencl, but my guess is thats due to the onboard graphics. 

     i  12:27:26|main      OpenCL device Intel(R) HD Graphics 4000   has insufficient GPU memory. 
    662700032  bytes of memory found < 1073739904  bytes of memory required
    No GPU device with sufficient memory was found. Can't GPU mine. Remove the -G argument

So i guess there is some kind of problem related to opencl device selection.

Also i'm on windows, based on the ``./``  it looks like you are on linux.

**Comment by peterwillcn** [comment] 2017-08-20 00:14
Hello smurfy,

I use centos7, use -X also don't work.
 ```
ethminer -X --opencl-platform 0 --farm-recheck 200 -F http://127.0.0.1:9090/eth03
  ℹ  20:12:18|ethminer  Found suitable OpenCL device [ Ellesmere ] with 8566140928  bytes of GPU memory
  m  20:12:18|ethminer  Getting work package...
  m  20:12:18|ethminer  Got work package: #3032f35b
  m  20:12:19|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:19|ethminer  Total: 0.00MH/s ( )
  m  20:12:19|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:19|ethminer  Total: 0.00MH/s ( )
  m  20:12:19|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:19|ethminer  Total: 0.00MH/s ( )
  m  20:12:19|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:19|ethminer  Total: 0.00MH/s ( )
  m  20:12:19|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:19|ethminer  Total: 0.00MH/s ( )
  m  20:12:20|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:20|ethminer  Total: 0.00MH/s ( )
  m  20:12:20|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:20|ethminer  Total: 0.00MH/s ( )
  m  20:12:20|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:20|ethminer  Total: 0.00MH/s ( )
  m  20:12:20|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:20|ethminer  Total: 0.00MH/s ( )
  m  20:12:20|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:20|ethminer  Total: 0.00MH/s ( )
  m  20:12:21|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:21|ethminer  Total: 0.00MH/s ( )
  m  20:12:21|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:21|ethminer  Total: 0.00MH/s ( )
  m  20:12:21|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:21|ethminer  Total: 0.00MH/s ( )
  m  20:12:21|ethminer  Mining on #3032f35b… [A0+0:R0+0:F0]
  m  20:12:21|ethminer  Total: 0.00MH/s ( )
```

**Comment by YanBellavance** [comment] 2017-08-20 03:23
why do you want to use opencl with nvidia..  its better to use cuda instead

**Comment by peterwillcn** [comment] 2017-08-20 04:10
@YanBellavance
  use opencl for device 0 is AMD 570 Ellesmere
  device 1 is Nvidia 1070 -X use cuda but  not work.

**Comment by YanBellavance** [comment] 2017-08-21 05:26
I  think there are 3 modes: open-cl, cuda and mixed.

**Comment by YanBellavance** [comment] 2017-08-21 05:27
i  12:27:26|main      OpenCL device Intel(R) HD Graphics 4000   has insufficient GPU memory.

This looks like an onboard graphics card so

Device 0 would be onboard,
 1 and 2 would be your amd and nvidia

**Comment by YanBellavance** [comment] 2017-08-21 05:35
How about launching the program  twice?  One for each card.  Why use cent os? 
Ubuntu has better support. CentOS is a free version of redhatlinux and this type of distro is k own to be buggy and undersupported. I always had integration problems on red hat distros and much smokther results with Ubuntu.

**Comment by YanBellavance** [comment] 2017-08-21 05:41
What is your nvidia driver version? What is your open cl version?
Cuda does not support open cl v2 i think. Only v1. Did you build or download binary?  If you built it then whay cida version did you use? 

Did you try using --cuda-devices

**Comment by peterwillcn** [comment] 2017-08-21 11:36
@YanBellavance 
   Ethminer are generated by source compilation (master:a537ed9bb5bd)
NVIDIA-SMI 375.26                 Driver Version: 375.26
amdgpu-pro-driver                  Driver Version: 17.30-465504 for centos7

**Comment by YanBellavance** [comment] 2017-08-21 16:10
Are you able to setup a debugging environment and let me connect remote? I'd gladly step through the code and find your problem.

Otherwise unbuntu is your best bet.

**Comment by peterwillcn** [comment] 2017-08-22 11:53
@YanBellavance 
Thank you very much for your kind help 👍, but one thing I don't quite agree with you. I've been using enterprise level RHEL and Centos at the data center, very stable, and some Ubuntu comparison data found less stable than Centos. :-)

**Comment by smurfy** [comment] 2017-08-22 11:58
@peterwillcn 
My guess is, in the context of mining/graphic card support
I think ubuntu is the top desktop linux distro, which better graphic card support. (like Steam focused on ubuntu too)

Other than that CentOS/RHEL/Debian for Servers is the better choice. (Stability and Security/Updates wise)

**Comment by smurfy** [comment] 2017-08-23 10:34
Probably duplicate of #123

**Comment by smurfy** [comment] 2017-09-08 15:50
Please test if #302 fixes the problem

**Closed** 2017-09-12 11:35 UTC

**Comment by goodcoin8** [comment] 2017-12-11 08:52
OS:centos 7.3
ethminer: 0.12.0

./ethminer --opencl-platform 1 -X -F http://127.0.0.1:8080/rig1 

This can work with GeForce GTX 1060 and AMD RX580.
