### ISSUE TITLE
Absurd hash rates on OS X

### ISSUE THREAD

**Issue by jakehaas** [ethereum-mining/ethminer#603] opened 2018-01-22 15:48 UTC
Mining on a Radeon Pro 570 4 GB

Currently on Mac OS High Sierra (10.13.2), but this was also happening to me on other versions.

Mining worked great until a few weeks ago and all of a sudden I am getting insanely high hash rates. (See sample output below)

(Nothing gets submitted to pool - At first, I thought maybe just display error)

Tried both stable and unstable kernel.

I had 2 computers with this card and they both started reporting these hash rates at the same time (overnight on the same day). This makes me believe it's not a hardware issue... Even so, I reformatted one of them and re-installed OS X to no avail. The same thing...

What is weird is that the DAG is being generated instantly (less than a second) and this used to take maybe 10 seconds or so...

Next, I installed Ubuntu on a separate partition to see if I could get it mining again. After installing the AMD drivers it started hashing properly again at the expected ~15MH/s.

So there is an issue 

> cl  10:38:56|cl-0      OpenCL kernel: Unstable kernel
>  cl  10:38:56|cl-0      Build info: 
>  cl  10:38:56|cl-0      Creating light cache buffer, size 38403392
>  cl  10:38:56|cl-0      Creating DAG buffer, size 2457861248
>  cl  10:38:56|cl-0      Loading kernels
>  cl  10:38:56|cl-0      Writing light cache buffer
>  cl  10:38:56|cl-0      Creating buffer for header.
>  cl  10:38:56|cl-0      Creating mining buffer
>  cl  10:38:56|cl-0      Generating DAG
>  cl  10:38:56|cl-0      DAG 0 %
>  cl  10:38:56|cl-0      DAG 2 %
>  cl  10:38:56|cl-0      DAG 5 %
>  cl  10:38:56|cl-0      DAG 8 %
>  cl  10:38:56|cl-0      DAG 10 %
>  cl  10:38:56|cl-0      DAG 13 %
>  cl  10:38:56|cl-0      DAG 16 %
>  cl  10:38:56|cl-0      DAG 18 %
>  cl  10:38:56|cl-0      DAG 21 %
>  cl  10:38:56|cl-0      DAG 24 %
>  cl  10:38:56|cl-0      DAG 27 %
>  cl  10:38:56|cl-0      DAG 29 %
>  cl  10:38:56|cl-0      DAG 32 %
>  cl  10:38:56|cl-0      DAG 35 %
>  cl  10:38:56|cl-0      DAG 37 %
>  cl  10:38:56|cl-0      DAG 40 %
>  cl  10:38:56|cl-0      DAG 43 %
>  cl  10:38:56|cl-0      DAG 45 %
>  cl  10:38:56|cl-0      DAG 48 %
>  cl  10:38:56|cl-0      DAG 51 %
>  cl  10:38:56|cl-0      DAG 54 %
>  cl  10:38:56|cl-0      DAG 56 %
>  cl  10:38:56|cl-0      DAG 59 %
>  cl  10:38:56|cl-0      DAG 62 %
>  cl  10:38:56|cl-0      DAG 64 %
>  cl  10:38:56|cl-0      DAG 67 %
>  cl  10:38:56|cl-0      DAG 70 %
>  cl  10:38:56|cl-0      DAG 72 %
>  cl  10:38:56|cl-0      DAG 75 %
>  cl  10:38:56|cl-0      DAG 78 %
>  cl  10:38:56|cl-0      DAG 81 %
>  cl  10:38:56|cl-0      DAG 83 %
>  cl  10:38:56|cl-0      DAG 86 %
>  cl  10:38:56|cl-0      DAG 89 %
>  cl  10:38:56|cl-0      DAG 91 %
>  cl  10:38:56|cl-0      DAG 94 %
>  cl  10:38:56|cl-0      DAG 97 %
>  cl  10:38:56|cl-0      Switch time 1318 ms / 1319040 us
>  cl  10:38:56|cl-0      New work: header #bf3f9a4c… target 0000000225c17d04dad2965cc5a02a23e254c0c3f75d9178046aeb27ce1ca574
>  cl  10:38:56|cl-0      Switch time 1319 ms / 75 us
>   m  10:38:56|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
>   m  10:38:57|          Speed 8043.64 Mh/s    gpu/0 8043.64  [A0+0:R0+0:F0] Time: 00:00
>   m  10:38:58|          Speed 9963.31 Mh/s    gpu/0 9963.31  [A0+0:R0+0:F0] Time: 00:00
>   m  10:38:58|          Speed 9963.31 Mh/s    gpu/0 9963.31  [A0+0:R0+0:F0] Time: 00:00
>   m  10:38:59|          Speed 10573.96 Mh/s    gpu/0 10573.96  [A0+0:R0+0:F0] Time: 00:00
>   m  10:39:00|          Speed 10899.84 Mh/s    gpu/0 10899.84  [A0+0:R0+0:F0] Time: 00:00
>   m  10:39:00|          Speed 10899.84 Mh/s    gpu/0 10899.84  [A0+0:R0+0:F0] Time: 00:00
>   m  10:39:01|          Speed 11080.15 Mh/s    gpu/0 11080.15  [A0+0:R0+0:F0] Time: 00:00
>   m  10:39:01|          Got work package: #9ae87172
>  cl  10:39:01|cl-0      New work: header #9ae87172… target 0000000225c17d04dad2965cc5a02a23e254c0c3f75d9178046aeb27ce1ca574
>  cl  10:39:01|cl-0      Switch time 0 ms / 54 us
>   m  10:39:02|          Speed 11203.18 Mh/s    gpu/0 11203.18  [A0+0:R0+0:F0] Time: 00:00

**Comment by AndreaLanfranchi** [comment] 2018-01-23 14:17
Apparently this is an output from a quite old release.
Have you tested the latest one ?

**Comment by jakehaas** [comment] 2018-01-23 14:51
@AndreaLanfranchi 
I actually compiled this from source last week. 

I also tried with the latest release binary and same thing.

**Comment by briancamp** [comment] 2018-01-25 03:39
Same issue here on a RX 580. The default kernel turns ~ 4Mh/s and the unstable does around 13Mh/sec. Over 20 in both Linux and Windows.

Speculate that it happened around the same time as the 10.13.2 supplemental update.

**Comment by SirBryan** [comment] 2018-01-25 18:00
I'm seeing the same thing on RX 580's (one discrete in a Mac Pro, one integrated in an iMac 2017) under both Sierra and High Sierra, with build 0.13 (both rc4 and final).

**Comment by bplein** [comment] 2018-02-03 18:01
iMac Pro, Vega64, using 0.14.

Stable kernel, ~7 MH/s.
Unstable kernel, ~18.7 MH/s

**Comment by DeadManWalkingTO** [comment] 2018-02-27 18:04
Try latest version and feedback please.
Thank you!

**Comment by jakehaas** [comment] 2018-02-27 20:46
@DeadManWalkingTO 

Just tried compiling from source and running again. Same issue:


> Jakes-iMac:ethminer jakehaas$ ./ethminer -G -F http://eth-eu.dwarfpool.com:80/0xXXXXXXXXXXXXXXXXXXX/imac --opencl-device 0 --farm-recheck 200
>   m  15:43:49|        |  ethminer version 0.14.0.dev2
>   m  15:43:49|        |  Build: darwin / release
>   ℹ  15:43:49|        |  Found suitable OpenCL device [ AMD Radeon Pro 570 Compute Engine ] with 4294967296  bytes of GPU memory
>   m  15:43:49|        |  not-connected
>   ℹ  15:43:50|getwork |  Connected to http://eth-eu.dwarfpool.com:80/0xXXXXXXXXXXXXXXXXXXX/imac
>   ℹ  15:43:50|getwork |  Spinning up miners...
>  cl  15:43:50|cl-0    |  No work. Pause for 3 s.
>   ℹ  15:43:50|getwork |  New pool difficulty: 2.0000 gigahashes
>   ℹ  15:43:50|getwork |  Received new job #48df553f from http://eth-eu.dwarfpool.com:80/0xXXXXXXXXXXXXXXXXXXXX/imac
>  cl  15:43:53|cl-0    |  New seed #1261dfe1…
>  cl  15:43:54|cl-0    |  Platform: Apple
>  cl  15:43:54|cl-0    |  Device:   AMD Radeon Pro 570 Compute Engine  / OpenCL 1.2 
>  cl  15:43:54|cl-0    |  OpenCL kernel: Stable kernel
>   m  15:43:54|        |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
>  cl  15:43:55|cl-0    |  Build info: <program source>:336:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
>                 if (i == thread_id)
>       ~ ^  ~~~~~~~~~
> <program source>:371:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
>                 if (i == thread_id)
>       ~ ^  ~~~~~~~~~
> 
>  cl  15:43:55|cl-0    |  Creating light cache buffer, size 39320768
>  cl  15:43:55|cl-0    |  Creating DAG buffer, size 2516582272
>  cl  15:43:55|cl-0    |  Loading kernels
>  cl  15:43:55|cl-0    |  Writing light cache buffer
>  cl  15:43:55|cl-0    |  Creating buffer for header.
>  cl  15:43:55|cl-0    |  Creating mining buffer
>   ℹ  15:43:55|cl-0    |  2.34375  GB of DAG data generated in 3 ms.
>   m  15:43:59|        |  Speed 9694.29 Mh/s    gpu/0 9694.29  [A0+0:R0+0:F0] Time: 00:00
>   m  15:44:04|        |  Speed 10779.66 Mh/s    gpu/0 10779.66  [A0+0:R0+0:F0] Time: 00:00
> ^C  ℹ  15:44:09|getwork |  Received new job #f36165a5 from http://eth-eu.dwarfpool.com:80/0xXXXXXXXXXXXXXXXXXX/imac
>   ℹ  15:44:09|        |  Disconnected from http://eth-eu.dwarfpool.com:80/0xXXXXXXXXXXXXXXXXXXXXXXXXX/imac
>   ℹ  15:44:09|        |  Shutting down miners...

**Comment by SirBryan** [comment] 2018-02-27 20:54
On iMac Pro 10.13.3, Vega64 using 0.14-dev2
- With no options = 7.4Mh/s
- With --cl-global-work 163840 --cl-local-work 128 =  20.9Mh/s on both kernels
- With --cl-global-work 163840 --cl-local-work 256 =  42Mh/s (both)


On iMac 10.3.2, R580 using 0.14-dev2
- With --cl-global-work 163840 --cl-local-work 128 =  21.2Mh/s (stable)
- With --cl-global-work 163840 --cl-local-work 256 =  224Mh/s (invalid, and process hung)

**Comment by SirBryan** [comment] 2018-02-27 21:13
Update: On RX580, amounts over 128 seem to cause the GPU to go bye-bye when ethminer wants to exit:

from dmesg:

```
Trying to restart GPU (Radeon Pro 580)...
void IOGraphicsAccelerator2::reportGPURestart(IOAccelSubmitter2 *, const char *, uint32_t, uint64_t): Truncated vendor's (too-long) GPURestartReport from 393848 to 65534
```

**Comment by DeadManWalkingTO** [comment] 2018-02-28 04:01
Check if miner works!

OpenCL Hardware Test Launch Command:

```
ethminer -RH -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue603
```

Try with latest Ethminer version and feedback please.
Thank you!

**Comment by bplein** [comment] 2018-02-28 04:25
Trying @SirBryan settings, I get the same as he did on 0.14.0.dev1

"With --cl-global-work 163840 --cl-local-work 256 = 42Mh/s"

I wasn't setting cl-global-work, and I misinterpreted that this setting was 8129 default, not 8192 * 128 (which is clearly stated BUT 128 is also the default cl-local-work).

**Comment by bplein** [comment] 2018-02-28 17:17
Interestingly, while ethminer is reporting 42MH/s (actually 45+ right now), ethermine.org is barely registering around 7MH/s. When I ran it at 20MH/s with different settings, after less than an hour ethermine.org would show that I was running around 20MH/s. 

I'll let it run a while longer today to see if the average rate picks up over time (maybe just a statistical anomaly). Ethermine.org is NOT reporting may stale shares, and zero invalid shares.

**Comment by jakehaas** [comment] 2018-02-28 18:27
@DeadManWalkingTO 

Same extremely high hash rates with your settings:

> Jakes-iMac:ethminer jakehaas$ ./ethminer -RH -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue603
>   m  13:25:40|        |  ethminer version 0.14.0.dev2
>   m  13:25:40|        |  Build: darwin / release
>   ℹ  13:25:40|        |  Found suitable OpenCL device [ AMD Radeon Pro 570 Compute Engine ] with 4294967296  bytes of GPU memory
>   m  13:25:40|        |  not-connected
>   ℹ  13:25:40|stratum |  Connected to eu1.ethermine.org
>   ℹ  13:25:40|stratum |  Spinning up miners...
>  cl  13:25:40|cl-0    |  No work. Pause for 3 s.
>   ℹ  13:25:41|stratum |  Subscribed to stratum server
>   ℹ  13:25:41|stratum |  Authorized worker 0x7013275311fc37ccc1e40193D75086293eCb43A4.issue603
>   ℹ  13:25:41|stratum |  New pool difficulty: 4.0000 gigahashes
>   ℹ  13:25:41|stratum |  Received new job #88a43773 from eu1.ethermine.org
>  cl  13:25:43|cl-0    |  New seed #1261dfe1…
>  cl  13:25:45|cl-0    |  Platform: Apple
>  cl  13:25:45|cl-0    |  Device:   AMD Radeon Pro 570 Compute Engine  / OpenCL 1.2 
>  cl  13:25:45|cl-0    |  OpenCL kernel: Stable kernel
>  cl  13:25:45|cl-0    |  Build info: <program source>:336:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
>                 if (i == thread_id)
>       ~ ^  ~~~~~~~~~
> <program source>:371:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
>                 if (i == thread_id)
>       ~ ^  ~~~~~~~~~
> 
>  cl  13:25:45|cl-0    |  Creating light cache buffer, size 39320768
>  cl  13:25:45|cl-0    |  Creating DAG buffer, size 2516582272
>  cl  13:25:45|cl-0    |  Loading kernels
>  cl  13:25:45|cl-0    |  Writing light cache buffer
>  cl  13:25:45|cl-0    |  Creating buffer for header.
>  cl  13:25:45|cl-0    |  Creating mining buffer
>   ℹ  13:25:45|cl-0    |  2.34375  GB of DAG data generated in 4 ms.
>   m  13:25:45|        |  Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
>   ℹ  13:25:46|stratum |  Received new job #7aa3425f from eu1.ethermine.org
>   ℹ  13:25:50|stratum |  Received new job #91d85e19 from eu1.ethermine.org
>   m  13:25:50|        |  Speed 11166.27 Mh/s    gpu/0 11166.27  [A0+0:R0+0:F0] Time: 00:00
>   m  13:25:55|        |  Speed 11469.17 Mh/s    gpu/0 11469.17  [A0+0:R0+0:F0] Time: 00:00
>   ℹ  13:25:58|stratum |  Received new job #9a992790 from eu1.ethermine.org
>   m  13:26:00|        |  Speed 11868.02 Mh/s    gpu/0 11868.02  [A0+0:R0+0:F0] Time: 00:00
>   m  13:26:05|        |  Speed 11856.59 Mh/s    gpu/0 11856.59  [A0+0:R0+0:F0] Time: 00:00
>   m  13:26:10|        |  Speed 11765.52 Mh/s    gpu/0 11765.52  [A0+0:R0+0:F0] Time: 00:00
>   m  13:26:15|        |  Speed 11587.84 Mh/s    gpu/0 11587.84  [A0+0:R0+0:F0] Time: 00:00
> ^C  ℹ  13:26:19|stratum |  Received new job #fc1e00d8 from eu1.ethermine.org
>   ℹ  13:26:20|        |  Disconnected from eu1.ethermine.org
>   ℹ  13:26:20|        |  Shutting down miners...

**Comment by SirBryan** [comment] 2018-02-28 19:15
Ran dev2 all night on two machines. Nicehash shows hardly a dent in ether mining, even with both of machines reporting 20 (iMac) or 40Mh/s (iMac Pro). 

Ran with your command line and got 7.44Mh/s.

**Comment by bplein** [comment] 2018-02-28 19:36
My hash rate grew to about 17MH/s then fell, which is far below the reported 42Mh/s.

I'm really doubting that the default for cl-global-work is 8192*128 or 8192*cl-local-work. That would be 1048576, which if you plug that into the CLI, you get absurd MH/s reported. I bet this is actually default to 8192. I can raise this value to 128K and I get 35MH/s reported but not according to ethminer.org where I am seeing far fewer. It does better with the reported rate vs. real using default for global and 256 for local., where I get about 20Mh/s. 

Now running latest 0.14.0.dev2

**Comment by chfast** [comment] 2018-06-18 09:50
Duplicate of https://github.com/ethereum-mining/ethminer/issues/841.

**Closed by chfast** 2018-06-18 09:50 UTC

**Comment by bplein** [comment] 2018-06-18 12:48
Why close the older version of the issue? Technically #841 is a duplicate of this issue. Closing older dupes in favor of newer dupes misrepresents how long the issue has been open and what version of code it was first reported in.

**Comment by ezcoder** [comment] 2019-03-15 04:40
has any progress been made on this bug? I'm seeing it as well. For context, with the increase in eGPU's in the Mac community, and the difficulty installing Linux with the new T2 security chips I think it's worth the time to give Mac users a reason to participate in the growth of the ETH network.

**Comment by th3podfather** [comment] 2022-01-09 17:34
> On iMac Pro 10.13.3, Vega64 using precompiled 0.14-dev2
> 
> * With no options = 7.4Mh/s
> * With --cl-global-work 163840 --cl-local-work 128 =  20.9Mh/s on both kernels
> * With --cl-global-work 163840 --cl-local-work 256 =  42Mh/s (both)
> 
> On iMac 2017 10.3.2, RX580 using precompiled 0.14-dev2
> 
> * With --cl-global-work 163840 --cl-local-work 128 =  21.2Mh/s (stable)
> * With --cl-global-work 163840 --cl-local-work 200 =  32.78Mh/s (stable)
> * With --cl-global-work 163840 --cl-local-work 256 =  224Mh/s (invalid, and process hung, took machine with it during reboot attempt)
> 
> The 42 (Vega 64) and 32 (RX580) more closely match what is being reported on whattomine.com with special mods.

@SirBryan any chance you are willing to assist me in optimizing for iMac Pro Vega 64? Im hitting 24-25MH and would love to reach 42 as you were.

**Comment by SirBryan** [comment] 2022-01-10 03:36
I don't have access to that machine anymore, and gave up mining a couple years ago.  Aside from those command line flags and options, I wonder know what to suggest.

**Comment by th3podfather** [comment] 2022-01-10 14:05
> I don't have access to that machine anymore, and gave up mining a couple years ago. Aside from those command line flags and options, I wonder know what to suggest.
> […](#)
> On Jan 9, 2022, at 10:35 AM, th3podfather ***@***.***> wrote: ﻿ On iMac Pro 10.13.3, Vega64 using precompiled 0.14-dev2 With no options = 7.4Mh/s With --cl-global-work 163840 --cl-local-work 128 = 20.9Mh/s on both kernels With --cl-global-work 163840 --cl-local-work 256 = 42Mh/s (both) On iMac 2017 10.3.2, RX580 using precompiled 0.14-dev2 With --cl-global-work 163840 --cl-local-work 128 = 21.2Mh/s (stable) With --cl-global-work 163840 --cl-local-work 200 = 32.78Mh/s (stable) With --cl-global-work 163840 --cl-local-work 256 = 224Mh/s (invalid, and process hung, took machine with it during reboot attempt) The 42 (Vega 64) and 32 (RX580) more closely match what is being reported on whattomine.com with special mods. @SirBryan any chance you are willing to assist me in optimizing for iMac Pro Vega 64? Im hitting 24-25MH and would love to reach 42 as you were. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.

I appreciate the response! Thank you and take it easy!
