### ISSUE TITLE
Miner keeps mining (wasting power) even when connection lost

### ISSUE THREAD

**Issue by madscientist159** [ethereum-mining/ethminer#734] opened 2018-02-12 21:09 UTC
When the pool connection goes down the miner should stop mining instead of wasting power.

**Comment by piotr-dobrogost** [comment] 2018-02-13 11:08
Duplicate of issue #707 which is a duplicate of issue #651 which is a duplicate of issue #632.
I suggest to choose one of these and close all others as duplicates.

**Comment by madscientist159** [comment] 2018-02-13 17:39
#632 is a different issue.  This issue is about stopping mining when the pool itself going down (bad connectivity), not about power wastage when the GPU crashes / fails.

**Comment by gashtal** [comment] 2018-02-15 04:01
> Duplicate of issue #707 which is a duplicate of issue #651 which is a duplicate of issue #632.
> I suggest to choose one of these and close all others as duplicates.

Actually none of those issue have anything to do with this ticket since those issues involve cases where ethminer is "pretending to mine while it is not" while this issue points to a case where ethminer "has failed to connect to the pool, but still keeps mining". I previously reported a similar observation in the following ticket:

https://github.com/ethereum-mining/ethminer/issues/672

ethminer really needs an exit option for cases involving internet or pool connectivity issues.

**Comment by mrbrendanhamm** [comment] 2018-02-24 13:40
I had the same issue with 0.13.0. Compiling the binaries myself seemed to fix the issue.

**Comment by DeadManWalkingTO** [comment] 2018-02-27 15:31
The issue have been fix.
I think this issue can be closed.

**Comment by madscientist159** [comment] 2018-02-27 19:12
@DeadManWalkingTO Do you have the GIT commit hash that fixes this issue?

**Comment by smurfy** [comment] 2018-02-27 19:14
It has'n fixed.  But reconnecting has been improved.

**Comment by madscientist159** [comment] 2018-02-27 19:17
@smurfy That doesn't help when the remote host goes down for maintenance or the Internet link fails (e.g. when someone's on a lousy cable connection and the link fails for 24-48 hours).  Why should they waste their power in these situations?

Anyway, just saying that this issue should not be closed until it is fixed.

**Comment by smurfy** [comment] 2018-02-27 19:21
Its not our choice. the problem currently is that stopping miner can crash ethminer. so its currently disabled

**Comment by madscientist159** [comment] 2018-02-27 19:24
@smurfy then a reasonable workaround would be an "exit-on-disconnect" flag, to allow people to script their own miner recovery if they consider wasting electricity more important than possibly needing to restart their rig when the link comes back up.

**Closed** 2018-03-01 06:33 UTC

**Comment by MariusVanDerWijden** [comment] 2018-03-01 06:34
@madscientist159 with https://github.com/ethereum-mining/ethminer/pull/757 I introduced the new parameter --exit which stops the miner whenever an error occured
