### ISSUE TITLE
graphics driver crash on stopping miner with VM running

### ISSUE THREAD

**Issue by willis936** [ethereum-mining/ethminer#81] opened 2017-06-28 14:50 UTC
ver: 0.11.0rc1
OS: Windows 8.1 64-bit
Driver: 382.53
Primary GPU: 1060
Secondary GPU: 1070

When running individual CUDA instances of the miner for each card the graphics driver crashes when stopping (either with ctrl+c or closing the window) the miner on the primary GPU when a virtualbox VM is also running (either windows or linux client OS, with or without 2D acceleration).  Windows error log shows an openGL error from virtualbox.exe.

I'm not sure if this is related but the CUDA device indexing is backwards from PCIe and nvidia driver adapter indexing.  This was the case even across a fresh driver install.
The 1060 is on PCIe lane 1 and is nvidia adapter 0 but is CUDA device 1.
The 1070 is on PCIe lane 5 and is nvidia adapter 1 but is CUDA device 0.

I was able to recreate this while VMs were paused so it may not be related to virtualbox.

**Comment by JHGitty** [comment] 2017-07-06 00:37
1. Please try newest nvidia driver (version 384 is released).
2. Please try newest miner version (version 0.11.0 is released).
3. Please try it again with zero overclocking of any GPU.

**Comment by willis936** [comment] 2017-07-06 05:46
The crash still occurs on driver version 384.76, miner version 0.11.0 (not just RC1), and with stock OC settings on all GPUs.

**Comment by JHGitty** [comment] 2017-07-06 18:24
As I understand the issue only happens if you run a virtual machine on the "miner machine". So all in all I don't know how we can find out the issue here. It might be a misbehaviour of the hypervisor. I don't know.

@chfast This sounds to me as a "not a bug on our miner" or "won't fix" situation, what do you think?

**Comment by willis936** [comment] 2017-07-06 18:34
I have confirmed that the crash still occurs when no VMs, services, or executables related to virtualbox are running.  I originally thought it was related to virtualbox because that program logged an error but I am convinced that it wasn't the cause.  My best guess is that it has to do with the backwards PCIe/GPU indexing.  Is there any more contextual information I can give or tests I can do?

**Comment by willis936** [comment] 2017-07-06 23:14
If it's any help here is the motherboard and CPU.

EP2C602-4L/D16
2x E5-2697 v2

**Comment by willis936** [comment] 2017-09-07 12:35
I am no longer observing this issue on 0.12.0rc1.

**Comment by derubm** [comment] 2017-09-07 19:26
so, close it ?

**Comment by DeadManWalkingTO** [comment] 2018-02-27 23:18
GTX1060 +150/+500/65%TDP @ 23-24MHs

1. Try Update Drivers.
Download and install the latests.

2. Try Update Ethminer.
Download (or beter build) the latest.

3. Try use -U for CUDA devices.
CUDA Hardware Test Launch Command:
`ethminer -RH -U -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x7013275311fc37ccc1e40193D75086293eCb43A4.test`

4. Try to change P2 State and Power managment mode.
You can use [NVidiaProfileInspectorDmW](https://github.com/DeadManWalkingTO/NVidiaProfileInspectorDmW).
For the best mining hashrate choose from sector "5 - Common":
    - CUDA - Force P2 State (Set to "Off")
    - Power managment mode (Set to "Prefer maximum performance")

5. Try Tweak Win10.
You can use [Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW) (#695).

6. Try Optimize/Overclock GPUs. 
You can use [MSI Afterburner](https://www.msi.com/page/afterburner) for GPU OverClock/Optimize. 

7. Try use a WatchDog
You can use [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) (#735).

Please feedback.
Thank you!

**Comment by fuiru** [comment] 2018-02-28 03:52
Not sure if the same issue exactly, but I see this (display driver dying/recovering) frequently when stopping the miner with Ctrl+C. Occasionally, it'll be so bad that later restarting the miner gives CUDA errors, requiring me to restart my system.

ethminer version 0.13.0
Build: Windows/msvc/Release
Win 7 64
NVidia 1050 Ti
driver 388.13

I suspect that, since signal()'s handler never sees SIGINT or SIGTERM on Windows, Ctrl+C is not allowing it to shutdown cleanly. Might be helpful if there's a clean way to shutdown to compare.

**Comment by DeadManWalkingTO** [comment] 2018-02-28 03:55
@fuiru Try latest version and feedback please.
Thank you!

**Comment by fuiru** [comment] 2018-03-01 05:05
14dev2 I see cleanly shuts down on Ctrl+C, and doesn't seem to be causing any issues so far.

**Closed** 2018-03-01 06:37 UTC
