### ISSUE TITLE
Mining with RX570 4GB is giving unpredictible ethermine dashboard hashrade

### ISSUE THREAD

**Issue by darena67** [ethereum-mining/ethminer#2079] opened 2020-11-16 19:00 UTC
**Describe the bug**
Basically my ethermine dashboard reports that my cl0 rx570 4gb is not mining. I see that in the beginning of ethminer's output but later it start showing 42Ghsh/s output.

i 13:37:59 ethminer Spinning up miners...
cl 13:37:59 cl-0     Using Device : 01:00.0 gfx803 OpenCL 1.2  Memory : 4.00 GB (4294967296 B)
 i 13:37:59 cl-0     Adjusting CL work multiplier for 32 CUs. Adjusted work multiplier: 58,255
cu 13:37:59 cuda-1   Using Pci Id : 03:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.82 GB
 i 13:38:00 ethminer Extranonce set to 9373
cu 13:38:00 cuda-2   Using Pci Id : 04:00.0 GeForce GTX 1070 (Compute 6.1) Memory : 7.82 GB
 i 13:38:00 ethminer Authorized worker 0xFf1eB0a5883896975648856F91c47D99d4F00D47.richbitch
 i 13:38:00 ethminer Epoch : 375 Difficulty : 4.29 Gh
 i 13:38:00 ethminer Job: 55338450… us2.ethermine.org [172.65.226.101:5555]
cl 13:38:02 cl-0     Generating split DAG + Light (total): 3.93 GB
 i 13:38:02 ethminer Job: 842f671a… us2.ethermine.org [172.65.226.101:5555]
cu 13:38:02 cuda-1   Generating DAG + Light(on GPU) : 3.99 GB
cu 13:38:02 cuda-2   Generating DAG + Light(on GPU) : 3.99 GB
cl 13:38:03 cl-0     OpenCL kernel
cl 13:38:03 cl-0     Loading binary kernel /home/vladi/ethminer/build/ethminer/kernels/ethash_gfx803_lws128_exit.bin
 X 13:38:03 cl-0     Failed to load binary kernel: /home/vladi/ethminer/build/ethminer/kernels/ethash_gfx803_lws128_exit.bin
 X 13:38:03 cl-0     Falling back to OpenCL kernel...
cl 13:38:03 cl-0     Creating DAG buffer, size: 3.93 GB, free: 72.01 MB
cl 13:38:03 cl-0     Creating light cache buffer, size: 62.87 MB
cl 13:38:03 cl-0     Loading kernels
cl 13:38:03 cl-0     Creating buffer for header.
cl 13:38:03 cl-0     Creating mining buffer
...
 i 13:56:01 ethminer Job: 6b41cce1… us2.ethermine.org [172.65.226.101:5555]
 m 13:56:04 ethminer 0:18 A13 53.52 Mh - cl0 0.00, cu1 26.79, cu2 26.73
 i 13:56:05 ethminer Job: a53f73c1… us2.ethermine.org [172.65.226.101:5555]
 i 13:56:05 ethminer Job: 3f811542… us2.ethermine.org [172.65.226.101:5555]
 m 13:56:09 ethminer 0:18 A13 53.47 Mh - cl0 0.00, cu1 26.74, cu2 26.73
 i 13:56:09 ethminer Job: b4dad467… us2.ethermine.org [172.65.226.101:5555]
...
 m 14:57:04 ethminer 1:19 A59 76.22 Mh - cl0 22.72, cu1 26.79, cu2 26.71
 i 14:57:07 ethminer Job: 9b0d2824… us2.ethermine.org [172.65.226.101:5555]
 m 14:57:09 ethminer 1:19 A59 76.21 Mh - cl0 22.75, cu1 26.73, cu2 26.73
 i 14:57:11 ethminer Job: 82ef4f12… us2.ethermine.org [172.65.226.101:5555]
 m 14:57:14 ethminer 1:19 A59 76.26 Mh - cl0 22.74, cu1 26.79, cu2 26.73
 i 14:57:15 ethminer Job: 07235220… us2.ethermine.org [172.65.226.101:5555]
 i 14:57:19 ethminer Job: 82c5b502… us2.ethermine.org [172.65.226.101:5555]
 m 14:57:19 ethminer 1:19 A59 76.25 Mh - cl0 22.74, cu1 26.78, cu2 26.73

**To Reproduce**
start ./ethminer -P stratums://xxxxx@us2.ethermine.org:5555

**Expected behavior**
combined hashing power shows up on ethmine dashboard

**Environment (please complete the following information):**
- Operating System: Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-54-generic x86_64)
- Hardware 2 x GTX 1070 8GB + 1 RX 570 4GB
- Ethminer Version: ethminer 0.19.0-11+commit.d5f3a972
- Ethminer options used

**Additional context**
I am using rocm 3.9.1 with ethminer build from git

**Comment by AndreaLanfranchi** [comment] 2020-11-23 18:22
Seems not an issue to me (probably missing pieces of log).
Apparently is only takink more time than NVIDIA cards to build up the DAG.

**Comment by AndreaLanfranchi** [comment] 2020-11-23 19:31
Possibly related to #2066

**Comment by evilbulgarian** [comment] 2020-11-30 20:22
I am using rocm, and yeah ethermine dashboard is not reflecting what the output from ethminer is showing.

**Comment by AndreaLanfranchi** [comment] 2020-11-30 21:07
Are you aware of the difference amongst computed hashrate and effective hashrate ?

**Comment by evilbulgarian** [comment] 2020-11-30 22:01
Yup, but this is huge drops equivalent to what my 4GB card is capable of. So as an example ethminer is showing my card mining at 23Mh but ethermine dashboard is showing 0.

**Comment by AndreaLanfranchi** [comment] 2020-11-30 23:32
Showing zero for what ? 
Reported hashrate or current hashrate ?
If the first you're not reporting (i.e. missing -R cli argument). If the latter check your find solutions: if they are zero then is normal ethermine says your current hashrate is zero

**Comment by darena67** [comment] 2020-12-01 21:50
![image](https://user-images.githubusercontent.com/70442640/100800973-303c1e00-33dc-11eb-95e3-ad5a7896dacc.png)

this is the dashboard vs this in the ethminer logs:
 m 16:48:00 ethminer 28:24 A1814:R4 76.06 Mh - cl0 22.70, cu1 26.63, cu2 26.73
 i 16:48:04 ethminer Job: 6144a618… us2.ethermine.org [172.65.226.101:5555]
 m 16:48:05 ethminer 28:24 A1814:R4 76.04 Mh - cl0 22.69, cu1 26.62, cu2 26.73
 i 16:48:06 ethminer Job: 9d3919fd… us2.ethermine.org [172.65.226.101:5555]
 i 16:48:06 ethminer Job: 1468c7e1… us2.ethermine.org [172.65.226.101:5555]
 i 16:48:10 ethminer Job: 427a5cbc… us2.ethermine.org [172.65.226.101:5555]
 m 16:48:10 ethminer 28:24 A1814:R4 76.01 Mh - cl0 22.70, cu1 26.57, cu2 26.73
 i 16:48:14 ethminer Job: 8b831276… us2.ethermine.org [172.65.226.101:5555]
 m 16:48:15 ethminer 28:24 A1814:R4 76.05 Mh - cl0 22.70, cu1 26.62, cu2 26.72
 i 16:48:17 ethminer Job: e2c49791… us2.ethermine.org [172.65.226.101:5555]
 i 16:48:17 ethminer Job: 6830a33a… us2.ethermine.org [172.65.226.101:5555]
 m 16:48:20 ethminer 28:24 A1814:R4 76.05 Mh - cl0 22.69, cu1 26.63, cu2 26.73
 i 16:48:21 ethminer Job: 13ecd3a7… us2.ethermine.org [172.65.226.101:5555]
 m 16:48:25 ethminer 28:24 A1814:R4 76.04 Mh - cl0 22.69, cu1 26.62, cu2 26.73
 i 16:48:25 ethminer Job: 06184483… us2.ethermine.org [172.65.226.101:5555]
 i 16:48:29 ethminer Job: 6dda49bf… us2.ethermine.org [172.65.226.101:5555]
 m 16:48:30 ethminer 28:24 A1814:R4 76.05 Mh - cl0 22.69, cu1 26.63, cu2 26.73

**Comment by AndreaLanfranchi** [comment] 2020-12-09 14:32
Everything seems pretty normal to me. Analyzing the topmost graph :
- Computed average hashrate (orange line) is ok
- Instant computed hashrate (blue line) is ok

What is actually missing is your reported hashrate (generally a green line on ethermine.org) but this might be caused by one of the following:

- either you have not set `-R` on command line which starts ethminer
- or you're communicating with ethermine.org on simple stratum protocol (which does not support signalling hashrate)

Change your command line to 
`ethminer -R -P stratum1+ssl://<your-address>.<your-worker>@us2.ethermine.org:55555`
and you will see your reported hashrate.

I see no other issues here.
Closing

**Closed by AndreaLanfranchi** 2020-12-09 14:32 UTC

**Comment by evilbulgarian** [comment] 2020-12-11 02:48
@AndreaLanfranchi thanks for the help! I did add -R and it is reporting now just seems weird that my hash rate went down after DAG went above 4GB. Thanks again!
