### ISSUE TITLE
the pool is regularly disconnected

### ISSUE THREAD

**Issue by Zaqsnaider** [ethereum-mining/ethminer#1539] opened 2018-09-04 08:07 UTC
Hello. 
I'm using the version ethminer-0.16.0rc1 and windows10. And I have the same problem of regular disconnects and rejects on etp coin - dodopool or metaverse.farm. I run the following bat file:

@echo off
timeout /t 45
:bg
ethminer -U -P stratum://WALLET.NAME:x@nl.metaverse.farm:3002 --exit --tstop 72 --tstart 45 --noeval
timeout /t 10
goto :bg

![default](https://user-images.githubusercontent.com/42960166/45018263-54102e00-b032-11e8-8b97-d387680aa075.jpg)

Thanks.

**Comment by AndreaLanfranchi** [comment] 2018-09-04 09:13
Actually this problem has nothing to do with ethminer.
You see "Connection remotely closed by" ... ?

This can be caused by any of these :

1. Poor internet connection
2. Absence of static public IP address on your internet connection (your IP gets changed)
3. Aggressive behavior of your router/firewall which prematurely detects idle connections
4. Problem on pool's side which abruptly closes connections

**Comment by Zaqsnaider** [comment] 2018-09-04 09:47
Thank you for your prompt reply. I have been mining for a long time. I like Ethminer very much and I would like to use it always. I would not ask such question - as other miner gives out approximately on 2000 decisions only 4 rejekts and the hashrate on a pool corresponds. While ethminer receives a regular discount and dozens of rejects-on 2000 solutions about 20 rejects.
By your answer:
1. Internet connection was not lost.
2. I have a static Internet address and it's fine, too.
3. This refutes the behavior of another miner.
4. Here I can say that I tried three pools - (dodo, sand and farm) and everywhere the same behavior, and on ETC and ETH this was not. ETP I started mining only recently.
I would like to send a screen with another miner on the same machine where everything is in order later.
What do you advise to do to narrow down the cause of the problem? It may be possible to make a debug log - if explain how.
Thanks.

**Comment by AndreaLanfranchi** [comment] 2018-09-04 09:57
The cause of rejects have to be investigated.
I see you have set the cli argument `--noeval` which prevents the CPU to re-validate solution found by GPU.
I'd suggest to remove it temporarily and run a batch of 4~6 hours.
If you see several messages about GPU giving incorrect result then it's likely you're overclocking too much. **Please note OC values are not universal** : what is fine for another miner might be too much for ethminer or vice versa (all miners implement very different ways to invoke GPU work).

**Comment by Zaqsnaider** [comment] 2018-09-04 13:06
I send a screen of another miner-a few hours everything is fine.
![phoenix](https://user-images.githubusercontent.com/42960166/45032994-deb95300-b05b-11e8-9076-fd053e96500d.jpg)

And immediately launched ethminer. Immediately visible problems. Acceleration and --noeval removed completely.
![ethmine_1](https://user-images.githubusercontent.com/42960166/45033077-2213c180-b05c-11e8-81b6-c9f53138a934.jpg)
![ethmine_2](https://user-images.githubusercontent.com/42960166/45033081-250eb200-b05c-11e8-9255-0c0efd914da1.jpg)
![ethmine_3](https://user-images.githubusercontent.com/42960166/45033088-2809a280-b05c-11e8-99c7-0183bfa277fc.jpg)
![ethmine_4](https://user-images.githubusercontent.com/42960166/45033093-2a6bfc80-b05c-11e8-922c-c6d97337ee47.jpg)

Is it possible that the pool accepts ethminer or something else as an attack and disconnects?

**Comment by AndreaLanfranchi** [comment] 2018-09-04 13:20
> Is it possible that the pool accepts ethminer or something else as an attack and disconnects?

Highly unlikely
Will try to run a batch now

**Comment by Zaqsnaider** [comment] 2018-09-04 15:56
For much time this was the first such strange case. I am very grateful for your help. I'll contact pool support.

**Comment by Zaqsnaider** [comment] 2018-09-04 16:31
Another farm 4*588+1*578 shows a record of stability.
ethminer 0.16.0rc1 and win10
ethminer -G -P stratum://WALLET.Name:x@nl.metaverse.farm:3004 --exit --tstop 72 --tstart 40
![extra](https://user-images.githubusercontent.com/42960166/45044561-21d5ef00-b079-11e8-97f8-cb771bb26f73.jpg)

**Comment by Zaqsnaider** [comment] 2018-09-04 16:32
Sorry - 4*rx588+1*rx578

**Comment by Zaqsnaider** [comment] 2018-09-04 16:35
Still I will tell that on other farms with such problem there are only Nvidia.

**Comment by chfast** [comment] 2018-09-06 23:35
Two comments:
1. If we drop the connection because of inactivity, maybe the log message should be other than "Connection remotely closed".
2. Can we increase the default value for --work-timeout?

**Comment by jean-m-cyr** [comment] 2018-09-07 01:08
Why would changing --response-timmeout or --work-timeout cause a "connection remotely closed" to disappear? I think that error message comes from the stack, so I don't see how client side timeouts would be the cause!

**Comment by chfast** [comment] 2018-09-07 10:12
@jean-m-cyr The issue has been resolved by increasing some timeouts, see https://github.com/ethereum-mining/ethminer/issues/1539#issuecomment-419228315.

I'm guessing that when one of the timeout is hit, the ethminer disconnects from the pool. If I'm right, then the log message "connection remotely closed" is incorrect and users don't have a clue how to solve the problem. It would be much easier if the log said "disconnected from pool because of inactivity (response timeout)". 

I'm also wander if increasing the default value have any impact on the overall performance. If not we could increase them to make ethminer work with default values in this case.

**Comment by AndreaLanfranchi** [comment] 2018-09-07 10:38
I do not agree.
Actually I see in the thread a couple of misunderstandings.

1. `Connection remotely closed by ...` have nothing to do with any value of timeout we can set. This is catched by a very specific condition `if (ec == boost::asio::error::eof)` which is a clear declaration the remote party have sent an "End of transmission".

2. Every time we hit a timeout we output the proper log message like `No response in ...`

I strongly believe the problem depicted on this thread is strictly related to the weakness of the pool which (I am only guessing) has suboptimal load balancing techniques or faulty pool implementation.

All tests on Rate A pools have never depicted such a situation.

**Comment by AndreaLanfranchi** [comment] 2018-09-07 10:40
The increase of timeouts, IMHO, has produced some effects only **coincidentally**

**Comment by AndreaLanfranchi** [comment] 2018-09-07 10:42
As @jean-m-cyr correctly underlined ... if the disconnection was on our side boost would have returned the "Operation Aborted" error code which is also trapped with a different output message.

**Comment by AndreaLanfranchi** [comment] 2018-09-07 10:57
> I'm also wander if increasing the default value have any impact on the overall performance. If not we could increase them to make ethminer work with default values in this case.

No it does not affect ethminer performance in any way. Only problem you **may** stay connected longer on a non-responsive pool.

**Comment by AndreaLanfranchi** [comment] 2018-09-22 16:52
@urpils and other.

Opening post for this thread depicts connection on port 3002 which causes problems.

This said if this statement by you is true 

> the disconnects are exactly 60 seconds after last job send AND no solution found. So it is a pool decision for disconnecting "inactive" clients

the pool is behaving **pretty badly**. As MTP has a block time of 24 seconds (avg) in 60 seconds the POOL should send at least 2~3 jobs. If it doesn't and it computes the missing jobs as _idle time_ ... well blame pool maintainers ... not ethminer.

**Comment by AndreaLanfranchi** [comment] 2018-09-22 16:53
Closing

**Closed by AndreaLanfranchi** 2018-09-22 16:53 UTC
