### ISSUE TITLE
Latest master does not configure 

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#836] opened 2018-03-02 15:19 UTC
```
prospector@miner01:~/ethereum-mining/ethminer2/build $ sudo cmake -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 -DAPICORE=ON -DETHASHCUDA=ON -DETHASHCL=OFF -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-9.1 -DCOMPUTE=61 ..
CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    cmake/cable/bootstrap.cmake


CMake Error at CMakeLists.txt:5 (include):
  include could not find load file:

    CableBuildInfo


CMake Error at CMakeLists.txt:6 (include):
  include could not find load file:

    CableBuildType


CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    CableToolchains


CMake Error at CMakeLists.txt:9 (cable_configure_toolchain):
  Unknown CMake command "cable_configure_toolchain".


-- Configuring incomplete, errors occurred!

```

**Comment by piotr-dobrogost** [comment] 2018-03-02 15:55
Duplicate of issue #816

**Closed** 2018-03-02 16:03 UTC
