### ISSUE TITLE
Nicehash JsonRpcException error

### ISSUE THREAD

**Issue by oleng** [ethereum-mining/ethminer#167] opened 2017-07-19 00:24 UTC
I get this error on build 0.11.0 & latest dev 0.12.0 build, binary downloads, when trying to mine on nicehash.

```
d:\_miners\ethminer-0.11.0\ethminer.exe -SP 2 --farm-recheck 200 -v 9 -U -FS daggerhashimoto.hk.nicehash.com:3353 -O xxx <redacted>

  m  07:08:35|main  Getting work package...   
  X  07:08:37|main  Failed to submit hashrate.   
  X  07:08:37|main  Dynamic exception type: class jsonrpc::JsonRpcException   
std::exception::what: Exception -32003 : Client connector error: libcurl error: 7 -> Could not connect to http://127.0.0.1:8545

JSON-RPC problem. Probably couldn't connect. Retrying in 1...
```

I don't recall this error on previous builds. Is it on my system? I doubt it though, didn't reinstall OS or change much between 0.11.0dev and now, only drivers. I also connected without problems to other pools.

**Comment by chfast** [comment] 2017-07-19 15:41
Duplicate of #151.

**Closed by chfast** 2017-07-19 15:41 UTC

**Comment by oleng** [comment] 2017-07-20 14:42
i'd like to see this issue re-opened until it's confirmed there is a fix.
