### ISSUE TITLE
ethminer doesn't start anymore (AMD)

### ISSUE THREAD

**Issue by nerle** [ethereum-mining/ethminer#1152] opened 2018-05-25 05:46 UTC
Hi,

I think the last Windows update caused the problem but I didn't find an solution by myself. I changed nothing than the Windows patch (forced from Windows). If I start ethminer:

c:\ethminer\bin\ethminer -G -M --cl-local-work 256 --cl-global-work 18432 --cl-parallel-hash 2 --cl-kernel 1 --opencl-platform 1 -S europe.ethash-hub.miningpoolhub.com:20535 -O xxx.ethminer:password

The exe simply ends with no error message. What could I do?

Best regards and thanks in advance!
Dirk

**Comment by Mycopka** [comment] 2018-05-25 06:12
Hi. no error, no problem ( joke:) ). 

Try to up verbosity level, to see what's happend (option -v 9).

**Comment by AndreaLanfranchi** [comment] 2018-05-25 09:48
@nerle 
quite likely you're using a .bat file which exits immediately after miner stops. So you do not see the errors which are, surely, there.

For instance, if you're using latest builds, ethminer will complain about old command line arguments which are not supported anymore.

In fact this

`-S europe.ethash-hub.miningpoolhub.com:20535 -O xxx.ethminer:password`

have to be translated into this

-P stratum+tcp://xxx.ethminer:password@europe.ethash-hub.miningpoolhub.com:20535

**Comment by divinity76** [comment] 2018-05-25 09:51
if the problem is indeed running a .bat file that close the terminal after ethminer exits, write "pause" right after the ethminer command, and you should be able to see the errors

**Comment by nerle** [comment] 2018-05-25 10:05
THX in advance, I use a .bat and tried the suggested new parameter with -P instead -S like Andrea suggested. Now I get the following error.

Mixed stratum and getwork endpoints not supported.
Error: Unknown exception

**Comment by divinity76** [comment] 2018-05-25 10:28
@nerle did you figure it out? (curious why you closed it)

**Comment by nerle** [comment] 2018-05-25 11:13
No I didn't find a solution yet and closed by accident :(

**Comment by AndreaLanfranchi** [comment] 2018-05-25 11:15
That is because you're asking for **benchmarking** mode (-M) which is incompatible with pool direct mining.

Remove -M and start mining.

**Comment by nerle** [comment] 2018-05-25 14:07
THX Andrea! I mined month with -M but no problem, I removed the switch. It dosen't work and no useful error message.

C:\ethminer\bin\ethminer -G --cl-local-work 256 --cl-global-work 18432 --cl-parallel-hash 2 --cl-kernel 1 --opencl-platform 1 -P stratum+tcp://xxx.ethminer:password@europe.ethash-hub.miningpoolhub.com:20535 -v 9
  m  16:03:37|main    |  ethminer 0.15.0.dev11
  m  16:03:37|main    |  Build: windows / release
C:\

**Comment by nerle** [comment] 2018-05-26 16:42
Yes, Windows 10 with 4 GB RAM and 5xAMD 480 RX (MSI) with 8 GB RAM. Mining worked fine for months with ethminer. Because it's not working now, I'm using Multipoolminer currently and the rig is mining fine with MMP but not with ethminer.

**Comment by AndreaLanfranchi** [comment] 2018-05-26 17:37
Have you tried to start ethminer with 1 gpu only, then 2, then 3 and so on ?

**Comment by nerle** [comment] 2018-05-27 10:01
Return code is 1 after ethminer exit, the same happened with using one GPU after another and all GPU are working fine with Multipoolminer.

**Comment by AndreaLanfranchi** [comment] 2018-05-27 10:17
Please retry **removing** the following

`--cl-local-work 256 --cl-global-work 18432 --cl-parallel-hash 2 --cl-kernel 1`

**Comment by AndreaLanfranchi** [comment] 2018-05-27 10:18
And also 

`--opencl-platform 1 `

**Comment by AndreaLanfranchi** [comment] 2018-05-27 10:19
Apparently exit code 1 is due to the fact ethminer either does not detect OpenCL platform correctly or it detects Platform 0 but you impose platform 1

**Comment by nerle** [comment] 2018-05-27 12:11
removing --opencl-platform 1 worked, ethminer is starting now.

BUT the hash dropped from 133MH/s to 72 MH/s. I don't understand that, I worked with the parameters from the beginning with ethminer and tried every single dev version and since v15 I have these problems. 

With MMP I have still 133MH/s with the rig.

**Comment by divinity76** [comment] 2018-05-27 13:05
@nerle what's MMP?

**Comment by nerle** [comment] 2018-05-27 13:11
Multipoolminer - I use it to mine until I get ethminer working again. ethminer worked most stable for me the last months. So multipoolminer is just a workaround.

**Comment by RyanF109** [comment] 2018-06-02 02:47
I had a similar issue and had to revert back to the release version. It would report my attached GPU's then quit without warning. Unsure if this issue has been resolved or not since it was around 3 weeks ago.

**Comment by nerle** [comment] 2018-06-02 11:04
no, its not solved yet.

**Comment by AndreaLanfranchi** [comment] 2018-06-03 09:13
@all please read this

https://github.com/ethereum-mining/ethminer/issues/1165#issuecomment-394129880

**Comment by nerle** [comment] 2018-06-08 13:12
Didn't helped in no way. Claymore is mining stable since a week now.

**Comment by ddobreff** [comment] 2018-06-27 00:01
I suspect your GPUs are in a way throttling, maybe because opencl takes more power or because you haven't specified correct --cl params, you may want to try just --cl-local-work 256 --cl-parallel-hash 2 and leave global-work autoadjusted(did Jean include this in ethminer?), else set global-work a bit lower lets say 16384

**Comment by AndreaLanfranchi** [comment] 2018-09-19 15:48
No feed back.
Closing

**Closed by AndreaLanfranchi** 2018-09-19 15:48 UTC
Labels: invalid
