### ISSUE TITLE
Ubuntu 16, after several days of mining got error

### ISSUE THREAD

**Issue by vladimircape** [ethereum-mining/ethminer#411] opened 2017-11-30 21:14 UTC
```
06:43:44|ethminer  Speed  93.78 Mh/s    gpu/0 22.80  gpu/1 23.76  gpu/2 23.66  gpu/3 23.56  [A10810+58:R0+1:F0] Time: 127:40
  ℹ  06:43:45|stratum   Received new job #e648039c
  ℹ  06:43:45|CUDA0     set work; seed: #4be89018, target:  #0000000112e0
  ℹ  06:43:45|CUDA1     set work; seed: #4be89018, target:  #0000000112e0
  ℹ  06:43:45|CUDA2     set work; seed: #4be89018, target:  #0000000112e0
  ℹ  06:43:45|CUDA3     set work; seed: #4be89018, target:  #0000000112e0
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 4) >= this->size() (which is 4)
Aborted (core dumped)
```

**Comment by smurfy** [comment] 2017-12-01 07:17
yea, that sometimes happens. its a known problem.
Dupe of #366

**Closed by smurfy** 2017-12-01 07:17 UTC
