### ISSUE TITLE
Submit hashRate failed : code:-32601 message:Method not found 

### ISSUE THREAD

**Issue by stone212** [ethereum-mining/ethminer#1887] opened 2019-05-09 11:09 UTC
**Describe the bug**
Using ethminer 0.18 and Parity 2.3.9 in stratum mode, ethminer shows `0.00` hash and `Submit hashRate failed : code:-32601 message:Method not found`

**To Reproduce**
1. Install Parity 2.3.9 and start with unlocked account and `[stratum]` enabled
2. Start ethminer with `/opt/ethminer/bin/ethminer -R -G -P stratum+tcp://127.0.0.1:8008`

```
i 04:01:41 ethminer Stratum mode : STRATUM
 i 04:01:41 ethminer Subscribed!
 i 04:01:41 ethminer Authorized worker 
 m 04:01:46 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 04:01:51 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 04:01:56 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 04:02:01 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 04:02:06 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 04:02:11 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 04:02:16 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 04:02:21 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 04:02:26 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 04:02:31 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 m 04:02:36 ethminer 0:00 A0 0.00 h { cl0 0.00 | cl1 0.00 }
 X 04:02:41 ethminer Submit hashRate failed : code:-32601 message:Method not found 
```

**Expected behavior**
I expect to see a number like `51` instead of `0` for hash rate and not to see Method not found

**Environment (please complete the following information):**
- Operating System: Ubuntu 18.04
- Hardware [AMD RX 480 with amdgpu-pro drivers
- Ethminer Version  0.18
- Ethminer options used -R -G -P

**Additional context**

See that it does subscribe so I think the problem is not the connection to Parity.

If I start ethminer with `stratum1+tcp` it gives the `32601` error and exits.

https://github.com/ethereum-mining/ethminer/issues/1763

**Comment by AndreaLanfranchi** [comment] 2019-05-09 11:39
Two problems here 
- Parity (as well as geth) are nodes (not pools) thus they're not meant to collect hashrate from miners. You have to remove `-R` from your start-up command line
- The fact ethminer is not mining is due to Parity not dispatching mining jobs. Due to this I assume parity node is not fully synchronized. Full sync is mandatory before any mining job gets dispatched.

**Comment by AndreaLanfranchi** [comment] 2019-05-22 07:23
No feed back. Closing.

**Comment by stone212** [comment] 2019-05-23 09:13
@AndreaLanfranchi 

> No feed back. Closing.

You are an impatient little guy aren't you?  I have 150 other servers I'm working on, and I don't work on your schedule.  But I am helping you make a better product by writing and de-bugging issues.

> Parity (as well as geth) are nodes (not pools) thus they're not meant to collect hashrate from miners. You have to remove -R from your start-up command line

Done, thank you.

> Full sync is mandatory before any mining job gets dispatched.

Parity is fully synced.  It's a private blockchain.  I can run more tests if you want.  And note it may take me a week or three to respond.

**Comment by AndreaLanfranchi** [comment] 2019-05-23 11:53
> You are an impatient little guy aren't you? 

You should be more careful with statements like that. I don't work on your schedule either.
Issue reopened.

Hopefully someone else will take care of (but apparently this space is slowly dying).
Good luck.

**Comment by stone212** [comment] 2019-05-28 01:04
> You should be more careful with statements like that.

Shut up.  You sound like a little child. 

> I don't work on your schedule either.

No one said that you did.  I didn't even ask you to reply in the first place.  You have not said anything useful.

**Comment by Spudz76** [comment] 2019-06-20 20:00
Wow someone wants to get banned.
Try less vinegar or you're going to turn into a pickle.

**Comment by Spudz76** [comment] 2019-06-20 20:00
Also looks like nobody is going to help you, good attitude!

**Comment by Spudz76** [comment] 2019-06-20 20:51
Reported to GitHub as abusive, after reviewing posts in other projects which were also very anger-filled
Also blocked, seeya!

**Comment by AndreaLanfranchi** [comment] 2019-06-26 08:20
Title of issue is not related to ethminer.
Closing.

**Closed by AndreaLanfranchi** 2019-06-26 08:20 UTC

**Comment by stone212** [comment] 2019-06-26 08:32
@AndreaLanfranchi Actually the title is related to ethminer.  The title is an error message produced by ethminer.

**Comment by smurfy** [comment] 2019-06-26 08:35
Error is shown by ethminer, but produced by parity, because it does not supported by it.
As you confirmed issue is solved by removing ``-R``, consider this issue as resolved.

**Comment by stone212** [comment] 2019-06-26 08:44
@smurfy I tested now and you are correct.  Agree this is resolved.

**Comment by Spudz76** [comment] 2019-06-26 17:07
And also, Parity people seem like they either haven't heard of the report-hashrate extension of Stratum, or are avoiding supporting it on purpose.
[parity-ethereum #5807](https://github.com/paritytech/parity-ethereum/issues/5807)
