### ISSUE TITLE
Darwin version doesn't work :(

### ISSUE THREAD

**Issue by Dauphin38** [ethereum-mining/ethminer#633] opened 2018-01-26 20:19 UTC
I launch the darwin ethminer with the terminal, I have this for example :
---
Dauphin-iMac-2:~ dauphin$ /Users/dauphin/Downloads/bin/ethminer --farm-recheck 200 -G -S eu1.ethermine.org:4444 -FS us1.ethermine.org:4444 -O 0x5d88100881a7a171268a1aff2b19484057b94c13.dauphin
  ℹ  21:07:28|          Found suitable OpenCL device [ AMD Radeon Pro 570 Compute Engine ] with 4294967296  bytes of GPU memory
  ℹ  21:07:28|          Connecting to stratum server eu1.ethermine.org:4444
Could not resolve host eu1.ethermine.org:4444, Operation canceled  ℹ  21:07:28|          Reconnecting in 3 seconds...
  ℹ  21:07:31|          Connecting to stratum server eu1.ethermine.org:4444
  ℹ  21:07:31|stratum   Connected to stratum server eu1.ethermine.org : 4444
  ℹ  21:07:31|stratum   Starting farm
 cl  21:07:31|cl-0      No work. Pause for 3 s.
  ℹ  21:07:31|stratum   Subscribed to stratum server
  ℹ  21:07:31|stratum   Authorized worker 0x5d88100881a7a171268a1aff2b19484057b94c13.dauphin
  ℹ  21:07:31|stratum   Received new job #db008552
  m  21:07:31|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:31|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:31|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:31|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:32|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:32|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:32|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:32|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:33|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:33|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:33|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:33|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:33|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:34|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  21:07:34|cl-0      New work: header #db008552… target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  21:07:34|cl-0      New seed #51e74ac0…
  m  21:07:34|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:34|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:34|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:34|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:35|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:35|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:35|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  21:07:35|cl-0      Platform: Apple
 cl  21:07:35|cl-0      Device:   AMD Radeon Pro 570 Compute Engine  / OpenCL 1.2 
  m  21:07:35|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:35|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 cl  21:07:35|cl-0      Build info: <program source>:329:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~
<program source>:364:9: warning: comparison of integers of different signs: 'int' and 'const uint' (aka 'const unsigned int')
                if (i == thread_id)
      ~ ^  ~~~~~~~~~

 cl  21:07:35|cl-0      Creating light cache buffer, size 38403392
 cl  21:07:35|cl-0      Creating DAG buffer, size 2457861248
 cl  21:07:35|cl-0      Loading kernels
 cl  21:07:35|cl-0      Writing light cache buffer
 cl  21:07:35|cl-0      Creating buffer for header.
 cl  21:07:35|cl-0      Creating mining buffer
 cl  21:07:35|cl-0      Generating DAG
 cl  21:07:35|cl-0      DAG 0 %
 cl  21:07:35|cl-0      DAG 2 %
 cl  21:07:35|cl-0      DAG 5 %
 cl  21:07:35|cl-0      DAG 8 %
 cl  21:07:35|cl-0      DAG 10 %
 cl  21:07:35|cl-0      DAG 13 %
 cl  21:07:35|cl-0      DAG 16 %
 cl  21:07:35|cl-0      DAG 18 %
 cl  21:07:35|cl-0      DAG 21 %
 cl  21:07:35|cl-0      DAG 24 %
 cl  21:07:35|cl-0      DAG 27 %
 cl  21:07:35|cl-0      DAG 29 %
 cl  21:07:35|cl-0      DAG 32 %
 cl  21:07:35|cl-0      DAG 35 %
 cl  21:07:35|cl-0      DAG 37 %
 cl  21:07:35|cl-0      DAG 40 %
 cl  21:07:35|cl-0      DAG 43 %
 cl  21:07:35|cl-0      DAG 45 %
 cl  21:07:35|cl-0      DAG 48 %
 cl  21:07:35|cl-0      DAG 51 %
 cl  21:07:35|cl-0      DAG 54 %
 cl  21:07:35|cl-0      DAG 56 %
 cl  21:07:35|cl-0      DAG 59 %
 cl  21:07:35|cl-0      DAG 62 %
 cl  21:07:35|cl-0      DAG 64 %
 cl  21:07:35|cl-0      DAG 67 %
 cl  21:07:35|cl-0      DAG 70 %
 cl  21:07:35|cl-0      DAG 72 %
 cl  21:07:35|cl-0      DAG 75 %
 cl  21:07:35|cl-0      DAG 78 %
 cl  21:07:35|cl-0      DAG 81 %
 cl  21:07:35|cl-0      DAG 83 %
 cl  21:07:35|cl-0      DAG 86 %
 cl  21:07:35|cl-0      DAG 89 %
 cl  21:07:35|cl-0      DAG 91 %
 cl  21:07:35|cl-0      DAG 94 %
 cl  21:07:35|cl-0      DAG 97 %
 cl  21:07:35|cl-0      Switch time 4759 ms / 1814923 us
  m  21:07:36|          Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:36|          Speed 2139.14 Mh/s    gpu/0 2139.14  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:36|          Speed 2139.14 Mh/s    gpu/0 2139.14  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:36|          Speed 2139.14 Mh/s    gpu/0 2139.14  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:36|          Speed 2139.14 Mh/s    gpu/0 2139.14  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:37|          Speed 2139.14 Mh/s    gpu/0 2139.14  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:37|          Speed 6913.36 Mh/s    gpu/0 6913.36  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:37|          Speed 6913.36 Mh/s    gpu/0 6913.36  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:37|          Speed 6913.36 Mh/s    gpu/0 6913.36  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:37|          Speed 6913.36 Mh/s    gpu/0 6913.36  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:38|          Speed 6913.36 Mh/s    gpu/0 6913.36  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:38|          Speed 8488.29 Mh/s    gpu/0 8488.29  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:38|          Speed 8488.29 Mh/s    gpu/0 8488.29  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:38|          Speed 8488.29 Mh/s    gpu/0 8488.29  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:38|          Speed 8488.29 Mh/s    gpu/0 8488.29  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:39|          Speed 8488.29 Mh/s    gpu/0 8488.29  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:39|          Speed 9272.43 Mh/s    gpu/0 9272.43  [A0+0:R0+0:F0] Time: 00:00
  ℹ  21:07:39|stratum   Received new job #4f199d56
 cl  21:07:39|cl-0      New work: header #4f199d56… target 0000000112e0be826d694b2e62d01511f12a6061fbaec8bc02357593e70e52ba
 cl  21:07:39|cl-0      Switch time 0 ms / 58 us
  m  21:07:39|          Speed 9328.52 Mh/s    gpu/0 9328.52  [A0+0:R0+0:F0] Time: 00:00
  m  21:07:39|          Speed 9328.52 Mh/s    gpu/0 9328.52  [A0+0:R0+0:F0] Time: 00:00
---
So I mean it's works. But not :( Nothing on the dashboard.
Ethermine see no worker no rate ... Nothing :(

Please help me

**Comment by kronem** [comment] 2018-01-27 02:24
If only that hash rate was real.   Wow!

**Comment by DeadManWalkingTO** [comment] 2018-02-27 17:47
Try latest version and feedback please.
Thank you!

**Comment by Dauphin38** [comment] 2018-03-02 16:47
it's the same :(

**Comment by melvyn2** [comment] 2018-03-05 15:03
Same thing for me.

**Comment by chfast** [comment] 2018-06-18 09:48
Duplicate of https://github.com/ethereum-mining/ethminer/issues/841

**Closed by chfast** 2018-06-18 09:48 UTC
