### ISSUE TITLE
v0.13-rc7, serious increment in stale shares (ethermine.org)

### ISSUE THREAD

**Issue by AndreaLanfranchi** [ethereum-mining/ethminer#570] opened 2018-01-15 22:14 UTC
Do not know if it's a coincidence or not but since rc7 my average of stale shares as reported by ethermine.org just rocketed from roughly 3.2% to an astonishing 14%. in stratum mode.

Just running a round now with ethminer bound to eth-proxy to see if something changes.

**Comment by AndreaLanfranchi** [comment] 2018-01-15 22:52
![screen](https://user-images.githubusercontent.com/15280851/34964698-1978f450-fa4f-11e7-9f69-6aa5c7d247a5.png)

**Comment by AndreaLanfranchi** [comment] 2018-01-16 11:55
After 14 hours round with rc7 my stale share rate stabilized at 19~20% which is IMHO unacceptable.

**Comment by chfast** [comment] 2018-01-16 14:13
Thanks for testing! Is this a new regression in RC7?

**Comment by ddobreff** [comment] 2018-01-16 15:36
http://prntscr.com/i19ad8
Agree with you, I also see small amount of stales increase, I've pointed where restart has been called on miner.

**Comment by AndreaLanfranchi** [comment] 2018-01-16 17:08
I confirm. If you need i can run a round on rc6  and report

**Comment by chfast** [comment] 2018-01-16 17:23
RC7 only includes my change: https://github.com/ethereum-mining/ethminer/pull/560.

**Comment by jean-m-cyr** [comment] 2018-01-16 17:33
> RC7 only includes my change: #560.

Correct, but I saw a claim go by that it didn't happen in rc6. Don't see that #560 would have to do with it, but that's why I ask.

**Comment by chfast** [comment] 2018-01-16 17:42
The https://github.com/ethereum-mining/ethminer/pull/560 is definitely about reporting solutions, so this is relevant.

**Comment by jean-m-cyr** [comment] 2018-01-16 17:44
That's why I'd like to know whether or not this increase in stales are from converted invalids, or something else?

**Comment by jean-m-cyr** [comment] 2018-01-16 19:53
Hmmm... I'm seeing the same high (10-15%) stale rate with release 12 at ethermine!!!

**Comment by Kveri** [comment] 2018-01-17 12:20
I see similar numbers. With 0.12 I had no issue (no failed or rejects). On 0.13rc4 I saw failed - because of the race condition, now in 0.13rc7 I see same amount of rejects as number of fails in 0.13rc4.
A361+0:R14+0:F0
A394+1:R11+0:F0
and so on.

With 0.12 I have seen maybe 1 rejected share and 0 failed in 1000 accepted, so there is definitely some problem.

**Comment by HNielsen-Networks** [comment] 2018-01-17 14:11
Would be interested in knowing which cards you guys are using? On my RX570/580 im actually seeing far LESS stales compared to claymore, I was getting 4-8% stales with Claymore on a combined 24 x 8GPU setup (Some 4-10 stales per rig per hour), so far on 13.rc7 I am at a total of 6 stales across all rigs, due to this ethminer is actually outperforming Claymore by a fair margin, even though Claymore reports 15-20MH/s more per rig compared to ethminer.

**Comment by AndreaLanfranchi** [comment] 2018-01-17 15:27
Just ran two round of 90 minutes each on 0.13.rc7 and same release WITHOUT COMMIT 560

With commit 560
`0.13.rc7 [A118+3:R0+0:F0] Time: 01:30 (ethermine.org reports 28 stale = 23.72%)`

Without commit 560
`0.13.rc7 [A110+1:R0+0:F0] Time: 01:30 (ethermine.org reports 9 stale = 8.1%)`

Do not understand how 560 may have impacted the issue howver THERE is a difference.

**Comment by jean-m-cyr** [comment] 2018-01-17 16:49
Ran 6 hours of Claymore to get a baseline. It also exceeds 10% stales much of the time. I had expected something below 5% stales with Claymore. This doesn't seem right.

![snap1](https://user-images.githubusercontent.com/3529253/35055091-4abf199e-fb7c-11e7-9ec2-c4f9bec276b3.png)
![snap2](https://user-images.githubusercontent.com/3529253/35055094-4d3d0be0-fb7c-11e7-866b-7336e42be91a.png)

**Comment by AndreaLanfranchi** [comment] 2018-01-17 17:50
I think we're facing subjective (hardware software) and environmental (diff spike, pool, latency) challanges which are difficult to address into a single point.

What I know (and this reflects my personal situation):

1) I use for this tests a rig with 6x  GTX 1050 Ti
2) Average submit time of shares to pool is 40 to 50 ms
3) Using Claymore 10 I can push overclock a little higher squeezing from ech gpu 14.5 Mhs. Also with Claymore my effective hashrate (24hrs - orange line) lays almost over the reported hashrate (green line) despite the 1% fee. Blue line reports way less variances from the average (less spikes and dips). Average stale is 5 to 7%.
4) Using ethminer I have to stay roughly 5% below with overclocking to stay stable; stale share ratio is way higher (up to 25%). Orange average hashrate is constantly below the reported hashrate of a good 10%

I have the feeling (but please take my words with care and no offense) reading the code that all those boost's async operations may lead to some unpredictable results and, effectively, are loosing valid jobs.

I am C# dev and would very like to support and help but my C++ skills are quite newbie (yet I am having difficulties in creating a proper VS2017 project).

**Comment by riviera695** [comment] 2018-01-17 18:02
hello all together,
my Name is Andreas and i life in Germany. First i want to say, that all of you make a perfect job here. 
I have the same problem. Too much stale shares and the ethminer stopps after nearly 4 hour with incorrect messages and faulty stratum contact.
But this problem only at my Cuda Rig with 6 x Gtx 1070.
The other one with 10 x RX 480 runs perfectly under Rel.13.7.
So, i hope you can fix the problem. 
Thank you. Best regards
Andreas

**Comment by jean-m-cyr** [comment] 2018-01-17 18:27
@AndreaLanfranchi  In no way do I doubt your data, in fact your higher hash rate gives it more weight than mine. :-)

I'm just trying to wrap my head around how rc7 could cause this stale share spike. There's no doubt it's there, we've all seen it. Since I have no explanation I'm just collecting data points at this time.

To make matters worse, 13rc7 is behaving perfectly normal this morning at about 4% stale over the last hour, whereas yesterday it was seeing 10-15%. Same image, same setup (ubuntu, 4x1060)!!!

**Comment by jean-m-cyr** [comment] 2018-01-17 18:58
@AndreaLanfranchi 

> I have the feeling (but please take my words with care and no offense) reading the code that all those boost's async operations may lead to some unpredictable results and, effectively, are loosing valid jobs.

Quite sure you are correct. My background is low level embedded firmware, where we count machine cycles not microseconds, and use lean micro-kernel like eCos and FreeRTOS. I believe Boost goes too far in its quest for abstraction, and though that has sure benefits, it cannot but hinder performance.

**Comment by oliverw** [comment] 2018-01-18 13:14
@chfast Getting all shares rejected when mining with RC6 and RC7 against https://coinfoundry.org/pool/eth. Doesn't happen with the latest stable release.

**Comment by jean-m-cyr** [comment] 2018-01-18 16:50
@oliverw Verified. However this is a different issue from what this thread is about. Could you create a new problem ticket.

I expect this issue to be closed as the stale share issue appears to have gone on its own. External cause???

**Comment by aleqx** [comment] 2018-01-18 18:02
I can confirm that somewhere between 0.12 and 0.13rc7 there is a visible increase in stale shares (did tests for the past 48h). I think rc1 is not affected, but I may be wrong -- I'm testing rc1 now.

**Comment by jean-m-cyr** [comment] 2018-01-18 18:36
@aleqx I'm presently more concerned with a spike in stale shares reported by Ethermine a few days ago where stales shot up to 10-15% for an extended period. I'm seeing 3-4% stale now with 13rc7 at Ethermine which is normal on my setup. The situation lasted enough for me to take measurements with r12, 13rc6, as well as Claymore and saw a similar increase in generated shares, though not quite so severe for Claymore. I don't have corroborating evidence for this spike, other than the initial reports here for 13rc7, which was initially thought to be the cause.

I'm less and less convinced that we had anything to do with it. Of course, improving hash rate and lowering shares continues to be the priority.

**Comment by DDDanny** [comment] 2018-01-21 15:12
*voting for solved*
4x gtx 1070 (pl70%) and 1x 1060 (pl60%) performing well with latest 13rc7 @ ~150mh/s [12 gave ~148 mh/s] - using nanopool
Failed Shares from rc6 disappeared... params: -SC 1 -U -SP 1 -RH --farm-recheck 10000 --cuda --cuda-parallel-hash 4...

13rc6:   m  15:27:27|main      Speed 150.53 Mh/s    gpu/0 31.99  gpu/1 24.48  gpu/2 31.99  gpu/3 30.77  gpu/4 31.30  [A90+0:R0+0:F10] Time: 01:43

13rc7:       m  16:11:04|main      Speed 150.44 Mh/s    gpu/0 32.09  gpu/1 24.35  gpu/2 31.93  gpu/3 30.80  gpu/4 31.28  [A27+0:R0+0:F0] Time: 00:34

okay, only 34 minutes timeslot - can recheck log/DB log tomorrow

**Comment by chfast** [comment] 2018-01-21 21:44
Ok, I'm closing it now. The RC8 is being built. Please test it and report any issues there. Thanks all for hard work on testing and fixing bugs.

**Closed by chfast** 2018-01-21 21:44 UTC
Labels: bug, showstopper

**Comment by trick77** [comment] 2018-02-01 18:07
I realize this has been closed but I‘m definitely seeing an increase in stale shares in 0.13.0-rc8 and 0.14.0-dev0 on m CUDA rig. I haven’t yet tested other revisions, so can‘t say when it started. 0.13.0-rc1 is fine though, so it started sometime after that.

**Comment by aleqx** [comment] 2018-02-01 18:37
Same thing here (and I also remember 0.13rc1 to be ok!). I just posted this https://github.com/ethereum-mining/ethminer/issues/679 ... i'm going back to 0.12 or 0.13rc1

**Comment by jean-m-cyr** [comment] 2018-02-01 18:50
Let us know if you see the same periodic bouts of high stale share rates with these other versions you're going back to. Ethermine has been doing that a lot lately... everything fine at 2-4% stale, then boom! A hour of 10% stales!!! Not sure what is going on?

**Comment by aleqx** [comment] 2018-02-01 19:01
> Ethermine has been doing that a lot lately... everything fine at 2-4% stale, then boom! A hour of 10% stales!!! Not sure what is going on?

That was not my experience, and I've been mining on ethermine continuously since november. The times I saw changes in stale share rate was always equal to times I made changes on my end (software, hardware, lots of restarts/relaunches, etc).

**Comment by AndreaLanfranchi** [comment] 2018-02-01 19:06
I am on 14 dev 1 and do not expierence such problem. Mining regularly at 2~3% stale share rate.

**Comment by jean-m-cyr** [comment] 2018-02-01 19:07
us1.ethermine...

**Comment by aleqx** [comment] 2018-02-01 19:08
eu1 in my case, hmm ...

**Comment by DDDanny** [comment] 2018-02-01 19:10
If I'm right: Nanopool does'nt show the stales in server stats
Therefore I can only verify what ethermine reports in logs. Stale rate is very ok from my POV:

 m  20:04:02|main      Speed 150.28 Mh/s    gpu/0 24.37  gpu/1 31.96  gpu/2 31.96  gpu/3 30.83  gpu/4 31.15  [A615+3:R0+0:F0] Time: 12:11

Also checking DB Logs, no suspicious stales.

**Comment by xristianos** [comment] 2018-02-03 06:52
i can verify 5-10% stale shares in ethermine in the last few days. givin it 180mh/s with claymore. if this goes one im switching to nanopool. effective below 170mh/s.. fastest share found 79ms. i dont think lag is the problem. eu server

**Comment by trick77** [comment] 2018-02-03 07:53
I'm on eu1 too but as soon as I switch back to 0.13.0rc1 my stale shares go down to 3-5% which is normal for my rig and latency to the mining pool. With 0.13.0rc8 and higher, stale shares rise to 5-15%. I've tested i this over multiple 24 hour periods with my 250 Mh/s CUDA rig, **I'm now 100% convinced ethminer plays a role in this.** I just don't know what change led to the increase of stale shares. Since 0.14 is giving me great hashrates, I had the idea to just remove this commit. However, the code has advanced much further between rc6 and 0.14, can't undo just this commit.
If someone has an idea how to close in on this, I'm more than willing to test it. Since ETH difficulty is going up and up the payouts aren't what they used to be 2-3 months ago anyway :-)

Important:
Every miner version has to be run for at least 24h before jumping to a conclusion. Stale shares are always fluctuating but usually within a certain band.

**Comment by aleqx** [comment] 2018-02-03 15:33
For those considering moving to nanopool. I mined with nanopool for months but it bugged me that I couldn't see stale shares (ethminer v0.12 and some rc versions of 0.13 never reliably reported stale shares for me). 

Then a couple of weeks ago I did a 48h test to compare ethermine to nanopool (I have access to a farm of gtx1070's) and placed equal amounts of hashrate on both, 3.3 GH/s each. Started at the same time, finished at the same time, waited 6h after finishing for the dust to settle. Ethermine gave about 5% extra payment in the end (counting dust too). I stuck with Ethermine since.

Feel free to do your own tests.

**Comment by jean-m-cyr** [comment] 2018-02-03 16:38
@aleqx I would add that here in Atlanta, us1.ethermine responds with accepts in 30-40ms, whereas nanopool responds in around 150ms. I've gotta believe that I'm getting new job notifications faster as well.

**Comment by aleqx** [comment] 2018-02-03 17:02
Very useful observation! I used their EU servers, so if the same happens with their EU servers (I haven't looked at the accept response time, the ping times were the same for both) then it may explain why Ethermine came out better in my test.

**Comment by tsauce** [comment] 2018-03-02 15:10
Same here. I've actually switched pools from nanopool to ethermine because of nanopool share stealing

mining for 24 hours on v0.13.0 yielded me 19% stale shares 81% valid shares.
We shall see what ethminer-0.14.0.dev1 will do.

**Comment by chfast** [comment] 2018-03-02 15:48
@tsauce ethermine had some internal issues.

**Comment by tsauce** [comment] 2018-03-02 15:57
Do you know if they were all fixed? @chfast 

Also anyone else have issues getting the reported hashrate to show in v14 ? I know it wasn't working in v13 series.

I'm using the following:
ethminer -F http://127.0.0.1:8080/miner1 -U --dag-load-mode sequential --cl-global-work 8192 --farm-recheck 3000 _**--stratum-protocol 1 --report-hashrate**_ -HWMON --cuda-parallel-hash 4 --cuda-devices 0

**Comment by AndreaLanfranchi** [comment] 2018-03-02 16:11
@tsauce 
if you use -F you're working in farm mode thus --stratum-protocol is irrelevant as you're not working in stratum

**Comment by aleqx** [comment] 2018-03-02 16:46
getwork (-F) via a the ether-proxy will increase your stale share, sometimes dramatically ... it's a pretty bad proxy. Just connect directly to the pool using stratum. Both Ethermine and Nanopool allow hundreds of individual simultaneous connections, so you don't risk getting banned. If you have that many workers then I would disable hashrate reporting or else you will have hundreds x2 json-rpc messages going back and forth every 10 seconds (plus the tcp acks) ...

**Comment by AndreaLanfranchi** [comment] 2018-03-02 16:55
I begin to think that is is a specific issue for users of EthOS.
Apparently this is the default behavior which is quite inefficient:

1. eth-proxy
2. farm mode
3. one instance of miner per single GPU

**Comment by tsauce** [comment] 2018-03-02 16:59
It is exactly what I'm using. Was just about to post:

globalminer ethminer
maxgputemp 75
stratumproxy enabled
### flypool
proxywallet 0xWallet
proxypool1 us1-etc.ethermine.org:14444
proxypool2 eu1-etc.ethermine.org:14444
flags --cl-global-work 16384 --farm-recheck 3000 --stratum-protocol 1
--report-hashrate -HWMON

With claymore i always get reported hashrate. I just don't like claymore
because i feel i'm being raped by the high dev fee.

**Comment by aleqx** [comment] 2018-03-02 16:59
One miner instance per GPU is not an issue (helps other aspects), but doing `stratum > getwork > stratum` is not only inefficient, it's detrimental ... the eth-proxy implementation in particular is seriously affecting stales (the proxy reports share acceptance times of 100ms, while the miner sees 900-1100ms time)

**Comment by tsauce** [comment] 2018-03-02 17:00
I also am suspicious of nanopool. It's always reporting a higher hashrate,
about 5Mh/s more but on flypool it's lower, with more stale shares.

**Comment by AndreaLanfranchi** [comment] 2018-03-02 17:02
@aleqx 

> One miner instance per GPU is not an issue (helps other aspects)

could u explain ? can't really find one and would be interesting if I could improve my settings.

**Comment by trick77** [comment] 2018-03-02 17:23
> With claymore i always get reported hashrate. I just don't like claymore

@tsauce 
Looks like you are using ethOS. Please keep in mind that ethOS automatically starts a local eth-proxy when using ethminer, all local miners mine to this proxy. I believe eth-proxy doesn't pass on the reported hashrate no matter what you set in the flags, which will only affect the mining processes, not the eth-proxy. No eth-proxy will be used when mining with Claymore, it has it's own proxy.

**Comment by tsauce** [comment] 2018-03-02 17:26
Thanks @trick77 I may have to switch to just good old ubuntu in this case.
I thought it'd be easier to just use ethos, unless there's a way to tweak
it.

**Comment by aleqx** [comment] 2018-03-02 17:34
You can mine directly to stratum using ethos or any os, just configure your miners.

eth-proxy can pass on reported hashrate to stratum.

>> One miner instance per GPU is not an issue (helps other aspects)
> could u explain ? can't really find one and would be interesting if I could improve my settings.

find what? an aspect where per-gpu processes help? helps dealing with errors (from overclocking, for example), a single process will kill all cards when an error occurs, while per-process only kills one card. Mining speed is the same otherwise.

**Comment by tsauce** [comment] 2018-03-03 00:37
Wow, after 6 hours mining on claymore 100 shares submitted, 1 invalid
share. vs the 18% stale share rate.

**Comment by aleqx** [comment] 2018-03-03 01:33
> Wow, after 6 hours mining on claymore 100 shares submitted, 1 invalid
share. vs the 18% stale share rate.

... and if you use ethminer connecting to stratum directly, you would have slightly higher hashrate and better payouts

Stop making Claymore rich by giving him that outrageously high 2% fee and support open source software. Do a one time donation to the etminer devs instead!

**Comment by tsauce** [comment] 2018-03-03 02:58
Noted. I will switch soon. And yes to dev donation to ethminer one time
instead!

**Comment by DDDanny** [comment] 2018-03-03 08:54
>Same here. I've actually switched pools from nanopool to ethermine because of nanopool share stealing
 @tsauce
Can you shortly brief how you recognized?

Since you still keep the flag up for this topic I have done some checks here:
Nanopool reports the Shares as a table - this is twice higher than ethminer submitted shares...
...can you/some one else verify?

![grafik](https://user-images.githubusercontent.com/31635744/36932413-c6dff5ec-1ec8-11e8-9739-6436641a258d.png)

**Comment by tsauce** [comment] 2018-03-03 18:39
After running 6+ hours on ethminer-0.14.0.dev1 and changing config to pool
on ethos v1.2.9 I'm glad to say that the stale shares problem replicates
what you see with claymore. In other words much better and 3% or less stale
shares.

As for share stealing? I suspect that nanopool reports higher shares
because the share average is always higher there than compared to ethermine

I don't have enough datapoints yet but currently rough calculations are
like 3-4%.

**Comment by tsauce** [comment] 2018-03-03 18:42
<img width="939" alt="screen shot 2018-03-03 at 10 37 11 am" src="https://user-images.githubusercontent.com/19714142/36937941-94479a7a-1ecf-11e8-873d-5d52ac2f1d19.png">

<img width="954" alt="screen shot 2018-03-02 at 4 06 13 pm" src="https://user-images.githubusercontent.com/19714142/36937932-6b0b9cce-1ecf-11e8-9ae8-5bc8bc591c29.png">

After I switched, reported hashrate shows up (because it was probably proxy that wasn't submitting it - at least on ethos) BUT it reports as only 20Mh/s. Very odd.

**Comment by trick77** [comment] 2018-03-03 18:46
@tsauce this is an ethos bug, they don't enumerate the worker names.

**Comment by tsauce** [comment] 2018-03-03 18:54
Thanks @trick77 with that being said, ethos is the culprit :) Nothing to
see here.

**Comment by aleqx** [comment] 2018-03-03 20:17
> As for share stealing? I suspect that nanopool reports higher shares
because the share average is always higher there than compared to ethermine

I mined on nanopool for a long time unti lI did a 48h head-to-head test between nanopool and ethermine using two pretty large setups (read: farm). Ethermine was paying better from the getgo (used 0.05 eth payout), and in the end I had something like 7% more ETH on Ethermine. Never went back to Nanopool after that.

I also find Ethermine's interface better as it's more informative - you actually see the stales and invalids. I just *wish* it was more real-time. Takes forever to see effects of changes you make as they average everything over long periods -- including those single bars (they aren't averaged over 10 minutes like it may seem, but over 1h)

**Comment by aleqx** [comment] 2018-03-11 03:19
Ethermine: https://etherscan.io/address/0xea674fdde714fd979de3edf0f56aa9716b898ec8
Nanopool: https://etherscan.io/address/0x52bc44d5378309ee2abf1539bf71de1b7d7be3b5

See the ratio between uncles and blocks. Make your own judgement.
