### ISSUE TITLE
Ethminer exits with error code 1073741819

### ISSUE THREAD

**Issue by fenlasonb** [ethereum-mining/ethminer#1371] opened 2018-07-23 15:28 UTC
ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v 9
pause

outputs to this:

C:\Users\CrypteyMiney\Desktop\Miners\ETH\Nvidia>ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v 9
  m  11:27:10|main    |  ethminer version 0.14.0
  m  11:27:10|main    |  Build: windows / release +git. 24c65cf
 cu  11:27:10|main    |  Using grid size 8192 , block size 128

C:\Users\CrypteyMiney\Desktop\Miners\ETH\Nvidia>pause
Press any key to continue . . .

Anythoughts?

C:\Users\CrypteyMiney\Desktop\Miners\ETH\Nvidia\bin>ethminer.exe --list-devices -U

Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GTX 1070 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 8589934592
        Pci: 0000:05:00
[1] GeForce GTX 1070 Ti
        Compute version: 6.1
        cudaDeviceProp::totalGlobalMem: 8589934592
        Pci: 0000:06:00

C:\Users\CrypteyMiney\Desktop\Miners\ETH\Nvidia\bin>

**Comment by AndreaLanfranchi** [comment] 2018-07-23 15:30
You're not on version but on version 14

`m 11:27:10|main | ethminer version 0.14.0`

**Comment by fenlasonb** [comment] 2018-07-23 15:31
So weird thought i updated. Updating now to verify if working.

**Comment by fenlasonb** [comment] 2018-07-23 15:33
C:\Users\CrypteyMiney\Desktop\bin>ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v 9
 m 11:32:32 main     ethminer 0.15.0
 m 11:32:32 main     Build: windows/release
cu 11:32:32 main     Using grid size: 8192, block size: 128

C:\Users\CrypteyMiney\Desktop\bin>pause
Press any key to continue . . .

**Comment by fenlasonb** [comment] 2018-07-23 15:36
@AndreaLanfranchi 


C:\Users\CrypteyMiney\Desktop\bin>ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v 9
 m 11:35:05 main     ethminer 0.16.0.dev1
 m 11:35:05 main     Build: windows/release
cu 11:35:05 main     Using grid size: 8,192, block size: 128

C:\Users\CrypteyMiney\Desktop\bin>pause
Press any key to continue . . .


Also testing on 16... i must be doing something wrong

**Comment by AndreaLanfranchi** [comment] 2018-07-23 15:37
Please modify your .bat file like this

```
ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v 9
echo %ERRORLEVEL%
pause
```

and report back the error code which is printed out

**Comment by fenlasonb** [comment] 2018-07-23 15:42
@AndreaLanfranchi 


C:\Users\CrypteyMiney\Desktop\bin>ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v 9
 m 11:39:13 main     ethminer 0.16.0.dev1
 m 11:39:13 main     Build: windows/release
cu 11:39:13 main     Using grid size: 8,192, block size: 128

C:\Users\CrypteyMiney\Desktop\bin>echo -1073741819
-1073741819

C:\Users\CrypteyMiney\Desktop\bin>pause
Press any key to continue . . .

**Comment by AndreaLanfranchi** [comment] 2018-07-23 15:45
It's a windows error. Not much we can do as we're not sure which is the cause.

Please read from here
https://github.com/ethereum-mining/ethminer/issues/1165#issuecomment-394129880

**Comment by AndreaLanfranchi** [comment] 2018-07-23 15:47
Probably you have applied some windows updates

**Comment by AndreaLanfranchi** [comment] 2018-07-23 17:59
Have you installed or update manually some app ?

**Comment by fenlasonb** [comment] 2018-07-23 18:07
The strange part is nothing has changed. 

Not sure. i am currently going to redeploy windows 10 and not update a single thing.

Will keep u informed.

**Comment by fenlasonb** [comment] 2018-07-24 21:12
Update. Re installed windows disabled updates via services.msc gpo policy and via gui. Miner was working.

Rebooted the PC now miner has stopped working with same exit code as mentioned.

**Comment by fenlasonb** [comment] 2018-07-24 21:35
also tried workaround noted in #1165 (comment)

C:\Users\CrypteyMiney\Desktop\bin>ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v 9
m 17:33:09 main ethminer 0.16.0.dev1
m 17:33:09 main Build: windows/release
cu 17:33:09 main Using grid size: 8,192, block size: 128

C:\Users\CrypteyMiney\Desktop\bin>echo %ERRORLEVEL%
-1073741819

also tested with bat file

C:\Users\CrypteyMiney\Desktop\bin>ETHminerNvidia_only.bat

C:\Users\CrypteyMiney\Desktop\bin>ethminer.exe -U -P stratum1+ssl://0x8d36ea933dd02aeffb22318125a1d9583aefbd01.CrypteyMiney@us1.ethermine.org:5555 -v 9
m 17:31:21 main ethminer 0.16.0.dev1
m 17:31:21 main Build: windows/release
cu 17:31:21 main Using grid size: 8,192, block size: 128

C:\Users\CrypteyMiney\Desktop\bin>echo -1073741819
-1073741819

**Comment by ChronoXNL** [comment] 2018-07-28 11:03
As far as i've been able to tell, manually setting your VM size (large enough to handle the mem footprint of your cards), should be sufficient. It even works when you haven't restarted your miner.

I think the latest patch from Win 10 adjusted the VM mechanism, returning an error when VM size is not enough instead of just automagically increasing the VM size. I cannot confirm if this is the case however.

**Comment by fenlasonb** [comment] 2018-07-28 14:18
I just adjusted to virtual Memory to be 4gbs. No noted changed on exit code.

**Comment by webprophet** [comment] 2018-07-31 17:32
26gb VM should be good enough.  I have a rig w 8 -1070ti with 30 gig and it works fine.  The only other things that come to mind on the -1073741819 error are UAC, NVidia drivers, or Visual Studio redistributables.  For UAC you could try switching between admin and a newly created admin account to rule out UAC (Antivirus tosses this error when they corrupt UAC).  For Nvidia, reinstall and make sure you dont have any "other sound controllers" in device manager instead of "NVIDIA High Definition Audio" (video games toss the same error).  Lastly, you could try reinstalling C++ Redistributable (cmd.exe can generically toss this error with corrupted C++).  Good luck.
ps~ I hope you have run checkdisk and all that.  :)

**Comment by fenlasonb** [comment] 2018-07-31 17:47
Welp, i have already tried with a new admin account to rule out a UAC issue. I am re installing windows 1 more time via usb key.

Will report back :(

**Comment by lesjokolat** [comment] 2018-08-08 19:01
Just wanted to update, I changed to stratum, and used last couple of Dev 16 releases the error went away. On windows 10, AMD drivers 18.6.1, 18.7.1, 18.8.1. I also think all the recent stratum updates made are amazing just wanted to thank the devs for giving me a product I can switch from CM and Phoenix. I have never mined faster and more stable than here!

**Comment by lesjokolat** [comment] 2018-08-20 14:38
@jean-m-cyr 

Another one to close I think. I has same message but all stratum fixes and tweaks to my start up removed this as an issue.

**Comment by jean-m-cyr** [comment] 2018-08-20 14:43
Closing

**Closed by jean-m-cyr** 2018-08-20 14:43 UTC
Labels: duplicate, feed back needed
