### ISSUE TITLE
reconnect() does not work.

### ISSUE THREAD

**Issue by fobispo-link** [ethereum-mining/ethminer#998] opened 2018-04-11 16:31 UTC
I'm running the latest HEAD, and I'm having constant problems with my rigs not being able to reconnect, they stay in the loop for 3 seconds attempting to reconnect, but are never capable of doing so.

Simply restarting the miners solve the issue, I'm going to locally patch my code in the mean time to call exit() on reconnect so my startup scripts can re-start the ethminer.

**Comment by fobispo-link** [comment] 2018-04-12 01:42
This is where it stays stuck:

```
Apr 11 18:41:33 rig06 miner-start[20502]:   �~\~X  18:41:33|stratum |  Could not connect to stratum server 192.168.1.76:4444, Operation canceled
Apr 11 18:41:33 rig06 miner-start[20502]:   �~D�  18:41:33|stratum |  Disconnected from 192.168.1.76
Apr 11 18:41:33 rig06 miner-start[20502]:   �~D�  18:41:33|stratum |  Retrying in 3 ...
Apr 11 18:41:34 rig06 miner-start[20502]:   �~D�  18:41:34|stratum |  Retrying in 2 ...
Apr 11 18:41:35 rig06 miner-start[20502]:   �~D�  18:41:35|stratum |  Retrying in 1 ...
```

**Comment by Xeroeth** [comment] 2018-04-12 06:48
Yeah, I had the same problem just tonight. Also, if the connection is lost from time to time the miner crashes altogether.

**Comment by papampi** [comment] 2018-04-12 07:59
@ #988

**Comment by chfast** [comment] 2018-04-12 12:48
Duplicate of #988.

**Closed by chfast** 2018-04-12 12:48 UTC
