### ISSUE TITLE
Ethminer --List-devices returns nothing, program exits with no error (AMD)

### ISSUE THREAD

**Issue by skarlath** [ethereum-mining/ethminer#1126] opened 2018-05-20 07:08 UTC
Have been using Ethminer for a while on a few machines. On one of my machines, it suddenly stopped working. Attempting to use --List-devices returns nothing. Attempting to run the miner using known-good configurations results in no output using version 12. Using version 14 I get the version info and build info displayed before it exits. Setting --verbosity 9 does not give any additional information.

Is there any settings that can be used to get an actual error message?

**Comment by efrasyad** [comment] 2018-05-20 09:02
Are you running linux or windows?

**Comment by DUWENINK** [comment] 2018-05-20 12:37
Me too, Running On Windows 10 pre

**Comment by efrasyad** [comment] 2018-05-20 12:41
Please give more details of the case.
Complete command line, card details, logs, etc.
Otherwise, it is hard for someone else to provide feedback.

**Comment by skarlath** [comment] 2018-05-20 12:54
Running Win 10, 64bit. All the latest updates.

Rx 580 8gb video card. 

Running  ethminer.exe  --List-devices returns nothing to see in the command line, just an empty line.

Running ethminer.exe --verbosity 9 gives the version information (0.14.0) and the build information (windows / git+) before exiting. No other logs/errors/messages.

**Comment by skarlath** [comment] 2018-05-20 15:17
Windows device manager detects the video card correctly. It works for general 3d applications. Using the latest AMD drivers (8.4.1).

**Comment by skarlath** [comment] 2018-05-22 14:40
Another point of information. I have a second machine, this one using an NVIDIA GTX 1070 that suddenly stopped working after the last round of windows updates. This displays identical symptoms except for it generates an error message "Error: Unknown Error" when attempting to run regularly or to run ethminer --list-devices. I am suspecting that something with the latest windows updates changed something?

**Comment by skarlath** [comment] 2018-05-23 18:14
I performed an uninstall of the update that you mentioned but it did not appear to make any difference on the AMD hardware machine. Though whatever changes that it made might not be completely removed.

**Comment by efrasyad** [comment] 2018-05-23 18:45
try to remove all GPU and try with 1 GPU and see if that would make any difference.

**Comment by skarlath** [comment] 2018-05-24 02:58
Both machines (the one with a rx 580 and the other one with the 1070) each have a single GPU in them. I've tried changing the pci-e slots as well and it made no difference.

**Comment by AndreaLanfranchi** [comment] 2018-05-27 17:56
Please try follow the steps reported for same problem on #1165 and report what is the error code returned.

**Comment by AndreaLanfranchi** [comment] 2018-06-01 09:08
Any news here ?

**Comment by AndreaLanfranchi** [comment] 2018-06-01 14:34
Please see this comment
https://github.com/ethereum-mining/ethminer/issues/1182#issuecomment-393898692

Apparently there is something wrong with latest Windows Update(s)

**Comment by AndreaLanfranchi** [comment] 2018-06-03 09:13
@all please read this

https://github.com/ethereum-mining/ethminer/issues/1165#issuecomment-394129880

**Comment by k1t4r0** [comment] 2018-06-26 18:53
Guys, there's really something with the last windows update 1803.
I was having an issue with my HD7970, tried everything, and i mean EVERYTHING.
Today, i don't know why, i DISABLED the INTEL HD GRAPHICS and voila! Miner was going back to work.
Don't ask me why, but solved my issue!
Maybe it's this, try to disable any other "onboard"driver and see if it lists the GPU.

**Comment by saleelk** [comment] 2018-07-10 07:13
The issue is with the opencl icd. On the latest windows 10, MS mandates that the vendors opencl implementation be located in driver store and the Regkey pointing to it *shouldn't* be under HKLM\Software\Khronos. I've got a fix for it in the Khronos trunk but hasnt been integrated yet. Meanwhile How does ethminer load the ICD functions without explicitly loading opencl.dll?

**Comment by AndreaLanfranchi** [comment] 2018-09-19 15:45
Mostly related to windows updates as no more feed backs.
Closing

**Closed by AndreaLanfranchi** 2018-09-19 15:45 UTC

**Comment by sabotagebeats** [comment] 2020-07-04 11:35
I'm still having this issue.
