### ISSUE TITLE
CUDA error in func 'dev::eth::CUDAMiner::search' at line 489 : an illegal instruction was encountered.

### ISSUE THREAD

**Issue by vladgrand2** [ethereum-mining/ethminer#907] opened 2018-03-19 21:59 UTC
HiveOS 1063 GTX  nvidia 390.25
ethminer 0.13.0 and 0.14.0 dev4
Memory Overclokced +930 Samsung
Claymore 11.5 working 24/7 without any errors but gives low hashrate and less shares
ethminer works randomly sometimes 40 hours sometimes 6 or ever 2 hours and get:

CUDA error in func 'dev::eth::CUDAMiner::search' at line 489 : an illegal instruction was encountered.
X 20:04:50|cuda-4 Error CUDA mining: an illegal instruction was encountered
CUDA error in func 'dev::eth::CUDAMiner::search' at line 489 : an illegal instruction was encountered.
X 20:04:50|cuda-1 Error CUDA mining: an illegal instruction was encountered
CUDA error in func 'dev::eth::CUDAMiner::search' at line 489 : an illegal instruction was encountered.
X 20:04:50|cuda-2 Error CUDA mining: an illegal instruction was encountered
CUDA error in func 'dev::eth::CUDAMiner::search' at line 489 : an illegal instruction was encountered.
X 20:04:50|cuda-0 Error CUDA mining: an illegal instruction was encountered
CUDA error in func 'dev::eth::CUDAMiner::search' at line 489 : an illegal instruction was encountered.
X 20:04:50|cuda-3 Error CUDA mining: an illegal instruction was encountered

After this errors drop speed a little and continued working show it ok but pool didn't see miner and videocard stay cold. When trying restart miner driver crashing and only rig reboot help.

Trying stock without overclok and problem still appear randomly

P.S>Sorry for bad english

**Comment by ludvanieztha** [comment] 2018-03-20 01:50
as i ethminer user i would said u to much overclock
try oc below 850 cant go 900 ++ ( can run but will crash after 12 hours or less)
or u can try --cuda-gride-size 4096 less hashrate but its stable just do few tweaks in ethminer until ur rig stable in this miner u do ur own setting comparing claymore plug and play

**Comment by vladgrand2** [comment] 2018-03-20 04:35
I think need kind of fix. When error appeaer miner should count it and continue to work without hang. Less speed will do that miner not good at all. And If I do stock frequency this error appears too but less. I think this is not overcloking issue. This is issue about random error in driver maybe. When other miner Phoenix or Claymore catch error it just count it and continue dig.

**Comment by XhmikosR** [comment] 2018-03-22 09:33
Duplicate of #902

**Closed** 2018-04-10 23:08 UTC
