### ISSUE TITLE
Claymore Cuda 11 error, fresh installed Windows 10, 32GB Virtual, updated driver please help

### ISSUE THREAD

**Issue by Infamous540** [ethereum-mining/ethminer#1472] opened 2018-08-18 23:57 UTC
Hello, my ETC miner havnt been working for a while since windows is notoriusly sending updates during nights at the mining rig, so on friday i decided to try fix it ended up terribly I got a corrupt hard drive and BSOD constantly, couldent even boot windows 10 so I got help from microsoft to do a clean install. Ive updated the drivers, done all the windows 10 updates, tried increasing the virtual memory to many diffrent numbers cause this has solved it for before but now i cant mine atm I upload pics how the miner looks

1) picture of the initiation process

http://tinypic.com/view.php?pic=359bvaw&s=9#.W3ilDNsVTOQ

2) this is where Cuda error -11 starts showing

http://tinypic.com/view.php?pic=2nki9fb&s=9#.W3ilUtsVTOQ

3) Here you can see some cards are hashing but the claymore miner already failed

http://tinypic.com/view.php?pic=2cz1ts1&s=9#.W3imB9sVTOQ

I think this internal Motherboard GPU might also have something to do with it, ( i dont think it was activate before when i mined) but if i turn it off and try open the miner it shuts down after 2 seconds without any error message

I got 13x Geforce gigabyte windforce 6gb 1060s
Asrock h110 pro Btc

Would really appreciate any help so i can solve this and start mining again, What am i missing? thanks

**Comment by lesjokolat** [comment] 2018-08-19 00:09
you may need even more virtual memory you have alot of gpus. increase ut to 48 to 56 range. short term just try to mine with half of them...  --cuda-devices 0 1 2 3 also use -L 1 i think its to load dag one at time. See if you can get 4 running then add one ata time

**Comment by DekInc** [comment] 2018-08-19 00:54
I think you got the wrong website, this is for ethminer, but if you need any help setting ethminer let me know, i am in telegram at @DekInc

**Comment by Infamous540** [comment] 2018-08-19 01:10
I tried increasein it to 50GB-50GB and that just completly slowed the computer down, wouldent even initiate mining so dont think that is the solution, as i understand u can should only increase the virtual memory to X ammount of your ram and i got 8GB ram

**Comment by Infamous540** [comment] 2018-08-19 01:15
Dekinc sorry i dont use github so often, im trying to find claymore thread to post this on aswell but i cant find one? also gonna try ethminer & will contact u on telegram perhaps

**Comment by lesjokolat** [comment] 2018-08-19 01:17
did you just try to run 4 gpus then add one gpu at a time to it? if it slowed it down then the issue is def ram related as im guessing you are nearing your hd capacity. how much free disk space do you have?

**Comment by Infamous540** [comment] 2018-08-19 01:28
I tried just now adding the command and it says unknown command, added like this "-cuda devices 0 1 2 3" and "-L 1" and tried "-L1" its unknown commands it says

http://tinypic.com/view.php?pic=10zzksx&s=9#.W3jHedsVTOQ

**Comment by Infamous540** [comment] 2018-08-19 01:28
Also I have 41.1gb free it says on hard drive

**Comment by lesjokolat** [comment] 2018-08-19 01:39
you are using claymore miner. my commands wont help you. this site is for ethminer. 

like Deklinc said you could get help here for ethminer

**Comment by Infamous540** [comment] 2018-08-19 01:59
@lesjokolat Any chance u can redirect me to the right forum?

**Comment by lesjokolat** [comment] 2018-08-19 02:10
sure

https://bitcointalk.org/index.php?topic=1433925.24920

do a search for cuda 11 errors. 

i used to use it but ethminer is now faster for me. and dev free

**Comment by StefanOberhumer** [comment] 2018-08-19 08:10
As this is ethminer (no Claymore support here) closing this issue.

**Closed by StefanOberhumer** 2018-08-19 08:10 UTC
