### ISSUE TITLE
CL_INVALID_ARG_INDEX (-49) - R9 390 

### ISSUE THREAD

**Issue by edhemphill** [ethereum-mining/ethminer#554] opened 2018-01-13 08:24 UTC
On initial startup / DAG download am seeing this:

```
ed@miner1:~/work/ethminer/build/ethminer$ ./ethminer -G -M
  ℹ  02:16:59|ethminer  Found suitable OpenCL device [ Hawaii ] with 8577007616  bytes of GPU memory
Benchmarking on platform: CL
Preparing DAG for block #0
 cl  02:16:59|cl-0      No work. Pause for 3 s.
Warming up...
 cl  02:17:02|cl-0      New work: header #50c856ae… target 0000000000000002000000000000000000000000000000000000000000000000
 cl  02:17:02|cl-0      New seed #00000000…
 cl  02:17:03|cl-0      Platform: AMD Accelerated Parallel Processing
 cl  02:17:03|cl-0      Device:   Hawaii  / OpenCL 1.2 AMD-APP (2482.3)
 cl  02:17:03|cl-0      OpenCL kernel: Stable kernel
 cl  02:17:04|cl-0      Build info: 
 cl  02:17:04|cl-0      Creating light cache buffer, size 16776896
 cl  02:17:04|cl-0      Creating DAG buffer, size 1073739904
 cl  02:17:04|cl-0      Loading kernels
 cl  02:17:04|cl-0      Writing light cache buffer
 cl  02:17:04|cl-0      Creating buffer for header.
 cl  02:17:04|cl-0      Creating mining buffer
 cl  02:17:04|cl-0      Generating DAG
 cl  02:17:04|cl-0      DAG 0 %
 cl  02:17:04|cl-0      DAG 6 %
 cl  02:17:05|cl-0      DAG 12 %
 cl  02:17:05|cl-0      DAG 18 %
 cl  02:17:05|cl-0      DAG 25 %
 cl  02:17:05|cl-0      DAG 31 %
 cl  02:17:06|cl-0      DAG 37 %
 cl  02:17:06|cl-0      DAG 43 %
 cl  02:17:06|cl-0      DAG 50 %
 cl  02:17:06|cl-0      DAG 56 %
 cl  02:17:07|cl-0      DAG 62 %
 cl  02:17:07|cl-0      DAG 68 %
 cl  02:17:07|cl-0      DAG 75 %
 cl  02:17:07|cl-0      DAG 81 %
 cl  02:17:08|cl-0      DAG 87 %
 cl  02:17:08|cl-0      DAG 93 %
 cl  02:17:08|cl-0      Switch time 8659 ms / 5659907 us
Trial 1... 26230138
Trial 2... 28118708
Trial 3... 28115894
Trial 4... 28118708
Trial 5... 28010984
  ✘  02:17:29|cl-0      OpenCL Error: clSetKernelArg: CL_INVALID_ARG_INDEX (-49)
min/mean/max: 26230138/27718886/28118708 H/s
inner mean: 28081862 H/s
```

I tried to get a backtrace with gdb, but nothing useful. 
Using these drivers from AMD:
http://support.amd.com/en-us/kb-articles/Pages/AMD-Radeon-GPU-PRO-Linux-Beta-Driver%E2%80%93Release-Notes.aspx

I'm at top-of-tree master

Any ideas?  Thanks all.

R390 8GB, although lspci reports R290.

**Comment by chfast** [comment] 2018-01-13 10:15
I think I've seen it on my 280X.

**Comment by chfast** [comment] 2018-01-13 10:16
Duplicate of https://github.com/ethereum-mining/ethminer/issues/346.

**Closed by chfast** 2018-01-13 10:16 UTC
Labels: bug
