### ISSUE TITLE
Please add a WATCHDOG 

### ISSUE THREAD

**Issue by itaosson** [ethereum-mining/ethminer#327] opened 2017-09-22 01:25 UTC
Please increase the watchdog,when  cuda crash and something errors. we need
Automatic restart the miner.

**Comment by mikebzh44** [comment] 2017-09-22 06:17
+1

I'm using Claymore but Ethminer give me more hashrate. But I can't use it, it's not stable (lost GPU, ...).

Please add watchdog like in Claymore to specifie  a minimum hashrate and to reboot miner and / or computer.

Thanks.

**Comment by piotr-dobrogost** [comment] 2017-09-22 07:50
Duplicate of issue #274.

**Comment by ykhuat** [comment] 2017-09-23 02:35
Maybe you can have a look here.
Auto restart ethminer if no job for 5 min time.
Auto restart system if "CUDA ERROR" detected.
https://bitcointalk.org/index.php?topic=2195527.0

**Comment by marcofranssen** [comment] 2017-09-29 14:27
+1 

Also see #340.

**Comment by ThetaProtocol** [comment] 2017-10-21 23:00
https://ethmonitoring.com/
Been using there EthControl program the past two weeks acts as watchdog, allows for RC from anywhere including app. Has support for ethminer,eminer, claymore and more for other crypto. bonus uptime, pool stats+ profit charts. Downside is for more than one rig requires premuim, which maxes out at 99 rigs, which new accounts get 5 days free  which I find it worth it due to ease of use + etra features and you do get notifications on rigs you can customize

**Comment by bmatthewshea** [comment] 2017-10-23 21:25
If you run Linux you can do something like this in the meantime -
https://github.com/ethereum-mining/ethminer/issues/310#issuecomment-336573725
And use monit or similar to monitor it/restart service/etc by simply monitoring the output (or lack of).

**Comment by jaddison** [comment] 2017-12-29 18:38
Not sure if this works on Windows (I've only tested on Ubuntu 16.04), but see my gist here https://gist.github.com/jaddison/d4966f9e789d1d6e987fda49638a284b

It's an `ethminer` process wrapper to monitor output and restart as necessary. Lets you increase overclock settings a bit more as it will restart on `CUDA error` output.

**Comment by one-quaker** [comment] 2018-01-23 17:01
Some watchdogs you can find here (ethminer, ewbf, gpu load) [https://github.com/one-quaker/linux-rig-tools](url)
development in progress

**Comment by DeadManWalkingTO** [comment] 2018-02-27 20:36
After #757 (added --exit parameter to exit whenever an error occurred) you can use a watchdog.

Here is my [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) Windows7/8/10 [32/64] & Linux (Any Dist/Any Ver/Any Arch) (#735).

Check and feedback please.
Thank you!

**Comment by Undertrey** [comment] 2018-03-29 20:43
Also +1 open source BATCH watchdog script for Windows users:
https://github.com/Undertrey/FarmWatchBot/releases

**Comment by XhmikosR** [comment] 2018-06-20 06:32
Duplicate of #274

**Closed by XhmikosR** 2018-06-20 06:32 UTC
Labels: enhancement, help wanted
