### ISSUE TITLE
Error: vector::_M_range_check

### ISSUE THREAD

**Issue by Stellarend** [ethereum-mining/ethminer#1123] opened 2018-05-18 16:38 UTC
Recently, I've been getting this error every few days on my 6x1060 system my with a conservative overclock/undervolt (core +50, memory +300, max power 60w). I'm using Ethminer 0.13.0 stable release on Antegros Linux.

**Comment by satori-q3a** [comment] 2018-05-18 17:34
Since a 1060 is a 100w device, your 60w setting isn't very conservative as it means you're running at 60% power.  I run mine at 70% before they start to lose hashrates.

**Comment by chfast** [comment] 2018-05-21 13:17
We need more information about the error. Where it comes from? Logs?

**Comment by chfast** [comment] 2018-05-21 14:04
Duplicate of https://github.com/ethereum-mining/ethminer/issues/366.

**Closed by chfast** 2018-05-21 14:04 UTC
Labels: bug, duplicate, invalid
