### ISSUE TITLE
Ethminer broken on osx (was compile help)

### ISSUE THREAD

**Issue by mrlando** [ethereum-mining/ethminer#1446] opened 2018-08-10 16:22 UTC
**Describe the bug**
When I try to build ethminer 0.16.0 dev3 (or 2 or 1) on my iMac with Radeon Pro 580 I get a failure on cmake ..

**To Reproduce**
1. Download 'ethminer-0.16.0.dev3.zip'
2. Unzip
3. cd ethminer-0.16.0.dev3
4. mkdir build ; cd build
5 cmake ..

**Expected behavior**
A successful build.

**Desktop (please complete the following information):**
- Operating System: MacOS 10.13.6
- Hardware: iMac 27" Radeon Pro580
- Ethminer Version: 0.16 dev3

**Additional context**

Versions:

perl 5.28.0
git 2.18.0
cmake 3.12.1

Do I need to install more dependancies?

Terminal log:

```
cmake ..
CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    cmake/cable/bootstrap.cmake


CMake Error at CMakeLists.txt:5 (include):
  include could not find load file:

    CableBuildInfo


CMake Error at CMakeLists.txt:6 (include):
  include could not find load file:

    CableBuildType


CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    CableToolchains


CMake Error at CMakeLists.txt:8 (include):
  include could not find load file:

    HunterGate


CMake Error at CMakeLists.txt:10 (include):
  include could not find load file:

    defaults/HunterCacheServers


CMake Error at CMakeLists.txt:12 (cable_configure_toolchain):
  Unknown CMake command "cable_configure_toolchain".


-- Configuring incomplete, errors occurred!
Broes-iMac:build tim$ cmake --build .
Error: could not find CMAKE_PROJECT_NAME in Cache
Broes-iMac:build tim$ cmake .. -DETHASHCUDA=OFF -DETHASHCL=ON
CMake Error at CMakeLists.txt:3 (include):
  include could not find load file:

    cmake/cable/bootstrap.cmake


CMake Error at CMakeLists.txt:5 (include):
  include could not find load file:

    CableBuildInfo


CMake Error at CMakeLists.txt:6 (include):
  include could not find load file:

    CableBuildType


CMake Error at CMakeLists.txt:7 (include):
  include could not find load file:

    CableToolchains


CMake Error at CMakeLists.txt:8 (include):
  include could not find load file:

    HunterGate


CMake Error at CMakeLists.txt:10 (include):
  include could not find load file:

    defaults/HunterCacheServers


CMake Error at CMakeLists.txt:12 (cable_configure_toolchain):
  Unknown CMake command "cable_configure_toolchain".


-- Configuring incomplete, errors occurred!
```

**Comment by e2dy** [comment] 2018-08-10 16:29
Is not a bug... You need to download dependency yourself ...

**Comment by mrlando** [comment] 2018-08-10 17:09
Ok, but what dependencies do I need for MacOS?
I already installed the required packages mentioned in the BUILD.md document, Cmake, Git and Perl. Anything else?

**Comment by StefanOberhumer** [comment] 2018-08-10 17:36
I think you have also to download the submodules (cable) and install hunter.

Maybe its easier to follow
https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md
and build it from a `git clone`

**Comment by mrlando** [comment] 2018-08-10 18:01
I've looked at BUILD.md, but I can't find how to build it for MacOS from a `git clone`.
What are the terminal commands to do that? Or how do you install the submodules? (I've tried with brew but that doesn't work).
Sorry to be such a noob...

**Comment by StefanOberhumer** [comment] 2018-08-10 18:29
As I have no Mac I just can guess:
1.) `git clone https://github.com/ethereum-mining/ethminer.git`
2.) `cd ethminer`
3.) Follow build [Instructions](https://github.com/ethereum-mining/ethminer/blob/master/docs/BUILD.md#instructions)

**Comment by mrlando** [comment] 2018-08-11 12:07
Thanks a million Stefan!
I did a successful build, however the miner quits after running with `OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_VALUE (-30)` (See log below)

These were my steps:

1. `git clone https://github.com/ethereum-mining/ethminer.git`
2. `cd ethminer`
3. `git submodule update --init --recursive`
4. `brew upgrade perl git cmake` or `brew install` if not installed yet.
5. `mkdir build ; cd build`
6. `cmake .. -DETHASHCUDA=OFF -DETHASHCL=ON`
7. `cmake --build .`


Terminal log:
```
 m 14:03:30          ethminer 0.16.0.dev3-4+commit.2eaff643
 m 14:03:30          Build: darwin/release
 i 14:03:30          Found suitable OpenCL device [AMD Radeon Pro 580 Compute Engine] with 8589934592 bytes of GPU memory
 i 14:03:30          Configured pool europe.ethash-hub.miningpoolhub.com:20535
 i 14:03:30 main     Selected pool europe.ethash-hub.miningpoolhub.com:20535
 i 14:03:30 stratum  Stratum mode detected : ETHEREUMSTRATUM (NiceHash)
 i 14:03:30 stratum  Subscribed to stratum server
 i 14:03:30 stratum  Extranonce set to 1fb3 (nicehash)
 i 14:03:30 stratum  Difficulty set to 1.00117 (nicehash)
 i 14:03:30 stratum  Job: #04e38532… europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
 i 14:03:30 stratum  Pool difficulty: 4.30K megahash
 i 14:03:30 stratum  New epoch 204
 i 14:03:31 stratum  Authorized worker [XXXXXX]
 i 14:03:31 stratum  Established connection with europe.ethash-hub.miningpoolhub.com:20535 at  [35.156.160.57:20535]
 i 14:03:31 stratum  Spinning up miners...
cl 14:03:31 cl-0     No work. Pause for 3 s.
cl 14:03:34 cl-0     No work. Pause for 3 s.
 m 14:03:35          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 14:03:37 cl-0     No work. Pause for 3 s.
cl 14:03:40 cl-0     No work. Pause for 3 s.
 m 14:03:40          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 14:03:43 cl-0     No work. Pause for 3 s.
 m 14:03:45          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 14:03:46 cl-0     No work. Pause for 3 s.
cl 14:03:49 cl-0     No work. Pause for 3 s.
 m 14:03:50          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 14:03:52 cl-0     No work. Pause for 3 s.
cl 14:03:55 cl-0     No work. Pause for 3 s.
 m 14:03:55          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 14:03:58 cl-0     No work. Pause for 3 s.
 m 14:04:00          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 14:04:01 cl-0     No work. Pause for 3 s.
cl 14:04:04 cl-0     No work. Pause for 3 s.
 m 14:04:05          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 14:04:07 cl-0     No work. Pause for 3 s.
 i 14:04:09 stratum  Job: #a1078c3e… europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
cl 14:04:10 cl-0     Platform: Apple
cl 14:04:10 cl-0     Device:   AMD Radeon Pro 580 Compute Engine / OpenCL 1.2 
 m 14:04:10          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 14:04:11 cl-0     OpenCL kernel
cl 14:04:11 cl-0     Loading binary kernel /Users/tim/./ethminer/kernels/ethash_amd radeon pro 580 compute engine_lws192.bin
 X 14:04:11 cl-0     Failed to load binary kernel: /Users/tim/./ethminer/kernels/ethash_amd radeon pro 580 compute engine_lws192.bin
 X 14:04:11 cl-0     Falling back to OpenCL kernel...
cl 14:04:11 cl-0     Creating light cache buffer, size: 43515712
cl 14:04:11 cl-0     Creating DAG buffer, size: 2785017728
cl 14:04:11 cl-0     Loading kernels
cl 14:04:11 cl-0     Writing light cache buffer
cl 14:04:11 cl-0     Creating buffer for header.
cl 14:04:11 cl-0     Creating mining buffer
 i 14:04:12 stratum  Job: #8a3fcdd3… europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
 m 14:04:15          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
 i 14:04:19 cl-0     2.59375 GB of DAG data generated in 7597 ms.
 X 14:04:19 cl-0     OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_VALUE (-30)
 m 14:04:20          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
 m 14:04:25          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
 i 14:04:27 stratum  Job: #92ce4df2… europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
libc++abi.dylib: terminating with uncaught exception of type cl::Error: clEnqueueWriteBuffer
/Users/tim/ethminer1/Miner ETHMiner GPU starter.command: line 21: 85059 Abort trap: 6           ./ethminer/ethminer -G -P stratum+tcp://[XXXXXX]@europe.ethash-hub.miningpoolhub.com:20535
```

**Comment by e2dy** [comment] 2018-08-11 12:43
You need to put the binary kernel in the kernel folder or use the option to disable binary kernel using

**Comment by mrlando** [comment] 2018-08-11 13:11
I've added step 8. `sudo make install`
Now it started a build in /usr/local/bin/ (how do I change this location?)
In that directory I found a kernel folder and ethminer. I moved them both to a separate folder but it still exits with the same OpenCL Error.
Building with the `-DBINKERN=OFF` flag doesn't generate the kernel folder but starting the resulting ethminer still gives the same log output.

**Comment by mrlando** [comment] 2018-08-11 13:15
There is a warning during `cmake .. --build`

Is this bad?

```
[ 25%] Building CXX object libhwmon/CMakeFiles/hwmon.dir/wrapnvml.cpp.o
/Users/tim/ethminer/libhwmon/wrapnvml.cpp:53:2: warning: "Unrecognized platform: need NVML DLL path for this platform..."
      [-W#warnings]
#warning "Unrecognized platform: need NVML DLL path for this platform..."
 ^
1 warning generated.
[ 28%] Building CXX object libhwmon/CMakeFiles/hwmon.dir/wrapadl.cpp.o
/Users/tim/ethminer/libhwmon/wrapadl.cpp:38:2: warning: "Unrecognized platform: need ADL DLL path for this platform..."
      [-W#warnings]
#warning "Unrecognized platform: need ADL DLL path for this platform..."
 ^
1 warning generated.
```

**Comment by mrlando** [comment] 2018-08-11 14:29
Where does it go wrong then?

It says: ` X 16:06:48 cl-0     Failed to load binary kernel: /Users/tim/./ethminer/kernels/ethash_amd radeon pro 580 compute engine_lws256.bin`
But my directory is `/Users/tim/ethminer/kernels/` 
Is it looking in the wrong directory?

**Comment by StefanOberhumer** [comment] 2018-08-11 21:31
`/Users/tim/./ethminer/kernels/` is the same as `/Users/tim/ethminer/kernels/` so this should not be an issue

**Comment by e2dy** [comment] 2018-08-11 21:52
copy binary kernel files from the git source to your folder /Users/tim/ethminer/kernels/

**Comment by mrlando** [comment] 2018-08-12 09:59
@e2dy The files are already there. 

@StefanOberhumer Ok, but it's looking for a file that isn't there anyway `ethash_amd radeon pro 580 compute engine_lws256.bin`. Shouldn't it be looking for `ethash_ellesmere_lws256.bin`? Because my graphics card (Radeon Pro 580) is an Ellesmere (as far as I know).

I did a test with the precompiled 0.16.0.dev1 I downloaded from the site. That one gives the same `Failed to load binary kernel: /Users/tim/./ethminer/kernels/ethash_amd radeon pro 580 compute engine_lws256.bin` error but starts hashing and does not give the `OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_VALUE (-30)` error.
Removing the kernels directory has no influence, it still works.

**Comment by StefanOberhumer** [comment] 2018-08-12 13:59
> `OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_VALUE (-30)` 

I'm just using CUDA maybe an OpenCL guy can help more

> `amd radeon pro 580 compute engine`

It seems your card is identified as `amd radeon pro 580 compute engine` (use of OpenCL function `m_device.getInfo<CL_DEVICE_NAME>()`)

**Comment by mrlando** [comment] 2018-08-15 05:48
Are there no OpenCL guys that can help with this issue?

**Comment by smurfy** [comment] 2018-08-15 10:37
The problem got introduced after ``v0.16.0.dev1``. I did some test on the 1.of august, getting the same error.

````
cl 17:54:02 cl-0     Creating mining buffer
 i 17:54:07 stratum  Job: #1357468c… eu1.ethermine.org [35.234.90.95:4444]
 m 17:54:07          Speed 0.00 Mh/s gpu0 0.00 0C 0% [A0] Time: 00:00
 i 17:54:07 cl-0     2.57812 GB of DAG data generated in 5,343 ms.
 X 17:54:07 cl-0     OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_VALUE (-30)
 m 17:54:12          Speed 0.00 Mh/s gpu0 0.00 0C 0% [A0] Time: 00:00
 m 17:54:17          Speed 0.00 Mh/s gpu0 0.00 0C 0% [A0] Time: 00:00
 i 17:54:19 stratum  Job: #149c8f88… eu1.ethermine.org [35.234.90.95:4444]
libc++abi.dylib: terminating with uncaught exception of type cl::Error: clEnqueueWriteBuffer
Abort trap: 6
````

As far as i understand it, it is not directly related to the binary kernels, because their loading itself already fails. But with the binary kernel the "fallback" cl kernel also got modified, which probably did something.

The thing is, i don't know nothing about opencl, also i only can test it on my hackingtosh at work and i'm quite busy at the moment at work :).. 

So one step to help figuring out the problem is, to verify that the ``v0.16.0.dev1`` branch really still works.
Then go forward commit for commit (commits changing nothing with opencl can be skipped)
My guess would be its some of the commits of @jean-m-cyr between 23 july and 1 august. (he did a lot of work improving opencl for linux and windows, osx always was not working that great in the first place)
If the commit is identified, we can look into what exactly has been changed and figure out how to fix it.

List of all commits after ``v0.16.0.dev1``: https://github.com/ethereum-mining/ethminer/compare/v0.16.0.dev1...master

**Comment by jean-m-cyr** [comment] 2018-08-15 13:04
There was recent mention of dropping OsX support in v0.16?

**Comment by jean-m-cyr** [comment] 2018-08-15 14:50
Failed to build??? Every commit builds clean at TravisCI.

**Comment by smurfy** [comment] 2018-08-15 14:52
> Failed to build??? Every commit builds clean at TravisCI.

nope that one had a bug, you pushed another commit after that fixing something :) (clang compile error)

**Comment by jean-m-cyr** [comment] 2018-08-15 14:52
As for the run time error, I can't say. There are very few OsX users, and even fewer developers (none willing to take responsibility for OsX bugs and fixes.)

**Comment by jean-m-cyr** [comment] 2018-08-15 14:56
> nope that one had a bug, you pushed another commit after that fixing something :) (clang compile error)

Ah yes, remember now... Had to #ifdef out the offending code. Clumsy, I admit, but o way to test.

**Comment by jean-m-cyr** [comment] 2018-08-15 14:58
Which brings me back to my original position. Without active OsX testers and developers, how can we realistically support OsX?

**Comment by smurfy** [comment] 2018-08-15 15:02
I try to do some tests tomorrow. For example adding debug outputs around all ``clEnqueueWriteBuffer``  to see which call crashes.  I already tried the static of the zero thing. which did NOT do the trick.
There is another static in kickminer maybe this is the cause. 

But hopefully i can tell tomorrow what exactly is the problem.

> Which brings me back to my original position. Without active OsX testers and developers, how can we realistically support OsX?

Well, i'm willing to test and possible to fix some problems on osx. But osx itself is a lot slower than linux.
instead of doing 30 i only have 16 (with dev1), but to be fair i was not able to overclock the card on osx.

**Comment by mrlando** [comment] 2018-08-15 15:03
Sorry to hear about the lack of OSX developers, I'm afraid I am no help either, no programming skills what so ever...
But as one of the few OSX users I would like to say: Please continue support if possible.

**Comment by smurfy** [comment] 2018-08-15 15:10
@mrlando 

you can try removing the "static" from the following lines
https://github.com/ethereum-mining/ethminer/commit/b6284f58576a1234367c5f75a4689edbfa01309b#diff-351ecf6184087be8f2eb519124e5324fR443

https://github.com/ethereum-mining/ethminer/commit/b6284f58576a1234367c5f75a4689edbfa01309b#diff-351ecf6184087be8f2eb519124e5324fR292

And trying to compile and run it.

**Comment by smurfy** [comment] 2018-08-15 15:35
``static const uint32_t one = 1;`` to ``const uint32_t one = 1;``
and
``uint32_t const static zerox3[3] = {0, 0, 0};`` to ``uint32_t const zerox3[3] = {0, 0, 0};``

so only the word ``static``

**Comment by mrlando** [comment] 2018-08-15 15:59
I removed those, it did build but giving the same error.
Maybe I'm not doing it right though. The version number is `0.16.0.dev3-12+commit.a6292182.dirty`

**Comment by smurfy** [comment] 2018-08-15 16:16
well was a shot in the dark, will try tomorrow

**Comment by mrlando** [comment] 2018-08-15 16:36
There is a workername 'eth1-gpu':
`-P stratum2+tcp://[username].eth1-gpu:x@europe.ethash-hub.miningpoolhub.com:20535`
And the older builds work fine.

**Comment by lesjokolat** [comment] 2018-08-15 16:49
ok i see now, but new vers i would look to remove stratum2 change to stratum. For fun remove the :x for password also where is -G

**Comment by mrlando** [comment] 2018-08-15 17:10
Removed the 2 an the :x, but if I remove the -G it doesn't run.

**Comment by lesjokolat** [comment] 2018-08-15 17:18
i meant i didnt see -G should be in.  can you add -v 9 see more detailed error output then?

**Comment by lesjokolat** [comment] 2018-08-15 18:39
can you now add this to startup

--cl-local-work 192  -L 0

**Comment by mrlando** [comment] 2018-08-15 21:17
Both parameters don't make a difference.

**Comment by smurfy** [comment] 2018-08-16 10:31
@mrlando i created a new branch with PR #1461  
This should fix the crash problem at least. But some more knowledgeable people need to have a look at my PR before it goes to master :)

**Comment by mrlando** [comment] 2018-08-16 11:06
Thanks, it works!
But its taking a long time before it starts hashing. About 1 minute longer than the older builds.

```
 m 13:02:30          ethminer 0.16.0.dev3-13+commit.c519030e
 m 13:02:30          Build: darwin/release
 i 13:02:30          Found suitable OpenCL device [AMD Radeon Pro 580 Compute Engine] with 8589934592 bytes of GPU memory
 i 13:02:30          Configured pool europe.ethash-hub.miningpoolhub.com:20535
 i 13:02:30          Configured pool eu1.ethermine.org:4444
 i 13:02:30 main     Selected pool europe.ethash-hub.miningpoolhub.com:20535
 i 13:02:30 stratum  Trying 35.156.160.57:20535 ...
 i 13:02:30 stratum  Socket connected to  [35.156.160.57:20535]
 i 13:02:30 stratum  {
	"id" : 1,
	"method" : "mining.subscribe",
	"params" : 
	[
		"ethminer-0.16.0.dev3-13+commit.c519030e",
		"EthereumStratum/1.0.0"
	]
}
 i 13:02:30 stratum  {
	"error" : null,
	"id" : 1,
	"result" : 
	[
		[
			"mining.notify",
			"deadbeefcafebabe26a8080000000000",
			"EthereumStratum/1.0.0"
		],
		"8b59"
	]
}
 i 13:02:30 stratum  Stratum mode detected : ETHEREUMSTRATUM (NiceHash)
 i 13:02:30 stratum  Subscribed to stratum server
 i 13:02:30 stratum  Extranonce set to 8b59 (nicehash)
 i 13:02:30 stratum  {
	"id" : 2,
	"method" : "mining.extranonce.subscribe",
	"params" : []
}
 i 13:02:30 stratum  {
	"id" : 3,
	"method" : "mining.authorize",
	"params" : 
	[
		"mrlando.eth1-gpu",
		""
	]
}
 i 13:02:30 stratum  {
	"id" : null,
	"method" : "mining.set_difficulty",
	"params" : 
	[
		1.0011717677116394
	]
}
 i 13:02:30 stratum  Difficulty set to 1.00117 (nicehash)
 i 13:02:30 stratum  {
	"id" : null,
	"method" : "mining.notify",
	"params" : 
	[
		"81b0",
		"1aef3e83f99bae13313f5e70bb3ee12078c8d78b7f31d83af211b7612d47eb12",
		"a512d82d19d8cb3a038f59dd572eb2aca8520b89f3fbe7803dcf10c3fad01859",
		false
	]
}
 i 13:02:30 stratum  Job: #a512d82d… europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
 i 13:02:30 stratum  Pool difficulty: 4.30K megahash
 i 13:02:30 stratum  New epoch 205
 i 13:02:31 stratum  {
	"error" : null,
	"id" : 3,
	"result" : true
}
 i 13:02:31 stratum  Authorized worker mrlando.eth1-gpu
 i 13:02:31 stratum  Established connection with europe.ethash-hub.miningpoolhub.com:20535 at  [35.156.160.57:20535]
 i 13:02:31 stratum  Spinning up miners...
cl 13:02:31 cl-0     No work. Pause for 3 s.
cl 13:02:34 cl-0     No work. Pause for 3 s.
cl 13:02:37 cl-0     No work. Pause for 3 s.
cl 13:02:40 cl-0     No work. Pause for 3 s.
 m 13:02:40          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 13:02:43 cl-0     No work. Pause for 3 s.
cl 13:02:46 cl-0     No work. Pause for 3 s.
cl 13:02:49 cl-0     No work. Pause for 3 s.
 m 13:02:50          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 13:02:52 cl-0     No work. Pause for 3 s.
cl 13:02:55 cl-0     No work. Pause for 3 s.
cl 13:02:58 cl-0     No work. Pause for 3 s.
 m 13:03:00          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
cl 13:03:01 cl-0     No work. Pause for 3 s.
 i 13:03:01 stratum  {
	"id" : null,
	"method" : "mining.notify",
	"params" : 
	[
		"81b1",
		"1aef3e83f99bae13313f5e70bb3ee12078c8d78b7f31d83af211b7612d47eb12",
		"291f0c21b68bc36bb1e58842a5f781d73f4dd474595b88a60e4a799dfedb1dc8",
		false
	]
}
 i 13:03:01 stratum  Job: #291f0c21… europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
cl 13:03:04 cl-0     Platform: Apple
cl 13:03:04 cl-0     Device:   AMD Radeon Pro 580 Compute Engine / OpenCL 1.2 
cl 13:03:06 cl-0     OpenCL kernel
cl 13:03:06 cl-0     Loading binary kernel /Users/tim/./ethminer/kernels/ethash_amd radeon pro 580 compute engine_lws192.bin
 X 13:03:06 cl-0     Failed to load binary kernel: /Users/tim/./ethminer/kernels/ethash_amd radeon pro 580 compute engine_lws192.bin
 X 13:03:06 cl-0     Falling back to OpenCL kernel...
cl 13:03:06 cl-0     Creating light cache buffer, size: 43646912
cl 13:03:06 cl-0     Creating DAG buffer, size: 2793401984
cl 13:03:06 cl-0     Loading kernels
cl 13:03:06 cl-0     Writing light cache buffer
cl 13:03:06 cl-0     Creating buffer for header.
cl 13:03:06 cl-0     Creating mining buffer
 m 13:03:10          Speed 0.00 Mh/s gpu0 0.00 [A0] Time: 00:00
 i 13:03:13 cl-0     2.60156 GB of DAG data generated in 7766 ms.
cl 13:03:13 cl-0     Switch time: 12300662 us.
 i 13:03:15 stratum  {
	"id" : null,
	"method" : "mining.notify",
	"params" : 
	[
		"81b2",
		"1aef3e83f99bae13313f5e70bb3ee12078c8d78b7f31d83af211b7612d47eb12",
		"c632c2fd4c9ed124b5225ba4ce908d3e01d4579f4852900fb74efe561a5ea5f1",
		false
	]
}
 i 13:03:15 stratum  Job: #c632c2fd… europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
cl 13:03:16 cl-0     Switch time: 791934 us.
 m 13:03:20          Speed 2.55 Mh/s gpu0 2.55 [A0] Time: 00:00
 m 13:03:30          Speed 6.81 Mh/s gpu0 6.81 [A0] Time: 00:01
 i 13:03:30 main     {
	"id" : 9,
	"jsonrpc" : "2.0",
	"method" : "eth_submitHashrate",
	"params" : 
	[
		"0x000000000000000000000000000000000000000000000000000000000067e2b4",
		"0x87744032c083098a395ab17f81920783f91184d5397e435b0a31bca3ab037d2a"
	],
	"worker" : "eth1-gpu"
}
 i 13:03:30 stratum  {
	"error" : null,
	"id" : 9,
	"result" : true
}
 i 13:03:36 stratum  {
	"id" : null,
	"method" : "mining.notify",
	"params" : 
	[
		"81b3",
		"1aef3e83f99bae13313f5e70bb3ee12078c8d78b7f31d83af211b7612d47eb12",
		"10962b78f079e397932b58fd6dcbfbb6a59c3602ed1fac42a0ff52e05f38042f",
		false
	]
}
 i 13:03:36 stratum  Job: #10962b78… europe.ethash-hub.miningpoolhub.com [35.156.160.57:20535]
cl 13:03:37 cl-0     Switch time: 642358 us.
 m 13:03:40          Speed 11.06 Mh/s gpu0 11.06 [A0] Time: 00:01
 m 13:03:50          Speed 12.55 Mh/s gpu0 12.55 [A0] Time: 00:01
```

**Comment by smurfy** [comment] 2018-08-16 13:16
Fixed and merged, cant tell anything related to speed. Its quite crap on osx ^^

**Closed** 2018-08-16 13:16 UTC
Labels: bug, opencl
